<div class="wish-list-remove-product-block">
    <?php if(!empty($this->useBtn)) :?>
        <a href="javascript:;" class="remove-wished-product btn" title="<?php echo $this->btnName;?>" data-pid="<?php echo $this->productId;?>"><?php echo $this->btnName;?></a>
    <?php else :?>
        <a href="javascript:;" class="ticon-close error action-close remove-wished-product" title="<?php echo $this->btnName;?>" data-pid="<?php echo $this->productId;?>"></a>
    <?php endif;?>
</div>


