<div class="wish-list-block">
    <?php if(!$this->isLogged) :?>
        <a href="<?php echo $this->websiteUrl . $this->clientPage ;?>" class="wish-product <?php echo (!empty($this->htmlClass)) ? $this->htmlClass : '';?>" title="<?php echo $this->toFavoritesBtnName;?>"><?php echo $this->toFavoritesBtnName;?></a>
    <?php else :?>
        <a href="javascript:;" class="wish-product add-to-wish-list <?php echo (!empty($this->htmlClass)) ? $this->htmlClass : '';?> <?php echo ($this->readyWished) ? 'already-wished' : ''?>" title="<?php echo $this->toFavoritesBtnName;?>" data-pid="<?php echo $this->productId;?>" data-client-page="<?php echo $this->websiteUrl . $this->clientPage ;?>" data-to-profile="<?php echo $this->goToProgile;?>"><?php echo $this->toFavoritesBtnName;?></a>
    <?php endif;?>
    <input type="hidden" class="secureToken" name="<?php echo Tools_System_Tools::CSRF_SECURE_TOKEN;?>" value="<?php echo Tools_System_Tools::initSecureToken(Shopping::SHOPPING_SECURE_TOKEN);?>">
</div>