<?php if (!empty($this->quantityDiscountPrices)): ?>
    <?php foreach ($this->quantityDiscountPrices as $quantity => $discountInfo): ?>
        <?php $discountAmount = $this->currency->toCurrency($discountInfo['unitSave']);?>
        <p class="m0px">
            <?php echo $this->translate('Buy') . ' ' . $quantity . ' ' . $this->translate(
                'for'
            ) . ' ' . $this->currency->toCurrency($discountInfo['price']) . ' ' . $this->translate(
                'each and save'
            ) . ' ' . $discountAmount; ?>
        </p>
    <?php endforeach; ?>
<?php endif; ?>