<script>
    $(function(){
        verifyThrottleLimit();
        function verifyThrottleLimit(){
            $.ajax({
                url:'<?php echo $this->websiteUrl;?>plugin/shopping/run/throttleCheckLimit/',
                type:"POST",
                dataType:"json"
            }).done(function(response) {
                if(response.error == '0') {
                    setTimeout(function(){
                        verifyThrottleLimit()
                    }, 10000);
                    $('#throttle-verify-block').addClass('hidden');
                } else {
                    $('#throttle-desc').text(response.responseText);
                    $('#throttle-verify-block').removeClass('hidden');
                    setTimeout(function(){
                        verifyThrottleLimit()
                    }, 10000);
                }
            });
        }

        $('#throttle-verify-block').on('click', '.close', function(){
            $(this).closest('li').addClass('hidden');
        });
    });
</script>

<div id="throttle-verify-block" class="dash-notification-box hidden">
    <ul class="throttle-verify-message dash-notification-list list-unstyled">
        <li class="item error">
            <p class="box-close"><i class="close icon-cancel icon-close"></i></p>
            <p class="title"></p>
            <p id="throttle-desc" class="desc"></p>
        </li>
    </ul>
</div>

<style>
    .dash-notification-box {
        position: fixed;
        top: 40px;
        left: 40%;
        z-index: 100000;
        width: 404px;
    }

    .dash-notification-list {
        margin: 0;
    }

    .dash-notification-list .item.error {
        background-color: #E2676A;
    }

    .dash-notification-list .item {
        background-color: #EAEAEA;
        padding: 10px 20px 20px;
        margin: 0;
        color: #FFF;
        font-size: 13px;
        -webkit-border-radius: 4px;
        -moz-border-radius: 4px;
        -ms-border-radius: 4px;
        border-radius: 4px;
        list-style-type: none;
    }

    .dash-notification-list .item p.box-close {
        text-align: right;
        font-size: 0.75em;
    }

    .dash-notification-list .item p {
        margin: 0;
    }

    .dash-notification-list .item p.title {
        font-weight: bold;
        margin-bottom: 5px;
    }

    .dash-notification-list .item p {
        margin: 0;
    }
</style>
