<div class="plugin-filtering-widget plugin-filtering-wrap" data-filterid="<?php echo $this->filterId; ?>">
    <h4><?php echo $this->translate('Filter Builder'); ?><br/>

        <p><?php echo $this->translate('Tags'); ?>:&nbsp;<?php echo implode(' | ', $this->tags); ?></p>

        <p style="font-size: 80%">!!! <?php echo $this->translate('Checked filters will not be displayed to users'); ?>
            !!!</p>
    </h4>
    <ul>
    <?php if (!empty($this->tags)) : ?>
        <li>
            <label class="filter-label"><?php echo $this->translate('Category');?></label>
            <ul>
                <?php foreach ($this->tags as $tagId => $tagName) :?>
                <li>
                    <label>
                        <?php
                        $checked = false;
                        $disabled = false;
                        if (isset($this->settings['tags'])) {
                            if ($this->settings['tags'] === '1') {
                                $checked = $tagId;
                                $disabled = true;
                            } elseif ( is_array($this->settings['tags'])
                                && in_array($tagId, $this->settings['tags']) ) {
                                $checked = $tagId;
                            }
                        }
                        echo $this->formCheckbox(
                            'hide[tags][]',
                            $tagId,
                            array(
                                'title'   => $this->translate('Check to hide from users'),
                                'disable' => $disabled
                            ),
                            array(
                                'checked'   => $tagId,
                                'unChecked' => false
                            )
                        );
                        echo $tagName; ?>
                    </label></li>
                <?php endforeach; ?>
            </ul>
        </li>
    <?php endif; ?>
    <?php if ($this->priceRange) :?>
        <li>
            <label class="filter-label"><?php echo $this->translate('Price');?></label>
            <div class="slider"
                 data-min="<?php echo $this->priceRange['min'];?>"
                 data-max="<?php echo $this->priceRange['max'];?>" ></div>
            <input type="hidden" name="price" />
        </li>
    <?php endif; ?>
    <?php foreach ($this->filters as $filterId => $filter) : ?>
        <li data-attributeId="<?php echo $filterId; ?>">
            <label class="filter-label">
                <?php
                echo $this->formCheckbox(
                    'hide[' . $filter['attribute_id'] . ']',
                    (array_key_exists($filterId, $this->settings) && $this->settings[$filterId] === '1'),
                    array(
                        'title' => $this->translate('Check to hide from users'),
                        'class' => 'filter-cb'
                    ),
                    array(
                        'checked'   => true,
                        'unChecked' => false
                    )
                );
                echo $filter['label'];
                ?>
            </label>
            <ul>
                <?php $values = array_unique($filter['value']); ?>
                <?php foreach ($values as $value) : ?>
                    <li>
                        <label>
                            <?php
                            $checked = false;
                            $disabled = false;
                            if (isset($this->settings[$filterId])) {
                                if ($this->settings[$filterId] === '1') {
                                    $checked = $value;
                                    $disabled = true;
                                } elseif (is_array($this->settings[$filterId]) && in_array(
                                        $value,
                                        $this->settings[$filterId]
                                    )
                                ) {
                                    $checked = $value;
                                }
                            }
                            echo $this->formCheckbox(
                                'hide[' . $filter['attribute_id'] . '][]',
                                $checked,
                                array(
                                    'title'   => $this->translate('Check to hide from users'),
                                    'disable' => $disabled
                                ),
                                array(
                                    'checked'   => $value,
                                    'unChecked' => false
                                )
                            );
                            echo $value;
                            ?></label>
                    </li>
                <?php endforeach; ?>
            </ul>
        </li>
    <?php endforeach; ?>
    </ul>
    <div class="footer">
        <button type="submit"><?php echo $this->translate('Save'); ?></button>
    </div>
</div>

<style type="text/css">
    .plugin-filtering-widget ul {
        margin: 0 0 0 10px;
        padding: 5px;
    }

    .plugin-filtering-widget ul li {
        list-style: none;
        padding: 0;
        margin: 0;
    }

    .plugin-filtering-widget > ul > li:nth-child(odd) {
        background-color: #eee;
    }

    .plugin-filtering-widget ul label.filter-label {
        font-weight: bold;
    }

    .plugin-filtering-wrap {
        width: auto;
        overflow: hidden;
        position: relative;
        border: 3px dashed #eee;
    }

    .plugin-filtering-wrap > h4 {
        border-bottom: 3px dashed #eee;
        padding: 3px;
        text-transform: uppercase;
    }

    .plugin-filtering-wrap > h4 > span {
        font-size: 80%;
    }

    .plugin-filtering-wrap > .footer {
        border-top: 3px dashed #eee;
    }
</style>