<form class="plugin-filtering-widget plugin-filtering-wrap" action="<?php echo $this->url();?>" method="post">
    <input type="hidden" name="filterId" value="<?php echo $this->filterId; ?>" />
    <h4><?php echo $this->translate('Filter Widget Builder'); ?></h4>
    <ul>
    <?php if (!empty($this->tags)) : ?>
        <li>
            <label class="filter-label">
                <input type="hidden" name="show[tags]" value="none" />
                <input type="checkbox" class="mass-change" title="<?php echo $this->translate('toggle all');?>"
                    <?php
                    $tagsChecked = array_reduce($this->tags, function($count, $tag) {
                        if ($tag['checked']) {
                            $count++;
                        }
                        return $count;
                    });
                    if ($tagsChecked == sizeof($this->tags)) {
                        echo "checked";
                    }
                    unset($tagsChecked);
                    ?>
                    />
                <?php echo $this->translate('Category');?>
            </label>
            <ul>
                <?php foreach ($this->tags as $tag) :?>
                <li>
                    <label>
                        <input type="checkbox" name="show[tags][]"
                               value="<?php echo $tag['id']; ?>"
                                <?php if ($tag['checked']) :?>
                               checked
                                <?php endif; ?>
                            />
                        <?php echo $tag['name']; ?>
                    </label></li>
                <?php endforeach; ?>
            </ul>
        </li>
    <?php endif; ?>
    <?php if (!empty($this->brands)) : ?>
        <li>
            <label class="filter-label">
                <input type="hidden" name="show[brands]" value="none"/>
                <input type="checkbox" class="mass-change" title="<?php echo $this->translate('toggle all');?>"
                    <?php
                    $brandsChecked = array_reduce($this->brands, function($count, $brand) {
                        if ($brand['checked']) {
                            $count++;
                        }
                        return $count;
                    });
                    if ($brandsChecked == sizeof($this->brands)) {
                        echo "checked";
                    }
                    unset($brandsChecked);
                    ?>
                    />
                <?php echo $this->translate('Brands');?>
            </label>
            <ul>
                <?php foreach ($this->brands as $brand) :?>
                <li>
                    <label>
                        <input type="checkbox" name="show[brands][]"
                               value="<?php echo $brand['id']; ?>"
                                <?php if ($brand['checked']) :?>
                               checked
                                <?php endif; ?>
                            />
                        <?php echo $brand['name']; ?>
                    </label></li>
                <?php endforeach; ?>
            </ul>
        </li>
    <?php endif; ?>
    <li class="filter-price">
        <label class="filter-label">
            <input type="checkbox" name="show[price]"
                   value="all"
                    <?php if (!empty($this->settings['price'])): ?>
                   checked
                    <?php endif; ?>
                />
            <?php echo $this->translate('Price'); ?>
        </label>
    </li>
    <?php foreach ($this->filters as $filterId => $filter) : ?>
        <li data-attributeId="<?php echo $filterId; ?>">
            <label class="filter-label">
                <input type="hidden" name="show[<?php echo $filter['attribute_id']; ?>]" value="0" />
                <input type="checkbox" class="mass-change" title="<?php echo $this->translate('toggle all');?>" />
                <?php echo $filter['label']; ?>
            </label>
            <ul>
                <?php $values = array_unique($filter['value']); ?>
                <?php foreach ($values as $value) : ?>
                    <li>
                        <label>
                            <?php
                            $checked = false;
                            $disabled = false;
                            if (isset($this->settings[$filterId])) {
                                if ($this->settings[$filterId] === '1') {
                                    $checked = $value;
                                    $disabled = true;
                                } elseif (is_array($this->settings[$filterId]) && in_array(
                                        $value,
                                        $this->settings[$filterId]
                                    )
                                ) {
                                    $checked = $value;
                                }
                            }
                            echo $this->formCheckbox(
                                'show[' . $filter['attribute_id'] . '][]',
                                $checked,
                                array(
                                    'title'   => $this->translate('Check to hide from users'),
                                    'disable' => $disabled
                                ),
                                array(
                                    'checked'   => $value,
                                    'unChecked' => false
                                )
                            );
                            echo $value;
                            ?></label>
                    </li>
                <?php endforeach; ?>
            </ul>
        </li>
    <?php endforeach; ?>
    </ul>
    <div class="footer">
        <button type="submit"><?php echo $this->translate('Save'); ?></button>
    </div>
</form>

<style type="text/css">
    .plugin-filtering-widget ul {
        margin: 0 0 0 10px;
        padding: 5px;
    }

    .plugin-filtering-widget ul li {
        list-style: none;
        padding: 0;
        margin: 0;
    }

    .plugin-filtering-widget > ul > li:nth-child(odd) {
        background-color: #eee;
    }

    .plugin-filtering-widget ul label.filter-label {
        font-weight: bold;
        cursor: pointer;
    }

    .plugin-filtering-wrap {
        width: auto;
        overflow: hidden;
        position: relative;
        border: 3px dashed #eee;
    }

    .plugin-filtering-wrap > h4 {
        border-bottom: 3px dashed #eee;
        padding: 3px;
        text-transform: uppercase;
    }

    .plugin-filtering-wrap > h4 > span {
        font-size: 80%;
    }

    .plugin-filtering-wrap > .footer {
        border-top: 3px dashed #eee;
    }

    .plugin-filtering-wrap label > input[type=checkbox] {
        cursor: pointer;
    }
</style>