<?php if (!empty($this->tags) || !empty($this->brands) || !empty($this->filters) || !empty($this->priceRange)) : ?>
<form class="plugin-filtering-widget filtering-form">
    <ul>
    <?php if (!empty($this->tags)) : ?>
        <li>
            <header><?php echo $this->translate('Category'); ?></header>
            <ul>
            <?php foreach ($this->tags as $tag) :?>
                <li>
                    <label>
                        <input type="checkbox"
                               name="category"
                               value="<?php echo $tag['name']; ?>"
                               <?php if ($tag['checked']) echo 'checked'; ?>
                            />
                        <a href="<?php echo $this->url().'?category='.urlencode($tag['name']); ?>"><?php echo $tag['name']; ?></a></label>
                </li>
            <?php endforeach; ?>
            </ul>
        </li>
    <?php endif; ?>
    <?php if (!empty($this->brands)) : ?>
        <li>
            <header><?php echo $this->translate('Brand'); ?></header>
            <ul>
            <?php foreach ($this->brands as $brand) :?>
                <li>
                    <label>
                        <input type="checkbox"
                               name="brand"
                               value="<?php echo $brand['name']; ?>"
                               <?php if ($brand['checked']) echo 'checked'; ?>
                            />
                        <a href="<?php echo $this->url().'?brand='.urlencode($brand['name']); ?>"><?php echo $brand['name']; ?></a></label>
                </li>
            <?php endforeach; ?>
            </ul>
        </li>
    <?php endif; ?>
    <?php if ($this->priceRange) : ?>
        <li class="filter-price">
        <?php if ($this->priceRange === 'slider') : ?>
            <div class="price-slider" data="<?php echo json_encode($this->priceRange); ?>"></div>
        <?php else : ?>
            <label class="filter-label">
                <?php echo $this->translate('Price'); ?>
            </label>
            <label><?php echo $this->translate('From'); ?></label>
            <input type="text" class="price-field price-min"
                   placeholder="<?php echo $this->priceRange['min'] ?>"
                   value="<?php if (!empty($this->priceRange['from'])) echo $this->priceRange['from']; ?>"
                />
            <label><?php echo $this->translate('To'); ?></label>
            <input type="text" class="price-field price-max"
                   placeholder="<?php echo $this->priceRange['max']; ?>"
                   value="<?php if (!empty($this->priceRange['to'])) echo $this->priceRange['to']; ?>"
                />
        <?php endif; ?>
            <?php
            if (!empty($this->priceRange['from']) && !empty($this->priceRange['to'])) {
                $priceFilter = $this->priceRange['from'].'-'.$this->priceRange['to'];
            } else {
                $priceFilter = '';
            }
            ?>
            <input type="hidden" name="price" value="<?php echo $priceFilter; ?>"/>
        </li>
    <?php endif; ?>
    <?php foreach ($this->filters as $filter) : ?>
        <li>
            <header><?php echo $filter['label']; ?></header>
            <ul>
                <?php
                foreach ($filter['value'] as $value) : ?>
                    <?php $checked = in_array($value, $filter['checked']); ?>
                    <li>
                        <label>
                            <input type="checkbox"
                                   name="<?php echo $filter['name']; ?>"
                                   value="<?php echo $value; ?>"
                                   <?php if ($checked) { echo 'checked'; }; ?>
                                />
                            <a href="<?php echo $this->url().'?'.$filter['name'].'='.urlencode($value); ?>"><?php echo $value; ?></a></label>
                    </li>
                <?php endforeach; ?>
            </ul>
        </li>
    <?php endforeach; ?>
    </ul>
    <button><?php echo $this->translate('Apply filters');?></button>
</form>
<?php if ($this->priceRange) :?>
<script>
    $(function () {
        <?php if ($this->priceRange === 'slider') :?>
        $('div.price-slider').each(function () {
            var self = this,
                data = $(self).data();
            $(this).slider({
                range: true,
                min: data.min,
                max: data.max,
                values: [ data.from, data.to ],
                slide: function( event, ui ) {
                    $(self).find('input[name=price]').val( ui.values[0] + '-' + ui.values[1] );
                }
            });
        });
        <?php else : ?>
        $(".price-field").on('change', function(){
           $('input[name=price]').val(''+parseFloat($(".price-min").val())+'-'+ parseFloat($(".price-max").val()));
        });
        <?php endif; ?>
    });
</script>
<?php endif; ?>
<?php endif; ?>
