<div class="product-options-listing" data-productId="<?php echo  $this->product->getId();?>">
<?php foreach ($this->product->getDefaultOptions() as $option): ?>
    <?php $uniqName = 'product-'.$this->product->getId().'-option-'.$option['id']; ?>
    <?php
    if (($option['type'] === Models_Model_Option::TYPE_DROPDOWN || $option['type'] === Models_Model_Option::TYPE_RADIO) && !empty($option['selection'])){
        $options = array();
        $defaultId = null;
	    $template = $option['type'] === Models_Model_Option::TYPE_RADIO ? ' <span>(%s%s)</span>' : ' (%s%s)';
        foreach ($option['selection'] as $item) {
            $options[$item['id']] = Models_Model_Option::TYPE_RADIO ? $this->escape($item['title']) : $item['title'];
            if (floatval($item['priceValue']) != 0){
                $options[$item['id']] .= sprintf($template, $item['priceSign'], ($item['priceType'] === 'unit'?$this->currency($item['priceValue']):$item['priceValue'].'%'));
            }
            if ($item['isDefault']) $defaultId = $item['id'];
        }
    }
    ?>
    <div class="product-option option-<?php echo strtolower(preg_replace('/[^\w\d]/i', '', $option['title']));?>" id="product-<?php echo $this->product->getId();?>_option-<?php echo $option['id'];?>" data-type="<?php echo $option['type'];?>">
        <label for="<?php echo $uniqName; ?>" ><?php echo $option['title'];?></label>
        <?php if ($option['type'] === Models_Model_Option::TYPE_DROPDOWN): ?>
        <?php echo  $this->formSelect($uniqName, $defaultId, null, $options); ?>
        <?php elseif ($option['type'] === Models_Model_Option::TYPE_RADIO): ?>
        <div>
        <?php echo  $this->formRadio($uniqName, $defaultId, array('escape'=>false), $options, ''); ?>
        </div>
        <?php elseif ($option['type'] === Models_Model_Option::TYPE_TEXT): ?>
        <input type="text" name="<?php echo  $uniqName;?>" id="" />
        <?php elseif ($option['type'] === Models_Model_Option::TYPE_DATE): ?>
        <input type="date" name="<?php echo  $uniqName;?>" onmouseover="if (window.jQuery && jQuery.ui) $(this).datepicker() ;" id="" />
        <?php endif; ?>
    </div>
<?php endforeach; ?>
</div>
