<ul class="related-products">
    <?php foreach ($this->related as $product) : ?>
	<?php if (!$product->getEnabled()) continue; ?>
    <li>
        <?php if ($product->getPhoto()) : ?>
        <?php
            $photo = explode('/', $product->getPhoto());
            $src = $this->websiteUrl.'media/'.$photo[0].'/'.$this->imageSize.'/'.$photo[1];
        ?>
        <a class="product-image" href="<?php echo $this->websiteUrl . ($product->getPage() !== null ? $product->getPage()->getUrl(): '' );?>" title="<?php echo $product->getPage()->getH1(); ?>">
            <img src="<?php echo $src; ?>" alt="<?php echo $product->getName(); ?>" title="<?php echo $product->getName(); ?>" />
        </a>
        <?php endif; ?>
        <a class="product-title" href="<?php echo $this->websiteUrl . ($product->getPage() !== null ? $product->getPage()->getUrl(): '' );?>" title="<?php echo $product->getPage()->getH1(); ?>"><?php echo $product->getName(); ?></a>
        <p class="product-description"><?php echo $product->getShortDescription();?></p>
        <span class="product-price"><?php echo $this->currency($product->getPrice());?></span>
        <?php if(isset($this->checkoutPageUrl)):?>
           <a class="tcart-add related-cart-add" href="javascript:;" data-pid="<?php echo $product->getId();?>"><?php echo $this->translate('Add to cart');?></a>
        <?php endif;?>
    </li>
    <?php endforeach ; ?>
</ul>
<?php if(isset($this->checkoutPageUrl)):?>
    <script type="text/javascript">
        $(function() {
            $(document).on('click', '.related-cart-add', function(e) {
                e.preventDefault();
                var pid  = $(this).data('pid');
                $.post('<?php echo $this->websiteUrl;?>plugin/cart/run/cart/', {
                    pid     : pid
                }, function() {
                    window.location.href = '<?php echo $this->websiteUrl, $this->checkoutPageUrl; ?>';
                })
            })
        });
    </script>
<?php endif;?>
