<script type="text/javascript" charset="utf-8">
    $('#fieldset-rcol').append('<div><label for="<?php echo $this->fieldLable; ?>">' +
        '<?php echo $this->fieldLable; ?></label>' +
        ' <input type="text" class="customer-attribute" id="<?php echo $this->fieldLable; ?>"' +
        ' data-uid="<?php echo $this->userId; ?>" data-attribute="<?php echo $this->attribute; ?>"' +
        ' value="<?php echo $this->value; ?>" /></div>');
</script>
