<div class="seotoaster product-set-wrap">
    <div class="product-set-controlls">
        <h4>Magic space: Productset</h4>
        <label>
            <span><?php echo $this->translate('Autocalculate set price'); ?></span>
            <?php echo $this->formCheckbox('autoCalculateSetPrice', $this->autoCalculatePrice, array('id' => 'auto-calculate-set-price'), array(1, 0)); ?>
        </label>
        <!-- manual set price -->
        <label <?php echo ($this->autoCalculatePrice) ? 'style="display:none;"' : ''; ?>>
            <span><?php echo $this->translate('Specify set price manualy'); ?></span>
            <input type="text" name="manualSetPrice" id="manual-set-price" value="<?php echo $this->currentSetPrice; ?>" />
        </label>
    </div>
    <div class="product-set-content"><?php echo $this->content; ?></div>
</div>

<style type="text/css">

    .seotoaster.product-set-wrap,
    .seotoaster.product-set-wrap div.product-set-controlls,
    .seotoaster.product-set-wrap div.product-set-content {
        overflow: hidden;
        background-color: #fff;
    }
    .seotoaster.product-set-wrap {
        width: 100%;
        overflow: hidden;
        position: relative;
        border: 3px dashed #eee;
    }
    .seotoaster.product-set-wrap div.product-set-controlls {
        background: rgba(248, 248, 248, 1);
        padding: 10px 5px 5px 5px;
        min-height: 30px;
    }
    .seotoaster.product-set-wrap div.product-set-controlls label {
        font-size: 14px;
        color: #ccc;
        font-weight: normal;
    }
    .seotoaster.product-set-wrap div.product-set-controlls h4 {
        padding: 3px;
        color: #ccc;
        text-transform: uppercase;
    }
    .seotoaster.product-set-wrap div.product-set-controlls input[type="text"] {width: 150px;padding: 3px;}
    .seotoaster.product-set-wrap div.product-set-content {
        padding: 5px;
        background: background: rgba(250, 250, 250, 1);
    }
</style>
<script type="text/javascript">
    $(document).on('keypress', '#manual-set-price', function(e) {
        var newPrice = parseFloat($(this).val()).toFixed(2);
        if(e.keyCode == 13 && newPrice) {
            $.ajax({
                url        : '<?php echo $this->websiteUrl;?>api/store/products/id/<?php echo $this->currentSetId; ?>',
                type       : 'put',
                beforeSend : showSpinner(),
                data       : JSON.stringify({price: newPrice}),
                dataType   : 'json'
            }).done(function(response) {
                hideSpinner();
                var oldPrice = $('*[itemprop="price"]').text();
                $('*[itemprop="price"]').text(oldPrice.replace(/[0-9,.]+/g, newPrice));
                showMessage('<?php echo $this->translate('Set price updated'); ?>');
            });
        }
    }).on('change', '#auto-calculate-set-price', function() {
        $('#manual-set-price').parent('label').fadeToggle();
        var checked = $(this).prop('checked') ? 1 : 0 ;
        $.post('<?php echo $this->websiteUrl;?>plugin/shopping/run/setSettings/', {
            'settings': {
                productId          : '<?php echo $this->currentSetId; ?>',
                autoCalculatePrice : checked
            }
        });
    });
</script>