const messages = {
    en: {
        message: {
            'searchByNameSkuMpn':'search by name, SKU, MPN',
            'selectBrand':'Filter by brand..',
            'noResultFoundSearch':'No result',
            'selectTag':'Filter by tag..',
            'selectInventory':'Filter by stock..',
            'withSelectedDo':'With selected do',
            'noMassActions': 'nothing',
            'first':'first',
            'last':'last',
            'previous':'previous',
            'next':'next',
            'total':'total',
            'records':'records',
            'found':'found',
            'rowsPerPage':'Rows per page',
            'unlimited':'unlimited',
            'no':'no',
            'yes':'yes',
            'name':'Name',
            'stock':'Stock',
            'brand':'Brand',
            'suppliers':'Suppliers',
            'sku':'Sku',
            'mpn':'Mpn',
            'freeShipping':'Free shipping',
            'weight':'Weight',
            'price':'Price',
            'salesCount':'Sales count',
            'cs_new':'Abandoned carts',
            'cs_completed':'Payment Received',
            'cs_shipped':'Items Shipped',
            'cs_refunded':'Refunded purchase',
            'cs_pending':'Merchant action required -  Customer charged',
            'cs_processing':'Technical processing  - Customer not charged',
            'cs_delivered':'Items delivered',
            'cs_canceled':'canceled',
            'cs_error':'error',
            'cs_partial':'Partial Order',
            'cs_not_verified':'Quote Signed (Signature only quote)',
            'totalSales':'Total',
            'updated':'Updated',
            'massActionAssignBrand':'Assign Brand',
            'selectProductBrand':'select brand',
            'orCreateNew':'or create new',
            'apply':'Apply',
            'massActionChangeProductBrand':'Assign brand',
            'pleaseChooseProductBrandOrAddNew':'Please choose product brand or add new one',
            'smsNoMassActionRecordsFound':'No products have been found with this product brand',
            'pleaseChooseAtLeastOneProduct':'Please choose at least one product',
            'notValidBrand':'Brand name should contain the following characters only: a-z, A-Z, 0-9, -(dash), _(underscore) and space.',
            'done':'Done',
            'canNotAssignBrand':'Can not assign brand',
            'productTabTitle':'Manage your product catalog',
            'massActionChangeProductTemplate':'Assign page template',
            'selectProductTemplate':'select template',
            'massActionAssignTemplate':'Assign page template',
            'pleaseChooseProductTemplate':'Please choose product template',
            'canNotAssignTemplate':'Can not assign template',
            'templateHasBeenChanged':'Template has been changed',
            'massActionChangeProductTax':'Assign tax',
            'massActionAssignTax':'Assign tax',
            'Non taxable':'Non taxable',
            'Default':'Default',
            'Alternative':'Alternative',
            'Alternative 2':'Alternative 2',
            'selectTaxCategory':'Select tax category',
            'taxHasBeenChanged':'Tax has been changed',
            'canNotAssignTax':'Can not assign tax',
            'massActionChangeProductShipping':'Assign free shipping',
            'selectProductShipping':'Select',
            'No free shipping':'No free shipping',
            'Free shipping':'Free shipping',
            'massActionAssignShipping':'Assign free shipping',
            'pleaseChooseProductShipping':'Please choose product shipping',
            'shippingHasBeenChanged':'Shipping has been changed',
            'canNotAssignShipping':'Can not assign shipping',
            'massActionChangeProductTag':'Assign/Remove tag',
            'brandHasBeenChanged':'Brand has been changed',
            'massActionAssignTag':'Manage tags',
            'massActionChangeProductCompany':'Assign suppliers',
            'massActionAssignCompany':'Assign suppliers',
            'massActionDeleteProduct':'Delete (nonreversible)',
            'massActionDelProduct':'Delete products',
            'areYouSure':'Are you sure?',
            'thisOperationCannotBeUndone':'This operation cannot be undone!',
            'productHasBeenDeleted':'Deleted',
            'canNotDeleteProduct':'Can not delete product(s)',
            'massActionToggleProduct':'Enable/Disable',
            'massActionEnableDisableProducts':'Enable/Disable products',
            'enable':'Enable',
            'disable':'Disable',
            'canNotToggleProduct':'Can not toggle product(s)',
            'productHasBeenChanged':'Done',
            'productHasBeenEnabled':'Enabled',
            'productHasBeenDisabled':'Disabled',
            'massActionProductQuantity':'Assign quantity',
            'infinite':'infinite',
            'or':'OR',
            'specifyInventoryStockLevel':'specify inventory stock level',
            'pleaseEnterValidNumber':'Please enter valid number',
            'canNotChangeProductInventory':'Can not change product inventory',
            'massActionProductNegativeStock':'Assign negative stock',
            'select':'select',
            'disable negative stock':'disable negative stock',
            'enable negative stock':'enable negative stock',
            'pleaseChooseOption':'Please select option',
            'negativeStockHasBeenChanged':'Negative stock has been changed',
            'canNotAssignNegativeStock':'Can not assign negative stock',
            'massActionAssignPromo':'Assign promo',
            'setSelectedProductsOnSale':'Set selected products on sale',
            'salePrice':'Sale price',
            'time':'Time',
            'salesTimeInfo':'Sales time depends on your local server time settings',
            'startingDate':'Starting date',
            'expiryDate':'Expiry date',
            'wrongDateFormat':'Wrong date format',
            'enterCorrectPrice':'Enter correct promo price',
            'promoHasBeenAdded':'Promo has been added',
            'massActionAssignProductOptionPrice':'Assign product/option price',
            'products':'Products',
            'options':'Options',
            'priceSignModifier':'Adjustment type',
            'priceTypeModifier':'Adjustment unit',
            'priceWillChangeTo':'Change price to',
            'minusOptionProcess':'Exclude negative-priced options',
            'attention':'Note: Products with a price of 0 will not be updated.',
            'dialogTitleTotal':'Total',
            'titleRecord':'Record',
            'titleRecords':'Records',
            'massActionAssignPrice':'Apply Price Update',
            'dialogAllProductsMatchingFilter':'Apply to all filtered products',
            'noProductsFound':'No products found',
            'confirmProduct':'product',
            'confirmProducts':'products',
            'areYouSureYouWantToProcess':'Are you sure you want to process',
            'productProcessedSoFar':'product processed so far',
            'productsProcessedSoFar':'products processed so far',
            'completed':'Completed',
            'productHasBeenProcessed':'product has been processed.',
            'productsHaveBeenProcessed':'products have been processed.',
            'priceMustBeNumeric':'Price must be a numeric value.',
            'priceEmpty':'Your changing price is empty',
            'productsDeletedSoFar':'products deleted so far',
            'productDeletedSoFar':'product deleted so far',
            'productHasBeenDeletedLabel':'product has been deleted.',
            'productsHaveBeenDeleted':'products have been deleted.',
            'areYouSureYouWantToDelete':'Are you sure you want to delete',
            'inventoryHasBeenChanged':'Quantity has been changed',
            'canNotAssignPromo':'Can not assign promo',

        }
    },
    es: {
        message: {
            'searchByNameSkuMpn':'search by name, SKU, MPN',
            'selectBrand':'Filter by brand..',
            'noResultFoundSearch':'No result',
            'selectTag':'Filter by tag..',
            'selectInventory':'Filter by stock..',
            'withSelectedDo':'With selected do',
            'noMassActions': 'nothing',
            'first':'first',
            'last':'last',
            'previous':'previous',
            'next':'next',
            'total':'total',
            'records':'records',
            'found':'found',
            'rowsPerPage':'Rows per page',
            'unlimited':'unlimited',
            'no':'no',
            'yes':'yes',
            'name':'Name',
            'stock':'Stock',
            'brand':'Brand',
            'suppliers':'Suppliers',
            'sku':'Sku',
            'mpn':'Mpn',
            'freeShipping':'Free shipping',
            'weight':'Weight',
            'price':'Price',
            'salesCount':'Sales count',
            'cs_new':'Abandoned carts',
            'cs_completed':'Payment Received',
            'cs_shipped':'Items Shipped',
            'cs_refunded':'Refunded purchase',
            'cs_pending':'Merchant action required -  Customer charged',
            'cs_processing':'Technical processing  - Customer not charged',
            'cs_delivered':'Items delivered',
            'cs_canceled':'canceled',
            'cs_error':'error',
            'cs_partial':'Partial Order',
            'cs_not_verified':'Quote Signed (Signature only quote)',
            'totalSales':'Total',
            'updated':'Updated',
            'massActionAssignBrand':'Assign Brand',
            'selectProductBrand':'select brand',
            'orCreateNew':'or create new',
            'apply':'Apply',
            'massActionChangeProductBrand':'Assign brand',
            'pleaseChooseProductBrandOrAddNew':'Please choose product brand or add new one',
            'smsNoMassActionRecordsFound':'No products have been found with this product brand',
            'pleaseChooseAtLeastOneProduct':'Please choose at least one product',
            'notValidBrand':'Brand name should contain the following characters only: a-z, A-Z, 0-9, -(dash), _(underscore) and space.',
            'done':'Done',
            'canNotAssignBrand':'Can not assign brand',
            'productTabTitle':'Manage your product catalog',
            'massActionChangeProductTemplate':'Assign page template',
            'selectProductTemplate':'select template',
            'massActionAssignTemplate':'Assign page template',
            'pleaseChooseProductTemplate':'Please choose product template',
            'canNotAssignTemplate':'Can not assign template',
            'templateHasBeenChanged':'Template has been changed',
            'massActionChangeProductTax':'Assign tax',
            'massActionAssignTax':'Assign tax',
            'Non taxable':'Non taxable',
            'Default':'Default',
            'Alternative':'Alternative',
            'Alternative 2':'Alternative 2',
            'selectTaxCategory':'Select tax category',
            'taxHasBeenChanged':'Tax has been changed',
            'canNotAssignTax':'Can not assign tax',
            'massActionChangeProductShipping':'Assign free shipping',
            'selectProductShipping':'Select',
            'No free shipping':'No free shipping',
            'Free shipping':'Free shipping',
            'massActionAssignShipping':'Assign free shipping',
            'pleaseChooseProductShipping':'Please choose product shipping',
            'shippingHasBeenChanged':'Shipping has been changed',
            'canNotAssignShipping':'Can not assign shipping',
            'massActionChangeProductTag':'Assign/Remove tag',
            'brandHasBeenChanged':'Brand has been changed',
            'massActionAssignTag':'Manage tags',
            'massActionChangeProductCompany':'Assign suppliers',
            'massActionAssignCompany':'Assign suppliers',
            'massActionDeleteProduct':'Delete (nonreversible)',
            'massActionDelProduct':'Delete products',
            'areYouSure':'Are you sure?',
            'thisOperationCannotBeUndone':'This operation cannot be undone!',
            'productHasBeenDeleted':'Deleted',
            'canNotDeleteProduct':'Can not delete product(s)',
            'massActionToggleProduct':'Enable/Disable',
            'massActionEnableDisableProducts':'Enable/Disable products',
            'enable':'Enable',
            'disable':'Disable',
            'canNotToggleProduct':'Can not toggle product(s)',
            'productHasBeenChanged':'Done',
            'productHasBeenEnabled':'Enabled',
            'productHasBeenDisabled':'Disabled',
            'massActionProductQuantity':'Assign quantity',
            'infinite':'infinite',
            'or':'OR',
            'specifyInventoryStockLevel':'specify inventory stock level',
            'pleaseEnterValidNumber':'Please enter valid number',
            'canNotChangeProductInventory':'Can not change product inventory',
            'massActionProductNegativeStock':'Assign negative stock',
            'select':'select',
            'disable negative stock':'disable negative stock',
            'enable negative stock':'enable negative stock',
            'pleaseChooseOption':'Please select option',
            'negativeStockHasBeenChanged':'Negative stock has been changed',
            'canNotAssignNegativeStock':'Can not assign negative stock',
            'massActionAssignPromo':'Assign promo',
            'setSelectedProductsOnSale':'Set selected products on sale',
            'salePrice':'Sale price',
            'time':'Time',
            'salesTimeInfo':'Sales time depends on your local server time settings',
            'startingDate':'Starting date',
            'expiryDate':'Expiry date',
            'wrongDateFormat':'Wrong date format',
            'enterCorrectPrice':'Enter correct promo price',
            'promoHasBeenAdded':'Promo has been added',
            'massActionAssignProductOptionPrice':'Assign product/option price',
            'products':'Products',
            'options':'Options',
            'priceSignModifier':'Adjustment type',
            'priceTypeModifier':'Adjustment unit',
            'priceWillChangeTo':'Change price to',
            'minusOptionProcess':'Exclude negative-priced options',
            'attention':'Note: Products with a price of 0 will not be updated.',
            'dialogTitleTotal':'Total',
            'titleRecord':'Record',
            'titleRecords':'Records',
            'massActionAssignPrice':'Apply Price Update',
            'dialogAllProductsMatchingFilter':'Apply to all filtered products',
            'noProductsFound':'No products found',
            'confirmProduct':'product',
            'confirmProducts':'products',
            'areYouSureYouWantToProcess':'Are you sure you want to process',
            'productProcessedSoFar':'product processed so far',
            'productsProcessedSoFar':'products processed so far',
            'completed':'Completed',
            'productHasBeenProcessed':'product has been processed.',
            'productsHaveBeenProcessed':'products have been processed.',
            'priceMustBeNumeric':'Price must be a numeric value.',
            'priceEmpty':'Your changing price is empty',
            'productsDeletedSoFar':'products deleted so far',
            'productDeletedSoFar':'product deleted so far',
            'productHasBeenDeletedLabel':'product has been deleted.',
            'productsHaveBeenDeleted':'products have been deleted.',
            'areYouSureYouWantToDelete':'Are you sure you want to delete',
            'inventoryHasBeenChanged':'Quantity has been changed',
            'canNotAssignPromo':'Can not assign promo',

        }
    },
    fr: {
        message: {
            'searchByNameSkuMpn':'search by name, SKU, MPN',
            'selectBrand':'Filter by brand..',
            'noResultFoundSearch':'No result',
            'selectTag':'Filter by tag..',
            'selectInventory':'Filter by stock..',
            'withSelectedDo':'With selected do',
            'noMassActions': 'nothing',
            'first':'first',
            'last':'last',
            'previous':'previous',
            'next':'next',
            'total':'total',
            'records':'records',
            'found':'found',
            'rowsPerPage':'Rows per page',
            'unlimited':'unlimited',
            'no':'no',
            'yes':'yes',
            'name':'Name',
            'stock':'Stock',
            'brand':'Brand',
            'suppliers':'Suppliers',
            'sku':'Sku',
            'mpn':'Mpn',
            'freeShipping':'Free shipping',
            'weight':'Weight',
            'price':'Price',
            'salesCount':'Sales count',
            'cs_new':'Abandoned carts',
            'cs_completed':'Payment Received',
            'cs_shipped':'Items Shipped',
            'cs_refunded':'Refunded purchase',
            'cs_pending':'Merchant action required -  Customer charged',
            'cs_processing':'Technical processing  - Customer not charged',
            'cs_delivered':'Items delivered',
            'cs_canceled':'canceled',
            'cs_error':'error',
            'cs_partial':'Partial Order',
            'cs_not_verified':'Quote Signed (Signature only quote)',
            'totalSales':'Total',
            'updated':'Updated',
            'massActionAssignBrand':'Assign Brand',
            'selectProductBrand':'select brand',
            'orCreateNew':'or create new',
            'apply':'Apply',
            'massActionChangeProductBrand':'Assign brand',
            'pleaseChooseProductBrandOrAddNew':'Please choose product brand or add new one',
            'smsNoMassActionRecordsFound':'No products have been found with this product brand',
            'pleaseChooseAtLeastOneProduct':'Please choose at least one product',
            'notValidBrand':'Brand name should contain the following characters only: a-z, A-Z, 0-9, -(dash), _(underscore) and space.',
            'done':'Done',
            'canNotAssignBrand':'Can not assign brand',
            'productTabTitle':'Manage your product catalog',
            'massActionChangeProductTemplate':'Assign page template',
            'selectProductTemplate':'select template',
            'massActionAssignTemplate':'Assign page template',
            'pleaseChooseProductTemplate':'Please choose product template',
            'canNotAssignTemplate':'Can not assign template',
            'templateHasBeenChanged':'Template has been changed',
            'massActionChangeProductTax':'Assign tax',
            'massActionAssignTax':'Assign tax',
            'Non taxable':'Non taxable',
            'Default':'Default',
            'Alternative':'Alternative',
            'Alternative 2':'Alternative 2',
            'selectTaxCategory':'Select tax category',
            'taxHasBeenChanged':'Tax has been changed',
            'canNotAssignTax':'Can not assign tax',
            'massActionChangeProductShipping':'Assign free shipping',
            'selectProductShipping':'Select',
            'No free shipping':'No free shipping',
            'Free shipping':'Free shipping',
            'massActionAssignShipping':'Assign free shipping',
            'pleaseChooseProductShipping':'Please choose product shipping',
            'shippingHasBeenChanged':'Shipping has been changed',
            'canNotAssignShipping':'Can not assign shipping',
            'massActionChangeProductTag':'Assign/Remove tag',
            'brandHasBeenChanged':'Brand has been changed',
            'massActionAssignTag':'Manage tags',
            'massActionChangeProductCompany':'Assign suppliers',
            'massActionAssignCompany':'Assign suppliers',
            'massActionDeleteProduct':'Delete (nonreversible)',
            'massActionDelProduct':'Delete products',
            'areYouSure':'Are you sure?',
            'thisOperationCannotBeUndone':'This operation cannot be undone!',
            'productHasBeenDeleted':'Deleted',
            'canNotDeleteProduct':'Can not delete product(s)',
            'massActionToggleProduct':'Enable/Disable',
            'massActionEnableDisableProducts':'Enable/Disable products',
            'enable':'Enable',
            'disable':'Disable',
            'canNotToggleProduct':'Can not toggle product(s)',
            'productHasBeenChanged':'Done',
            'productHasBeenEnabled':'Enabled',
            'productHasBeenDisabled':'Disabled',
            'massActionProductQuantity':'Assign quantity',
            'infinite':'infinite',
            'or':'OR',
            'specifyInventoryStockLevel':'specify inventory stock level',
            'pleaseEnterValidNumber':'Please enter valid number',
            'canNotChangeProductInventory':'Can not change product inventory',
            'massActionProductNegativeStock':'Assign negative stock',
            'select':'select',
            'disable negative stock':'disable negative stock',
            'enable negative stock':'enable negative stock',
            'pleaseChooseOption':'Please select option',
            'negativeStockHasBeenChanged':'Negative stock has been changed',
            'canNotAssignNegativeStock':'Can not assign negative stock',
            'massActionAssignPromo':'Assign promo',
            'setSelectedProductsOnSale':'Set selected products on sale',
            'salePrice':'Sale price',
            'time':'Time',
            'salesTimeInfo':'Sales time depends on your local server time settings',
            'startingDate':'Starting date',
            'expiryDate':'Expiry date',
            'wrongDateFormat':'Wrong date format',
            'enterCorrectPrice':'Enter correct promo price',
            'promoHasBeenAdded':'Promo has been added',
            'massActionAssignProductOptionPrice':'Assign product/option price',
            'products':'Products',
            'options':'Options',
            'priceSignModifier':'Adjustment type',
            'priceTypeModifier':'Adjustment unit',
            'priceWillChangeTo':'Change price to',
            'minusOptionProcess':'Exclude negative-priced options',
            'attention':'Note: Products with a price of 0 will not be updated.',
            'dialogTitleTotal':'Total',
            'titleRecord':'Record',
            'titleRecords':'Records',
            'massActionAssignPrice':'Apply Price Update',
            'dialogAllProductsMatchingFilter':'Apply to all filtered products',
            'noProductsFound':'No products found',
            'confirmProduct':'product',
            'confirmProducts':'products',
            'areYouSureYouWantToProcess':'Are you sure you want to process',
            'productProcessedSoFar':'product processed so far',
            'productsProcessedSoFar':'products processed so far',
            'completed':'Completed',
            'productHasBeenProcessed':'product has been processed.',
            'productsHaveBeenProcessed':'products have been processed.',
            'priceMustBeNumeric':'Price must be a numeric value.',
            'priceEmpty':'Your changing price is empty',
            'productsDeletedSoFar':'products deleted so far',
            'productDeletedSoFar':'product deleted so far',
            'productHasBeenDeletedLabel':'product has been deleted.',
            'productsHaveBeenDeleted':'products have been deleted.',
            'areYouSureYouWantToDelete':'Are you sure you want to delete',
            'inventoryHasBeenChanged':'Quantity has been changed',
            'canNotAssignPromo':'Can not assign promo',


        }
    }

};

export default messages;
