<input type="hidden" name="group-currency" class="group-currency" value="<?php echo Models_Mapper_ShoppingConfig::getInstance()->getConfigParam( 'currency' ); ?>" xmlns="http://www.w3.org/1999/html"/>
<div id="edit-group">
    <fieldset class="background mb10px grid_12 alpha omega">
        <legend class="background p5px"><?php echo $this->translate('Default user group'); ?></legend>
        <?php $groupList = array($this->translate('Select group'));
            $groups = Store_Mapper_GroupMapper::getInstance()->fetchPairsAll();
            if(!empty($groups)) {
                foreach ($groups as $key => $group) {
                    $groupList[$key] = $group;
                }
            }
        ?>
        <?php echo $this->formSelect('groups-list', $this->defaultGroupId, array('id' => 'groups-list','class' => 'grid_4 alpha'), $groupList);?>
    </fieldset>
    <form id="edit-group-form" class="grid_12 alpha omega background">
        <div class="grid_3 alpha">
            <?php echo $this->formText( 'groupName', null, array(
                'class' => 'new-group-name', 'placeholder' => $this->translate( 'Enter group name' )
            ) ); ?>
        </div>
        <div class="grid_1 alpha omega mt0px">
            <?php echo $this->formSelect( 'priceSign', null, array(
                'id' => 'group-sign',
            ), array(
                'plus' => '+', 'minus' => '-'
            ) ); ?>

        </div>
        <div class="grid_3 mt0px">
            <?php echo $this->formText( 'priceValue', null, array(
                'class' => 'new-group-price-value'
            ) ); ?>
        </div>
        <div class="grid_1 alpha omega mt0px">
            <?php echo $this->formSelect( 'priceType', null, array(
                'id' => 'group-price-type',
            ), array(
                'percent' => '%', 'unit' => Models_Mapper_ShoppingConfig::getInstance()->getConfigParam( 'currency' )
            ) ); ?>

        </div>

        <button class="btn grid_4 omega mt0px ticon-plus" type="submit"><?php echo $this->translate( 'Create or update group' ); ?></button>
        <input type="hidden" name="<?php echo Tools_System_Tools::CSRF_SECURE_TOKEN;?>" value="<?php echo Tools_System_Tools::initSecureToken(Api_Store_Groups::GROUPS_SECURE_TOKEN);?>">

    </form>
</div>

<div class="grid_12 alpha omega mt15px">
    <table id="group-table" class="table-striped table-hover small mb10px">
        <thead class="header-inner">
            <tr>
                <th><?php echo $this->translate( 'Group Name' ); ?></th>
                <th><?php echo $this->translate( 'Default price modifier' ); ?></th>
                <th class="w10 text-center"><?php echo $this->translate( 'Action' ); ?></th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>