<ul class="pagination-breadcrumb">
    <?php
    $breadCrumb = '';
    $startName = $this->translate('Start');
    $shippingAddrName = $this->translate('Shipping address');
    $shippingCarrierName = $this->translate('Shipping carrier');
    $merchandisingName = $this->translate('Merchandising');
    $paymentName = $this->translate('Payment');
    if (!empty($this->steplabels)) {
        $startName = isset($this->steplabels[0]) ? $this->steplabels[0] : $startName;
        $shippingAddrName = isset($this->steplabels[1]) ? $this->steplabels[1] : $shippingAddrName;
        $shippingCarrierName = isset($this->steplabels[2]) ? $this->steplabels[2] : $shippingCarrierName;
        $merchandisingName = isset($this->steplabels[3]) ? $this->steplabels[3] : $merchandisingName;
        $paymentName = isset($this->steplabels[4]) ? $this->steplabels[4] : $paymentName;
    }
    $start = '<li><a href="' . $this->websiteUrl . $this->checkoutPage->getUrl() . '">' . $startName . '</a></li>';
    $startPlus = '<li><span>' . $shippingAddrName . '</span></li>';
    $address = '<li><a href="' . $this->websiteUrl . $this->checkoutPage->getUrl() . '?step=' . Cart::STEP_SHIPPING_OPTIONS . '">' . $shippingAddrName . '</a></li>';
    $addressPlus = '<li><span>' . $shippingCarrierName . '</span></li>';
    $shipping = '<li><a href="' . $this->websiteUrl . $this->checkoutPage->getUrl() . '?step=' . Cart::STEP_SHIPPING_METHOD . '&stepBack=address">' . $shippingCarrierName . '</a></li>';
    $shippingPlus = '<li><span>' . $paymentName . '</span></li>';
    $merchandising = '<li><a href="' . $this->websiteUrl . $this->checkoutPage->getUrl() . '?step=' . Cart::STEP_MERCHANDISING . '&stepBackMerchandising=merchandisingBack">' . $merchandisingName . '</a></li>';
    $merchandisingCurrent = '<li><span>' . $merchandisingName . '</span></li>';
    $merchandisingPlus = '<li><span>' . $paymentName . '</span></li>';

    $pathAAp = $address . $addressPlus;
    $pathASSp = $address . $shipping . $shippingPlus;
    $pathASMc = $address . $shipping . $merchandisingCurrent;
    $pathASMMp = $address . $shipping . $merchandising. $merchandisingPlus;
    $pathAMMp = $address . $merchandising . $merchandisingPlus;
    $pathAMc = $address . $merchandisingCurrent;
    $pathAMp = $address . $merchandisingPlus;
    $pathASMp = $address . $shipping . $merchandisingPlus;
    $pathAMMp = $address . $merchandising. $merchandisingPlus;
    ?>
    <?php
    if ($this->currentUser === Tools_Security_Acl::ROLE_GUEST){
        $breadCrumb = '<li><span class="current">' . $startName . '</span></li>';
        if ($this->step === 'signup' || $this->step === 'shipping'){
            $breadCrumb = $start . $startPlus;
        }
        if($this->step === 'address'){
            $breadCrumb = $start . $pathAAp;
        }
        if($this->step === 'method'){
            $breadCrumb = $start . $pathASSp;
            if($this->merchandising){
                $breadCrumb = $start . $pathASMc;
            }
        }
        if($this->step === 'merchandising'){
            $breadCrumb = $start . $pathASMMp;
            if($this->merchandisingBack){
                $breadCrumb = $start . $pathASMc;
            }
            if($this->freeShipping && $this->merchandising){
                $breadCrumb = $start . $pathAMMp;
                if($this->merchandisingBack){
                    $breadCrumb = $start . $pathAMc;
                }
            }
        }
        if($this->step === 'address' && $this->freeShipping){
            $breadCrumb = $start . $pathAMc;
            if(empty($this->merchandising)){
                $breadCrumb = $start . $pathAMp;
            }
        }
    }else{
        if (empty($this->step) || $this->step === 'shipping'){
            $breadCrumb = $startPlus;
        }
        if ($this->step === 'address'){
            $breadCrumb = $pathAAp;
            if($this->freeShipping){
                $breadCrumb = $pathAMp;
            }
            if($this->freeShipping && $this->merchandising){
                $breadCrumb = $pathAMc;
            }
        }
        if ($this->step === 'method'){
            $breadCrumb = $pathASMc;
            if(empty($this->merchandising)){
                $breadCrumb = $pathASMp;
            }
        }
        if ($this->step === 'merchandising'){
            $breadCrumb = $pathASMMp;
            if($this->merchandisingBack){
                $breadCrumb = $pathASMc;
            }
            if ($this->freeShipping && $this->merchandising){
                $breadCrumb = $pathAMMp;
                if($this->merchandisingBack){
                    $breadCrumb = $pathAMc;
                }
            }
        }
    }
?>
  <?php echo $breadCrumb; ?>
</ul>