<?php $id = uniqid('store-coupon-'); ?>
<div>
    <h3 class="checkout-widget-title">
	    <?php echo $this->translate('Enter coupon');?>
	    <?php if (count(Tools_ShoppingCart::getInstance()->getCoupons()) > 0): ?>
        <a href="<?php echo $this->url();?>?step=shipping" class="checkout-edit" title="<?php echo $this->translate('Edit coupons');?>">[&nbsp;<?php echo $this->translate('edit');?>&nbsp;]</a>
	    <?php endif; ?>
    </h3>
    <form id="<?php echo $id; ?>" class="store-coupon" action="<?php echo trim($this->websiteUrl, '/').$_SERVER['REQUEST_URI']; ?>" method="post">
	    <input type="text" name="code">
	    <input type="submit" value="<?php echo $this->translate('Apply'); ?>">
	</form>
	<?php if (isset($this->errors)): ?>
	<ul class="errors">
		<?php foreach($this->errors as $err): ?>
			<li><?php echo $this->translate($err); ?></li>
		<?php endforeach; ?>
	</ul>
	<?php endif; ?>
</div>
<script>
$(function(){
	$('#<?php echo $id; ?>').on('submit', function(e){
        e.preventDefault();

        var self = this;

		$.ajax({
			url: $('#website_url').val()+'plugin/shopping/run/coupon/',
			data: $(this).serialize(),
			type: 'POST',
			dataType: 'json',
			success: function(response){
				console.log(response);
				var notify = $("<p></p>", {"class": "store-coupon-notify"}).html(response.responseText.join('<br>'))
						.on('click', function(){ $(this).remove(); });
				$(self).trigger('reset').after(notify);
                refreshCartSummary();
			}
		})
	});
});
</script>