<?php
$this->headScript()->setAllowArbitraryAttributes(true)
		->appendFile($this->websiteUrl . 'system/js/external/chosen/chosen.jquery.min.js')
		->appendFile($this->websiteUrl.'plugins/shopping/web/js/libs/jquery/addresschain.jquery.js')
        ->appendFile($this->websiteUrl . 'plugins/shopping/web/js/libs/require.min.js',
            null,
            array('data-main' => $this->websiteUrl . 'plugins/shopping/web/js/modules/store-orders/main.js')
        );
$this->headLink()
	->appendStylesheet($this->websiteUrl . 'system/js/external/chosen/chosen.css')
	->appendStylesheet($this->websiteUrl . 'system/css/reset-widgets.css');
?>
<style>
	#store-orders select.filter, .chzn-container-single .chzn-search input{
		width: 100% !important;
        float: none;
    }
    .filters .chzn-container .chzn-results {
        max-height: 170px;
    }
	table#orders-table tbody td {
		min-height: 24px;
	}
</style>
<input type="hidden" name="system-language" value="<?php echo Tools_Misc::getJsTranslationLanguage();?>"/>
<div id="store-orders" class="toaster-widget clearfix">
	<div>
        <form class="filters mb30px clearfix">
            <div class="grid_12 alpha omega">
                <label class="h2"><?php echo $this->translate('Search');?></label>
                <div class="grid_9 alpha omega search-orders-block">
                    <div class="grid_4 alpha t-grid_2 t-alpha search-block-element">
                        <input type="text" class="filter search-input" name="search" placeholder="<?php echo $this->translate('by order ID') ?>" >
                    </div>
                    <div class="grid_4 t-grid_2 search-block-element">
                        <input type="text" class="filter search-input" name="filter-product-key" placeholder="<?php echo $this->translate('by product name, sku, mpn');?>">
                    </div>
                    <div class="grid_4 omega t-grid_2 t-omega search-block-element">
                        <input type="text" class="filter search-input" name="user-name" placeholder="<?php echo $this->translate('by name');?>">
                    </div>
                </div>
                <div id="extra-filters-switch" class="fl-right"><a class="btn icon-arrow-down2" href="javascript:;">[ <?php echo $this->translate('show/hide advanced filters');?> ]</a></div>
            </div>
            <fieldset id="extra-filters" class="flex-row grid_12 mt20px block-wrap hidden alpha omega">
                <fieldset id="filter-settings-preset-block" class="flex_12 f-alpha f-omega">
                    <legend><?php echo $this->translate('Filter settings'); ?></legend>
                    <div class="grid_5 alpha">
                        <?php $presetApplied = false;?>
                        <select id="predefined-filter-list" name="predefinedFilterList" class="grid_4 alpha t-grid_2" data-placeholder="<?php echo $this->translate('show all'); ?>">
                            <option value="0"><?php echo $this->translate('Select filter preset'); ?></option>
                            <?php if (!empty($this->filtersPreset)) : ?>
                                <?php foreach ($this->filtersPreset as $filterPreset): ?>
                                    <option value="<?php echo $filterPreset->getId(); ?>"<?php echo (!empty($this->presetDefaultId) && $this->presetDefaultId == $filterPreset->getId()) ? 'selected' : ''; ?>><?php echo $filterPreset->getFilterPresetName(); ?></option>
                                    <?php if(!empty($this->presetDefaultId) && $this->presetDefaultId == $filterPreset->getId()):?>
                                        <?php $presetApplied = true;?>
                                    <?php endif;?>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </select>

                        <div class="grid_3 text-center switch-search-filter space-vert t-grid_2">
                            <?php if($presetApplied === true):?>
                                <span id="switch-search-filter-label"><?php echo $this->translate('Modify preset name'); ?></span>
                            <?php else: ?>
                                <span id="switch-search-filter-label"><?php echo $this->translate('OR'); ?></span>
                            <?php endif;?>
                        </div>
                        <input class="grid_4 omega t-grid_2" type="text" id="filter-preset-name" autocomplete="off"
                               name="filters-preset-name"
                               value="<?php echo (!empty($this->presetDefaultName)) ? $this->presetDefaultName : ''; ?>"
                               placeholder="<?php echo $this->translate('Set new filter preset'); ?>"/>
                    </div>
                    <div class="grid_4 space-vert">
                        <div class="inline-block t-grid_3">
                            <label><input type="checkbox" id="filter-preset-default"
                                          name="filterPresetDefault" <?php echo (!empty($this->presetDefault)) ? 'checked="checked"' : ''; ?>/><?php echo $this->translate('Mark as default'); ?>
                            </label>

                        </div>
                        <input type="hidden" name="presetId" id="preset-id"
                               value="<?php echo (!empty($this->presetDefaultId)) ? $this->presetDefaultId : ''; ?>"/>
                        <?php if (Tools_Security_Acl::ROLE_SUPERADMIN === $this->userRole || Tools_Security_Acl::ROLE_ADMIN === $this->userRole): ?>
                            <div class="inline-block prefix_1 t-grid_3">
                                <label><input type="checkbox" id="filter-preset-allow"
                                              name="filterPresetAllow" <?php echo (!empty($this->presetDefaultAccess) && $this->presetDefaultAccess === 'all') ? 'checked="checked"' : ''; ?>/><?php echo $this->translate('Show to all users'); ?>
                                </label>
                            </div>
                        <?php endif; ?>
                    </div>
                    <span class="btn red prefix_1 grid_1 omega" name="deleteFilterPreset"
                            id="delete-filter-preset" style="display: none;"><?php echo $this->translate('Delete'); ?></span>
                    <span class="btn green grid_1 omega fl-right" name="saveFilterPreset"
                            id="save-filter-preset"><?php echo $this->translate('Save filter'); ?></span>
                </fieldset>
                <p class="flex_3 f-alpha t-grid_3">
                    <label class="text-bold"><?php echo $this->translate('By order amount');?></label>
                    <input id="filter-from-amount" class="grid_6 alpha t-grid_3 t-alpha m-grid_2 m-alpha" type="text" name="filter-from-amount" placeholder="<?php echo $this->translate('from');?>" value="<?php echo (!empty($this->presetConfig['filter_from_amount'])) ? $this->presetConfig['filter_from_amount'] : ''; ?>">
                    <input id="filter-to-amount" class="grid_6 omega t-grid_3 t-omega m-grid_2 m-omega" type="text" name="filter-to-amount" placeholder="<?php echo $this->translate('to');?>" value="<?php echo (!empty($this->presetConfig['filter_to_amount'])) ? $this->presetConfig['filter_to_amount'] : ''; ?>">
                </p>
                <p class="flex_3 f-alpha t-grid_3">
                    <label class="text-bold"><?php echo $this->translate('By coupon');?></label>
                    <input type="text" class="filter" id="filter-by-coupon-code" name="filter-by-coupon-code" placeholder="<?php echo $this->translate('by coupon code');?>" value="<?php echo (!empty($this->presetConfig['filter_by_coupon_code'])) ? $this->presetConfig['filter_by_coupon_code'] : ''; ?>">
                </p>
                <p class="flex_3 f-alpha t-grid_3">
                    <label class="text-bold"><?php echo $this->translate('By date');?></label>
                    <input class="grid_6 alpha t-grid_3 t-alpha m-grid_2 m-alpha" type="text" autocomplete="off" id="orders-filter-fromdate" name="filter-from-date" placeholder="<?php echo $this->translate('from');?>" value="<?php echo(!empty($this->presetConfig['orders_filter_fromdate']) ? date('d-M-y', strtotime($this->presetConfig['orders_filter_fromdate'])) : ''); ?>">
                    <input class="grid_6 omega t-grid_3 t-omega m-grid_2 m-omega" type="text" autocomplete="off" id="orders-filter-todate" name="filter-to-date" placeholder="<?php echo $this->translate('to');?>" value="<?php echo(!empty($this->presetConfig['orders_filter_todate']) ? date('d-M-y', strtotime($this->presetConfig['orders_filter_todate'])) : ''); ?>">
                </p>
                <p class="flex_3 f-alpha f-omega t-grid_3">
                    <label class="text-bold"><?php echo $this->translate('By order status');?></label>
                    <select class="filter" multiple id="filter-status" name="filter-status" data-placeholder="<?php echo $this->translate('show all');?>">
                        <?php if (!empty($this->orderStatuses)) : ?>
                            <?php foreach ($this->orderStatuses as $statusType => $statusName): ?>
                                <option value="<?php echo $statusType; ?>" <?php echo (!empty($this->presetConfig['filter_status']) && in_array($statusType, $this->presetConfig['filter_status'])) ? 'selected="selected"' : ''; ?>><?php echo $this->translate($statusName);?></option>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </select>
                </p>
                <p class="flex_3 f-alpha t-grid_3">
                    <label class="text-bold"><?php echo $this->translate('By Client Group');?></label>
                    <select class="filter" multiple id="filter-client-group" name="filter-client-group" data-placeholder="<?php echo $this->translate('show all');?>">
                        <?php if (!empty($this->customerGroups)) : ?>
                            <?php foreach ($this->customerGroups as $groupId => $groupName): ?>
                                <option value="<?php echo $groupId; ?>" <?php echo (!empty($this->presetConfig['filter_client_group']) && in_array($groupId, $this->presetConfig['filter_client_group'])) ? 'selected="selected"' : ''; ?>><?php echo $this->translate($groupName);?></option>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </select>
                </p>
                <p class="flex_2 f-alpha <?php echo (!empty($this->presetConfig['filter_order_type']) && $this->presetConfig['filter_order_type'] == 'recurring_id') ? '' : 'hidden' ;?> recurring-filters t-grid_3">
                    <label class="text-bold"><?php echo $this->translate('By order recurring status type');?></label>
                    <?php echo $this->formSelect('filter-recurring-order-type', (!empty($this->presetConfig['filter_recurring_order_type'])) ? $this->presetConfig['filter_recurring_order_type'] : null, array(
                        'class' => 'filter',
                        'data-placeholder' => $this->translate('show all')
                    ), array(
                        '',
                        'new' => $this->translate('New'),
                        'active' => $this->translate('Active'),
                        'pending' => $this->translate('Pending'),
                        'expired' => $this->translate('Expired'),
                        'suspended' => $this->translate('Suspended'),
                        'canceled' => $this->translate('Canceled')
                    )); ?>
                </p>
                <p class="flex_2 f-alpha f-omega t-grid_3">
                    <label class="text-bold"><?php echo $this->translate('By order type');?></label>
                    <?php $orderTypes = array(
                        '',
                        'cart_imported_id' => $this->translate('Imported'),
                        'recurring_id' => $this->translate('Recurring'),
                        'real_order_id' => $this->translate('Regular')
                    );?>
                    <?php if(!empty($this->orderSubtypes)):?>
                        <?php foreach ($this->orderSubtypes as $orderSubtype):?>
                            <?php $orderTypes[$orderSubtype] = $this->translate(ucfirst($orderSubtype));?>
                        <?php endforeach;?>
                    <?php endif;?>
                    <?php echo $this->formSelect('filter-order-type', (!empty($this->presetConfig['filter_order_type'])) ? $this->presetConfig['filter_order_type'] : null, array(
                        'class' => 'filter',
                        'data-placeholder' => $this->translate('show all')
                    ), $orderTypes); ?>
                </p>
                <?php if(!empty($this->isPluginWithTagPosExist)):?>
                    <p class="flex_3 f-omega t-grid_3">
                        <label class="text-bold"><?php echo $this->translate('By cashier id');?></label>
                        <select class="filter" multiple id="filter-by-cashier-id" name="filter-by-cashier-id" data-placeholder="<?php echo $this->translate('show all');?>">
                            <?php if (!empty($this->cashierIds)) : ?>
                                <?php foreach ($this->cashierIds as $cashier => $cashierName): ?>
                                    <option value="<?php echo $cashier; ?>" <?php echo (!empty($this->presetConfig['filter_by_cashier_id']) && in_array($cashier, $this->presetConfig['filter_by_cashier_id'])) ? 'selected="selected"' : ''; ?>><?php echo $this->translate($cashierName);?></option>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </select>
                    </p>
                <?php endif;?>
                <div class="flex_8 f-omega f-alpha">
                    <label class="text-bold"><?php echo $this->translate('By shipping destination');?></label>
                    <?php
                    $countryList = Tools_Geo::getCountries(true);
                    $countryList = array_merge(array('_' => ''), $countryList);
                    echo '<div class="grid_4 alpha t-grid_2 t-alpha">' . $this->formSelect('filter-country', (!empty($this->presetConfig['filter_country'])) ? $this->presetConfig['filter_country'] : null, array('class' => 'filter', 'data-placeholder' => $this->translate('shipping country')), $countryList ) . '</div>';

                    $stateList = array('' => '');
                    if(!empty($this->states) && !empty($this->presetConfig['filter_country']) && ($this->presetConfig['filter_country'] == 'US' || $this->presetConfig['filter_country'] == 'CA' || $this->presetConfig['filter_country'] == 'AU')){
                        $stateList = array('' => '') + $this->states;
                    }

                    echo '<div class="grid_4 t-grid_2">' . $this->formSelect('filter-state', (!empty($this->presetConfig['filter_state'])) ? $this->presetConfig['filter_state'] : null, array('class' => 'filter', 'data-placeholder' => $this->translate('shipping state')), $stateList) . '</div>';

                $shippingServices = array_merge(array(''), $this->shippingServices);
                echo '<div class="grid_4 omega t-grid_2 t-omega">' . $this->formSelect('filter-carrier', (!empty($this->presetConfig['filter_carrier'])) ? $this->presetConfig['filter_carrier'] : null, array('class' => 'filter', 'data-placeholder' => $this->translate('shipping carrier')), $shippingServices ) . '</div>';
                ?>

                <?php $countriesWithStates = array(); ?>
                <?php foreach ($this->countriesList as $countryAbbr => $countryFullName) : ?>
                    <?php if (!empty($countryStates = Tools_Geo::getState($countryAbbr, true))) {
                        $countriesWithStates[$countryAbbr] = $countryStates;
                    } ?>
                <?php endforeach;?>
                <input type="hidden" id="countries-with-states" value='<?php echo json_encode($countriesWithStates); ?>'/>
            </div>
            <div class="flex_2 mt20px">
                <label><input type="checkbox" id="exclude-quotes-from-search" name="exclude-quotes-from-search" <?php echo ((!empty($this->presetConfig['exclude_quotes_from_search']))) ? "checked" : ''; ?>> <?php echo $this->translate('Exclude quotes');?></label>
                <label><input type="checkbox" id="is-a-gift" name="is-a-gift" <?php echo ((!empty($this->presetConfig['is_a_gift']))) ? "checked" : ''; ?>> <?php echo $this->translate('Is a gift');?></label>
            </div>
            <div class="flex_12 f-alpha f-omega text-right">
                <button class="btn green ticon-checkmark" name="filter-apply" id="orders-filter-apply-btn"><?php echo $this->translate('Apply filter');?></button>
                <button class="btn red ticon-reload" name="filter-reset" id="orders-filter-reset-btn"><?php echo $this->translate('Reset all filters');?></button>
            </div>
        </div>
    </form>
    <div class="responsive-table">
        <table id="orders-table" class="widget table-hover">
            <thead>
                <tr class="title-table">
                    <th><input type="checkbox" name="checkAllOrders" id="orders-check-all" value="1" title="Check/Uncheck All"></th>
                    <th>#</th>
                    <th class="sortable" data-sortkey="name"><?php echo $this->translate('Customer name');?></th>
                    <th class="sortable" data-sortkey="email"><?php echo $this->translate('Email');?></th>
                    <th class="sortable sortDown" data-sortkey="aggregatedPurchasedOn"><?php echo $this->translate('Purchased on');?></th>
                    <th class="sortable" data-sortkey="status" style="min-width: 180px;"><?php echo $this->translate('Status');?></th>
                    <th class="sortable" data-sortkey="products"><?php echo $this->translate('Products in cart');?></th>
                    <th class="sortable" data-sortkey="total"><?php echo $this->translate('Total price');?></th>
                    <th class="sortable" data-sortkey="shipping_price"><?php echo $this->translate('Shipping price');?></th>
                    <th style="min-width: 110px;"><?php echo $this->translate('Shipping via');?></th>
                    <th class="text-center"><?php echo $this->translate('Details');?></th>
                    <?php if(isset($this->invoicePlugin)):?>
                        <th class="text-center"><?php echo $this->translate('Invoice & packing slip');?></th>
                    <?php endif;?>
                    <th data-sortkey="real_order_id"><?php echo $this->translate('Order type');?></th>
                </tr>
            </thead>
            <tbody id="orders-list">
            <?php if(isset($this->invoicePlugin)):?>
                <td colspan="13" style="text-align:center;">
            <?php else:?>
                 <td colspan="8" style="text-align:center;">
            <?php endif;?>
                    <img src="<?php echo $this->websiteUrl;?>system/images/spinner-small.gif" border="0" alt="loading..." />
                </td>
            </tbody>
            <tfoot>
            <td colspan="4" class="order-mass-action-block">
                <?php echo $this->translate('with selected do');?>
                <select name="order-mass-action" id="mass-action">
                    <option value="0"><?php echo $this->translate('nothing');?></option>
                    <option value="exportOrders"><?php echo $this->translate('Export orders');?></option>
                </select>
            </td>
            <?php if(isset($this->invoicePlugin)):?>
                    <td colspan="9" class="paginator text-right"></td>
                <?php else:?>
                    <td colspan="8" class="paginator text-right"></td>
                <?php endif;?>
            </tfoot>
        </table>
        <input type="hidden" id="orders-secure-token" name="orders-secure-token" class="orders-secure-token" value="<?php echo Tools_System_Tools::initSecureToken(Shopping::SHOPPING_SECURE_TOKEN);?>" />
        <?php if(isset($this->invoicePlugin)):?>
            <input type="hidden" value="enabled" name="invoiceEnable" id="invoiceEnable"/>
        <?php endif;?>
    </div>
</div>

<script type="text/javascript">
$(function(){
	$('select.filter', '#store-orders').chosen({
		allow_single_deselect: true
	});
	var filterFromDate = $('#orders-filter-fromdate', '#store-orders'),
		filterToDate = $('#orders-filter-todate', '#store-orders');
	filterFromDate.datepicker({
	    dateFormat: 'd-M-yy',
        defaultDate: "+1w",
	    changeMonth: true,
	    changeYear: true,
	    yearRange: "c-5:c+5",
	    onSelect: function(selectedDate){
		    filterToDate.datepicker("option", "minDate", selectedDate);
	    }
    });
    filterToDate.datepicker({
        dateFormat: 'd-M-yy',
        defaultDate: "+1w",
        changeMonth: true,
	    changeYear: true,
	    yearRange: "c-5:c+5",
        onSelect: function(selectedDate){
	        filterFromDate.datepicker("option", "maxDate", selectedDate);
        }
    });
	$('#filter-state').on('addressChain:updated', function(){
		$(this).prepend('<option value=""></option>').trigger('chosen:updated');
	});
	$('#extra-filters').addressChain({
		countrySelector: $('#filter-country'),
		stateSelector: $('#filter-state'),
		toogleStateVisibility: false,
		url: $('#website_url').val()+'api/store/geo/type/state?pairs'
	});

    var filterDefaultCouponCode = localStorage.getItem('couponCode');
    if (filterDefaultCouponCode) {
        $('#filter-by-coupon-code').val(filterDefaultCouponCode);
        localStorage.removeItem('couponCode');
    }

    var searchData = <?php echo json_encode(array_values($this->usedCoupons));?>;
    $('#filter-by-coupon-code').autocomplete({
        minLength: 2,
        source: searchData,
        messages: {
            noResults: '',
            results: function() {}
        }
    });
});
</script>
