<?php
$this->headScript()->setAllowArbitraryAttributes(true)
		->appendFile($this->websiteUrl . 'system/js/external/chosen/chosen.jquery.min.js')
		->appendFile($this->websiteUrl.'plugins/shopping/web/js/libs/jquery/addresschain.jquery.js')
        ->appendFile($this->websiteUrl . 'plugins/shopping/web/js/libs/require.min.js',
            null,
            array('data-main' => $this->websiteUrl . 'plugins/shopping/web/js/modules/store-orders/main.js')
        );
$this->headLink()
	->appendStylesheet($this->websiteUrl . 'system/js/external/chosen/chosen.css')
	->appendStylesheet($this->websiteUrl . 'system/css/reset-widgets.css');
?>
<style>
	#store-orders select.filter, .chzn-container-single .chzn-search input{
		width: 100% !important;
        float: none;
    }
    .filters .chzn-container .chzn-results {
        max-height: 170px;
    }
	table#orders-table tbody td {
		min-height: 24px;
	}
</style>
<input type="hidden" name="system-language" value="<?php echo Tools_Misc::getJsTranslationLanguage();?>"/>
<div id="store-orders" class="toaster-widget clearfix">
	<div>
        <form class="filters mb30px clearfix">
            <div class="grid_12 alpha omega">
                <label class="h2 mt20px"><?php echo $this->translate('Search');?></label>
                <input type="text" class="filter grid_3 alpha t-grid_2 t-alpha" name="search" placeholder="<?php echo $this->translate('by order ID') ?>" >
                <input type="text" class="filter grid_3 t-grid_2" name="filter-product-key" placeholder="<?php echo $this->translate('by product name, sku, mpn');?>">
                <input type="text" class="filter grid_3 omega t-grid_2 t-omega" name="user-name" placeholder="<?php echo $this->translate('by name');?>">
                <div id="extra-filters-switch" class="fl-right"><a class="btn icon-arrow-down2" href="javascript:;">[ <?php echo $this->translate('show/hide advanced filters');?> ]</a></div>
            </div>
            <div id="extra-filters" class="grid_12 mt20px block-wrap hide alpha omega">
                <p class="grid_3 alpha t-grid_3">
                    <label class="text-bold"><?php echo $this->translate('By order amount');?></label>
                    <input class="grid_6 alpha t-grid_3 t-alpha m-grid_2 m-alpha" type="text" name="filter-from-amount" placeholder="<?php echo $this->translate('from');?>">
                    <input class="grid_6 omega t-grid_3 t-omega m-grid_2 m-omega" type="text" name="filter-to-amount" placeholder="<?php echo $this->translate('to');?>">
                </p>
                <p class="grid_3 alpha t-grid_3">
                    <label class="text-bold"><?php echo $this->translate('By coupon');?></label>
                    <input type="text" class="filter" id="filter-by-coupon-code" name="filter-by-coupon-code" placeholder="<?php echo $this->translate('by coupon code');?>">
                </p>
                <p class="grid_3 alpha t-grid_3">
                    <label class="text-bold"><?php echo $this->translate('By date');?></label>
                    <input class="grid_6 alpha t-grid_3 t-alpha m-grid_2 m-alpha" type="text" id="orders-filter-fromdate" name="filter-from-date" placeholder="<?php echo $this->translate('from');?>">
                    <input class="grid_6 omega t-grid_3 t-omega m-grid_2 m-omega" type="text" id="orders-filter-todate" name="filter-to-date" placeholder="<?php echo $this->translate('to');?>">
                </p>
                <p class="grid_3 alpha omega t-grid_3">
                    <label class="text-bold"><?php echo $this->translate('By order status');?></label>
                    <?php $this->translate('cs_'.Models_Model_CartSession::CART_STATUS_NEW);?>
                    <select class="filter" multiple id="filter-status" name="filter-status" data-placeholder="<?php echo $this->translate('show all');?>">
                        <option value="<?php echo Models_Model_CartSession::CART_STATUS_NEW ?>"><?php echo $this->translate('cs_'.Models_Model_CartSession::CART_STATUS_NEW); ?></option>
                        <option selected value="<?php echo Models_Model_CartSession::CART_STATUS_PENDING; ?>"><?php echo $this->translate('cs_'.Models_Model_CartSession::CART_STATUS_PENDING); ?></option>
                        <option value="<?php echo Models_Model_CartSession::CART_STATUS_PROCESSING; ?>"><?php echo $this->translate('cs_'.Models_Model_CartSession::CART_STATUS_PROCESSING); ?></option>
                        <?php if(!empty($this->shoppingConfig['enabledPartialPayment'])) :?>
                            <option selected value="<?php echo Models_Model_CartSession::CART_STATUS_PARTIAL; ?>"><?php echo $this->translate('cs_'.Models_Model_CartSession::CART_STATUS_PARTIAL); ?></option>
                        <?php endif;?>
                        <option selected value="<?php echo Models_Model_CartSession::CART_STATUS_COMPLETED ; ?>"><?php echo $this->translate('cs_'.Models_Model_CartSession::CART_STATUS_COMPLETED); ?></option>
                        <option selected value="<?php echo Models_Model_CartSession::CART_STATUS_SHIPPED; ?>"><?php echo $this->translate('cs_'.Models_Model_CartSession::CART_STATUS_SHIPPED); ?></option>
                        <option selected value="<?php echo Models_Model_CartSession::CART_STATUS_DELIVERED; ?>"><?php echo $this->translate('cs_'.Models_Model_CartSession::CART_STATUS_DELIVERED); ?></option>
                        <option value="<?php echo Models_Model_CartSession::CART_STATUS_CANCELED; ?>"><?php echo $this->translate('cs_'.Models_Model_CartSession::CART_STATUS_CANCELED); ?></option>
                        <option value="<?php echo Models_Model_CartSession::CART_STATUS_REFUNDED; ?>"><?php echo $this->translate('cs_'.Models_Model_CartSession::CART_STATUS_REFUNDED); ?></option>
                        <option value="<?php echo Tools_Misc::CS_ALIAS_PENDING; ?>"><?php echo $this->translate('cs_'.Tools_Misc::CS_ALIAS_PENDING); ?></option>
                        <option value="<?php echo Tools_Misc::CS_ALIAS_PROCESSING; ?>"><?php echo $this->translate('cs_'.Tools_Misc::CS_ALIAS_PROCESSING); ?></option>
                        <option selected value="<?php echo Tools_Misc::CS_ALIAS_QUOTE_SIGNED; ?>"><?php echo $this->translate('cs_'.Tools_Misc::CS_ALIAS_QUOTE_SIGNED); ?></option>
                        <option value="<?php echo Tools_Misc::CS_ALIAS_LOST_OPPORTUNITY; ?>"><?php echo $this->translate('cs_'.Tools_Misc::CS_ALIAS_LOST_OPPORTUNITY); ?></option>
                    </select>
                </p>
                <p class="grid_2 alpha hidden recurring-filters t-grid_3">
                    <label class="text-bold"><?php echo $this->translate('By order recurring status type');?></label>
                    <?php echo $this->formSelect('filter-recurring-order-type', null, array(
                        'class' => 'filter',
                        'data-placeholder' => $this->translate('show all')
                    ), array(
                        '',
                        'new' => $this->translate('New'),
                        'active' => $this->translate('Active'),
                        'pending' => $this->translate('Pending'),
                        'expired' => $this->translate('Expired'),
                        'suspended' => $this->translate('Suspended'),
                        'canceled' => $this->translate('Canceled')
                    )); ?>
                </p>
                <p class="grid_2 alpha omega t-grid_3">
                    <label class="text-bold"><?php echo $this->translate('By order type');?></label>
                    <?php $orderTypes = array(
                        '',
                        'cart_imported_id' => $this->translate('Imported'),
                        'recurring_id' => $this->translate('Recurring'),
                        'real_order_id' => $this->translate('Regular')
                    );?>
                    <?php if(!empty($this->orderSubtypes)):?>
                        <?php foreach ($this->orderSubtypes as $orderSubtype):?>
                            <?php $orderTypes[$orderSubtype] = $this->translate(ucfirst($orderSubtype));?>
                        <?php endforeach;?>
                    <?php endif;?>
                    <?php echo $this->formSelect('filter-order-type', null, array(
                        'class' => 'filter',
                        'data-placeholder' => $this->translate('show all')
                    ), $orderTypes); ?>
                </p>
                <div class="grid_8 omega">
                    <label class="text-bold"><?php echo $this->translate('By shipping destination');?></label>
                    <?php
                    $countryList = Tools_Geo::getCountries(true);
                    $countryList = array_merge(array('_' => ''), $countryList);
                    echo '<div class="grid_4 alpha t-grid_2 t-alpha">' . $this->formSelect('filter-country', null, array('class' => 'filter', 'data-placeholder' => $this->translate('shipping country')), $countryList ) . '</div>';
                    echo '<div class="grid_4 t-grid_2">' . $this->formSelect('filter-state', null, array('class' => 'filter', 'data-placeholder' => $this->translate('shipping state')), array('') ) . '</div>';



                $shippingServices = array_merge(array(''), $this->shippingServices);
                echo '<div class="grid_4 omega t-grid_2 t-omega">' . $this->formSelect('filter-carrier', null, array('class' => 'filter', 'data-placeholder' => $this->translate('shipping carrier')), $shippingServices ) . '</div>';
                ?>
            </div>
            <div class="grid_2 mt20px">
                <label><input type="checkbox" id="exclude-quotes-from-search" name="exclude-quotes-from-search"> <?php echo $this->translate('Exclude quotes');?></label>
                <label><input type="checkbox" id="is-a-gift" name="is-a-gift"> <?php echo $this->translate('Is a gift');?></label>
            </div>
            <div class="grid_12 alpha omega text-right">
                <button class="btn green ticon-checkmark" name="filter-apply" id="orders-filter-apply-btn"><?php echo $this->translate('Apply filter');?></button>
                <button class="btn red ticon-reload" name="filter-reset" id="orders-filter-reset-btn"><?php echo $this->translate('Reset all filters');?></button>
            </div>
        </div>
    </form>
    <div class="responsive-table">
        <table id="orders-table" class="widget table-hover">
            <thead>
                <tr class="title-table">
                    <th><input type="checkbox" name="checkAllOrders" id="orders-check-all" value="1" title="Check/Uncheck All"></th>
                    <th>#</th>
                    <th class="sortable" data-sortkey="name"><?php echo $this->translate('Customer name');?></th>
                    <th class="sortable" data-sortkey="email"><?php echo $this->translate('Email');?></th>
                    <th class="sortable sortDown" data-sortkey="aggregatedPurchasedOn"><?php echo $this->translate('Purchased on');?></th>
                    <th class="sortable" data-sortkey="status" style="min-width: 180px;"><?php echo $this->translate('Status');?></th>
                    <th class="sortable" data-sortkey="products"><?php echo $this->translate('Products in cart');?></th>
                    <th class="sortable" data-sortkey="total"><?php echo $this->translate('Total price');?></th>
                    <th class="sortable" data-sortkey="shipping_price"><?php echo $this->translate('Shipping price');?></th>
                    <th style="min-width: 110px;"><?php echo $this->translate('Shipping via');?></th>
                    <th class="text-center"><?php echo $this->translate('Details');?></th>
                    <?php if(isset($this->invoicePlugin)):?>
                        <th class="text-center"><?php echo $this->translate('Invoice & packing slip');?></th>
                    <?php endif;?>
                    <th data-sortkey="real_order_id"><?php echo $this->translate('Order type');?></th>
                </tr>
            </thead>
            <tbody id="orders-list">
            <?php if(isset($this->invoicePlugin)):?>
                <td colspan="13" style="text-align:center;">
            <?php else:?>
                 <td colspan="8" style="text-align:center;">
            <?php endif;?>
                    <img src="<?php echo $this->websiteUrl;?>system/images/spinner-small.gif" border="0" alt="loading..." />
                </td>
            </tbody>
            <tfoot>
            <td colspan="4">
                <?php echo $this->translate('with selected do');?>
                <select name="order-mass-action" id="mass-action">
                    <option value="0"><?php echo $this->translate('nothing');?></option>
                    <option value="exportOrders"><?php echo $this->translate('Export orders');?></option>
                </select>
            </td>
            <?php if(isset($this->invoicePlugin)):?>
                    <td colspan="9" class="paginator text-right"></td>
                <?php else:?>
                    <td colspan="8" class="paginator text-right"></td>
                <?php endif;?>
            </tfoot>
        </table>
        <input type="hidden" name="orders-secure-token" class="orders-secure-token" value="<?php echo Tools_System_Tools::initSecureToken(Shopping::SHOPPING_SECURE_TOKEN);?>" />
        <?php if(isset($this->invoicePlugin)):?>
            <input type="hidden" value="enabled" name="invoiceEnable" id="invoiceEnable"/>
        <?php endif;?>
    </div>
</div>

<script type="text/javascript">
$(function(){
	$('select.filter', '#store-orders').chosen({
		allow_single_deselect: true
	});
	var filterFromDate = $('#orders-filter-fromdate', '#store-orders'),
		filterToDate = $('#orders-filter-todate', '#store-orders');
	filterFromDate.datepicker({
	    dateFormat: 'd-M-yy',
        defaultDate: "+1w",
	    changeMonth: true,
	    changeYear: true,
	    yearRange: "c-5:c+5",
	    onSelect: function(selectedDate){
		    filterToDate.datepicker("option", "minDate", selectedDate);
	    }
    });
    filterToDate.datepicker({
        dateFormat: 'd-M-yy',
        defaultDate: "+1w",
        changeMonth: true,
	    changeYear: true,
	    yearRange: "c-5:c+5",
        onSelect: function(selectedDate){
	        filterFromDate.datepicker("option", "maxDate", selectedDate);
        }
    });
	$('#filter-state').on('addressChain:updated', function(){
		$(this).prepend('<option value="0"></option>').trigger('chosen:updated');
	});
	$('#extra-filters').addressChain({
		countrySelector: $('#filter-country'),
		stateSelector: $('#filter-state'),
		toogleStateVisibility: false,
		url: $('#website_url').val()+'api/store/geo/type/state?pairs'
	});

    var filterDefaultCouponCode = localStorage.getItem('couponCode');
    if (filterDefaultCouponCode) {
        $('#filter-by-coupon-code').val(filterDefaultCouponCode);
        localStorage.removeItem('couponCode');
    }

    var searchData = <?php echo json_encode(array_values($this->usedCoupons));?>;
    $('#filter-by-coupon-code').autocomplete({
        minLength: 2,
        source: searchData,
        messages: {
            noResults: '',
            results: function() {}
        }
    });
});
</script>
