
<div class="post-purchase-report-customer-info">
    <span class="title"><?php echo $this->translate('Sold to');?>:</span>
    <?php if (null !== ($billingAddressId = $this->cart->getBillingAddressId())): ?>
        <?php $billingAddress = Tools_ShoppingCart::getAddressById($billingAddressId);?>
        <p class="customer-name"><?php echo $billingAddress['firstname'];?> <?php echo $billingAddress['lastname'];?></p>
    <?php endif;?>
</div>


<div class="post-purchase-report-billing">
<span class="title"><?php echo $this->translate('Billing Address');?>:</span>
    <div class="post-purchase-report-billing-address">
        <?php if (null !== ($billingAddressId = $this->cart->getBillingAddressId())): ?>
        	<?php $billingAddress = Tools_ShoppingCart::getAddressById($billingAddressId);?>
			<span class="street-address"><?php echo $billingAddress['address1'].' '. $billingAddress['address2'];?></span>
			<br/>
			<span class="locality"><?php echo $billingAddress['city'].($billingAddress['city']&&($billingAddress['state'] || $billingAddress['zip'])?',':'');?></span>
			<span class="region"><?php $state = Tools_Geo::getStateById($billingAddress['state']); echo $state['state']; ?></span>
			<span class="postal-code"><?php echo $billingAddress['zip'];?></span>
			<br />
			<span><?php echo $countryList[$billingAddress['country']];?></span>
		<?php else:?>
			<p><?php echo $this->translate('not provided');?></p>
		<?php endif;?>
    </div>
</div>
<p style="clear:both"></p>
<table class="post-purchase-report">
	<thead>
		<tr>
			<th><?php echo $this->translate('Product'); ?></th>
			<th><?php echo $this->translate('Price'); ?></th>
			<th><?php echo $this->translate('Qty'); ?></th>
			<th><?php echo $this->translate('Total'); ?></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->cartContent as $product) :?>
		<tr>
            <td>
                <?php if(isset($product['photo']) && $product['photo'] != ''):?>
                    <img src="<?php echo $this->websiteUrl;?>/media/<?php echo str_replace('/', '/product/', $product['photo']);?>" alt="<?php echo $product['name']; ?>"/>
                <?php else:?>
                    <img src="<?php echo $this->websiteUrl;?>system/images/noimage.png" alt="<?php echo $product['name']; ?>"/>
                <?php endif;?>
                <?php echo $product['name']; ?>
                <?php if(!empty($product['options'])):?>
                    <?php foreach($product['options'] as $optData): ?>
                        <p>
                        <?php echo $optData['title']; ?>
                       <?php if(intval($optData['priceValue'])): ?>
                            <span>(<?php echo $optData['priceSign'], $optData['priceValue']; ?>)</span>
					   <?php endif; ?>
                            <?php if(intval($optData['weightValue'])): ?>
		                    <span>(<?php echo $optData['weightSign'], ' ', $optData['weightValue'],' ', $this->weightSign; ?>)</span>
		               <?php endif; ?>
                        </p>
                    <?php endforeach; ?>
                <?php endif;?>
            </td>
			<td><?php echo $this->currency($product['tax_price']); ?></td>
			<td><?php echo $product['qty']; ?></td>
			<td><?php echo $this->currency($product['tax_price'] * $product['qty']); ?></td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
<div class="post-purchase-report-shipping">
    <span class="title"><?php echo $this->translate('Shipping Address');?>:</span>
    <div class="post-purchase-report-shipping-address">
    <?php if (null !== ($shippingAddressId = $this->cart->getShippingAddressId())): ?>
    <?php $shippingAddress = Tools_ShoppingCart::getAddressById($shippingAddressId);?>
    <span><?php echo $shippingAddress['firstname'];?></span>
    <span><?php echo $shippingAddress['lastname'];?></span>
    <br/>
    <span class="street-address"><?php echo $shippingAddress['address1'].' '. $shippingAddress['address2'];?></span>
                <br/>
                <span class="locality"><?php echo $shippingAddress['city'].($shippingAddress['city']&&($shippingAddress['state'] || $shippingAddress['zip'])?',':'');?></span>
                <span class="region"><?php $state = Tools_Geo::getStateById($shippingAddress['state']); echo $state['state']; ?></span>
                <span class="postal-code"><?php echo $shippingAddress['zip'];?></span>
                <br />
                <span><?php echo $countryList[$shippingAddress['country']];?></span>
			<?php else:?>
                <p><?php echo $this->translate('not provided');?></p>
			<?php endif;?>
    </div>
</div>
<div class="post-purchase-report-summary">
	<div class="post-purchase-row cart-subtotal">
		<span><?php echo $this->translate('Sub-Total');?></span>
        <?php if($this->showPriceIncTax == 1):?>
            <span id="subtotal-val"><?php echo $this->currency($this->cart->getSubTotal()+$this->cart->getTotalTax());?></span>
        <?php else:?>
            <span id="subtotal-val"><?php echo $this->currency($this->cart->getSubTotal());?></span>
        <?php endif;?>
	</div>
	<div class="post-purchase-row cart-total-tax">
        <?php if($this->showPriceIncTax == 1):?>
            <span><?php echo $this->translate('Inc. Tax');?>:</span>
        <?php else:?>
            <span><?php echo $this->translate('Total Tax');?>:</span>
        <?php endif;?>
			<span><?php echo $this->currency($this->cart->getTotalTax());?></span>
	</div>
	<div class="post-purchase-row cart-shipping">
		<span><?php echo $this->translate('Shipping');?>
				<?php if ($this->cart->getShippingService()):?>
				<?php echo $this->translate(' via ') .$this->cart->getShippingService().': '.$this->cart->getShippingType(); ?>
				<?php endif;?>
        </span>
		<span><?php echo $this->currency($this->cart->getShippingPrice());?></span>
	</div>
	<div class="post-purchase-row cart-total">
		<span><?php echo $this->translate('Total');?>:</span>
		<span><?php echo $this->currency($this->cart->getTotal());?></span>
	</div>
</div>
