<ul id="sortable-<?php echo $this->dragListId; ?>" style="list-style: none;">
    <?php foreach ($this->dragproducts as $product): ?>
        <?php
        $img = $product->getPhoto();
        $imgArr = explode('/', $img);

        ?>
        <li>
            <p class="product_id" style="display: none;"><?php echo $product->getId(); ?></p>
            <?php if (!empty($imgArr[1])) :?>
                <img src="<?php echo $this->websiteUrl . 'media/' . $imgArr[0] . '/small/' . $imgArr[1]; ?>" alt="">
            <?php else:?>
                <img src="<?php echo $this->websiteUrl . 'system/images/no_image.png';?>" alt="">
            <?php endif;?>
            <p><?php echo $product->getName(); ?></p>
        </li>
    <?php endforeach; ?>
</ul>
<input id="website_url" type="hidden" value="<?php echo $this->websiteUrl; ?>">
<input id="<?php echo $this->dragListId; ?>" type="hidden" value="<?php echo $this->dragListId; ?>">
<button class="save_drag_pos btn" id="save_drag_pos-<?php echo $this->dragListId; ?>"><?php echo $this->translate('Save position');?></button>
<script>
    $(function () {
        $("#sortable-<?php echo $this->dragListId; ?>").sortable();
        $("#sortable-<?php echo $this->dragListId; ?>").disableSelection();

        $('#save_drag_pos-<?php echo $this->dragListId; ?>').on('click', function () {
            var sort_order = [];
            $('#sortable-<?php echo $this->dragListId; ?> li p.product_id').each(function (index) {
                sort_order.push($(this).text());
            });

            var action = $('#website_url').val() + 'plugin/shopping/run/saveDragListOrder';
            var data = {'list_data': sort_order, 'list_id': $('#<?php echo $this->dragListId; ?>').val()}
            $.ajax({
                url: action,
                data: data,
                type: 'post',
                dataType: 'json'
            }).done(function(response) {
                if(response.error == 1){
                    smoke.alert(response.responseText,{'classname':'errors'});
                }else{
                    smoke.signal('<?php echo $this->translate('Saved');?>');
                }
            });

        });

    });

</script>