<?php $id = uniqid('pl-'); ?>
<?php if(empty($this->unwrap)): ?>
    <div class="product-list">
<?php endif;?>
        <?php if (!empty($this->isPreview) && Tools_Security_Acl::isAllowed(Shopping::RESOURCE_STORE_MANAGEMENT)):?>
            <a class="btn backToOriginal"><?php echo $this->translate('Back to drag & drop');?></a>
        <?php endif;?>
        <?php echo $this->plContent; ?>
        <?php if ($this->totalCount >= $this->limit): ?>
        <a href="#<?php echo $id;?>" class="show-more" id="<?php echo $id; ?>"><?php echo $this->translate('show more'); ?></a>
        <?php endif; ?>
<?php if(empty($this->unwrap)): ?>
    </div>
<?php endif;?>
<script type="application/javascript">
    $(function() {
        $('.backToOriginal').on('click', function (e) {
            e.preventDefault();
            var pathName = window.location.pathname;
            window.location.href = '<?php echo rtrim($this->websiteUrl, '/'); ?>' + pathName;
        });
    });
</script>
<?php if ($this->totalCount >= $this->limit): ?>
<script>
	$('#<?php echo $id; ?>').on('click', function(e){
        e.preventDefault();
        $(this).hide();

        var self = this,
	        nextpage = $(this).data('nextpage') || 1,
		    filters = $.extend({
			    pageId: '<?php echo $this->pageId; ?>',
			    template: '<?php echo $this->productTemplate; ?>',
			    nextpage: nextpage,
                limit: '<?php echo $this->limit; ?>',
                sort: '<?php echo $this->sort; ?>'
		    }, <?php echo json_encode(!empty($this->filters) ? array_filter($this->filters) : array()); ?>,
                <?php echo json_encode(!empty($this->filterAttributes) ? array_filter($this->filterAttributes) : array()); ?>,
                <?php echo json_encode(!empty($this->price) ? array_filter(array('price' => $this->price)) : array()); ?>,
				<?php echo json_encode(!empty($this->dragListId) ? array('draglist_id' => $this->dragListId): array());?>,
				<?php echo json_encode(!empty($this->filterable) ? array('filterable' => $this->filterable): array());?>);

		showSpinner('body', 'show-more-spinner');

		$.post('<?php echo $this->websiteUrl; ?>plugin/shopping/run/renderproducts/', filters, function(response) {
            hideSpinner('.show-more-spinner');
            $(self).show();
            if (response) {
                $(self).before(response);
				$(self).data('nextpage', ++nextpage);
            } else {
	            $(self).replaceWith('<span><?php echo $this->translate('No more products found'); ?></span>');
            }
		});
	});

</script>
<?php endif; ?>
