const messages = {
    en: {
        message: {
            actionConfirmation: 'Are you sure?',
            fieldType: 'Field Type',
            fieldName: 'Field Name',
            fieldLabel: 'Field Label',
            fieldAction: 'Action',
            addFieldToScreen: 'Add fields to your screen',
            customFeieldType: 'Custom field type',
            textField: 'Text field',
            dropdownField: 'Dropdown',
            customFieldName: 'Custom field name',
            customFieldLabel: 'Custom field label',
            first: 'First',
            previous: 'Previous',
            next: 'Next',
            last: 'Last',
            total: 'Total',
            records: 'records',
            found: 'found',
            specifyParamType: 'Please select field type',
            specifyParamName: 'Please specify field name',
            specifLabel: 'Please specify label',
            relogin: 'Please re-login',
            emptyLabel: 'label can\'t be empty',
            emptyName: 'name can\'t be empty',
            back: 'Back',
            title: 'Title',
            addNewSelection: 'Add new selection',
            provideOptionName: 'Please provide option name',
            specifySelectionEl: 'Please add at least one selection',
            specifyOptionName: 'Please specify option name',
            updateError: 'Can\'t update dropdown field',
            actionConfirmationDeleteSelect: 'This selection can used in product, Would you like to delete?'

        }
    },
    es: {
        message: {
            actionConfirmation: 'Are you sure?',
            fieldType: 'Field Type',
            fieldName: 'Field Name',
            fieldLabel: 'Field Label',
            fieldAction: 'Action',
            addFieldToScreen: 'Add fields to your screen',
            customFeieldType: 'Custom field type',
            textField: 'Text field',
            dropdownField: 'Dropdown',
            customFieldName: 'Custom field name',
            customFieldLabel: 'Custom field label',
            first: 'First',
            previous: 'Previous',
            next: 'Next',
            last: 'Last',
            total: 'Total',
            records: 'records',
            found: 'found',
            specifyParamType: 'Please select field type',
            specifyParamName: 'Please specify field name',
            specifLabel: 'Please specify label',
            relogin: 'Please re-login',
            emptyLabel: 'label can\'t be empty',
            emptyName: 'name can\'t be empty',
            back: 'Back',
            title: 'Title',
            addNewSelection: 'Add new selection',
            provideOptionName: 'Please provide option name',
            specifySelectionEl: 'Please add at least one selection',
            specifyOptionName: 'Please specify option name',
            updateError: 'Can\'t update dropdown field',
            actionConfirmationDeleteSelect: 'This selection can used in product, Would you like to delete?'

        }
    },
    fr: {
        message: {
            actionConfirmation: 'Are you sure?',
            fieldType: 'Field Type',
            fieldName: 'Field Name',
            fieldLabel: 'Field Label',
            fieldAction: 'Action',
            addFieldToScreen: 'Add fields to your screen',
            customFeieldType: 'Custom field type',
            textField: 'Text field',
            dropdownField: 'Dropdown',
            customFieldName: 'Custom field name',
            customFieldLabel: 'Custom field label',
            first: 'First',
            previous: 'Previous',
            next: 'Next',
            last: 'Last',
            total: 'Total',
            records: 'records',
            found: 'found',
            specifyParamType: 'Please select field type',
            specifyParamName: 'Please specify field name',
            specifLabel: 'Please specify label',
            relogin: 'Please re-login',
            emptyLabel: 'label can\'t be empty',
            emptyName: 'name can\'t be empty',
            back: 'Back',
            title: 'Title',
            addNewSelection: 'Add new selection',
            provideOptionName: 'Please provide option name',
            specifySelectionEl: 'Please add at least one selection',
            specifyOptionName: 'Please specify option name',
            updateError: 'Can\'t update dropdown field',
            actionConfirmationDeleteSelect: 'This selection can used in product, Would you like to delete?'

        }
    }

};

export default messages;
