<form name="user-edit-account" id="user-edit-account" action="<?php echo $this->websiteUrl; ?>plugin/shopping/run/editAccount/" method='post' enctype="multipart/form-data">
    <p><label><?php echo $this->translate('Current email');?>:</label>
        <span class="user-current-email"><?php echo $this->currentEmail;?></span></p>
    <input type="hidden" name="currentEmail" value="<?php echo $this->currentEmail;?>" />
    <p><?php echo $this->userForm->getElement('newEmail')->renderLabel(); ?>
        <?php echo $this->userForm->getElement('newEmail')->renderViewHelper(); ?></p>
    <p><?php echo $this->userForm->getElement('newEmailConfirm')->renderLabel(); ?>
        <?php echo $this->userForm->getElement('newEmailConfirm')->renderViewHelper(); ?></p>
    <p><?php echo $this->userForm->getElement('currentPassword')->renderLabel(); ?>
        <?php echo $this->userForm->getElement('currentPassword')->renderViewHelper(); ?></p>
    <p><?php echo $this->userForm->getElement('newPassword')->renderLabel(); ?>
        <?php echo $this->userForm->getElement('newPassword')->renderViewHelper(); ?></p>
    <p><?php echo $this->userForm->getElement('newPasswordConfirm')->renderLabel(); ?>
        <?php echo $this->userForm->getElement('newPasswordConfirm')->renderViewHelper(); ?></p>
    <input type="hidden" name="<?php echo Tools_System_Tools::CSRF_SECURE_TOKEN;?>" value="<?php echo Tools_System_Tools::initSecureToken(Shopping::SHOPPING_SECURE_TOKEN);?>">
    <?php echo $this->userForm->getElement('saveUser')->renderViewHelper(); ?>
</form>

<script type="text/javascript">
    $(function() {
        var form = $('#user-edit-account');
        $(document).on('submit', '#user-edit-account', function(e) {
                e.preventDefault();
                $.ajax({
                    url      : form.attr('action'),
                    type     : 'post',
                    data     : form.serialize(),
                    beforeSend: showSpinner(),
                    dataType :'json',
                    success  : function(response) {
                        hideSpinner();
                        if(response.error) {
                            showMessage(response.responseText, response.error);
                        } else {
                            $('#user-edit-account').find(':input[type=text]').val('');
                            $('#user-edit-account').find(':input[type=password]').val('');
                            $('.user-current-email').html(response.responseText.email);
                            showMessage(response.responseText.message);
                        }
                    }
                });

        });

    });
</script>