<style type="text/css">
    #group-table_paginate a[role="button"] {
        display: inline-block;
        cursor: pointer;
        padding: 4px 0;
    }
    #group-table_paginate a[role="button"]:not(:first-child) {
        padding-left: 10px;
    }
</style>


<div id="editing-grouping-price" class="grid_12 mt10px clearfix">
    <input type="hidden" id="group-products-id" name="group-products-id" value=""/>

</div>

