<?php $this->headTitle($this->translate('Manage customers')); ?>

<script id="tableRowTemplate" type="text/x-jquery-tmpl">
    <td class="check-td textcentered"><input type="checkbox" name="select[]" value="${id}" title="Click to mark/unmark ${full_name}" {{if checked}}checked="checked"{{/if}} /></td>
    <td class="full-name text-left"><a href="javascript:;" class="details">${full_name}</a></td>
    <td class="email text-left"><a href="mailto:${email}">${email}</a></td>
    <td class="date textcentered">${reg_date}</td>
    <td class="total textcentered"><span>{{if total_amount}}${total_amount}{{else}}0{{/if}}</span> (${total_orders})</td>
</script>

<script id="customerDetailsTemplate" type="text/x-jquery-tmpl">
	<h2 class="fn">${fullName}</h2>
	<h3><a href="mailto:${email}" class="email">${email}</a></h3>
	<p>${roleId} since ${regDate}</p>

</script>

<script id="addressTemplate" type="text/x-jquery-tmpl">
	<div class="adr">
		<h3><?php echo $this->translate('Default shipping address');?></h3>
		<span class="street-address">address1 + address2</span>
		<br/>
		<span class="locality">city</span>
		<span class="region">state</span>
		<span class="postal-code">zip</span>
	</div>
</script>

<?php
    $this->headScript()->setAllowArbitraryAttributes(true)
		    ->appendFile($this->websiteUrl . 'system/js/external/jquery/plugins/tmpl/jquery.tmpl.min.js')
			->appendFile($this->websiteUrl.'plugins/shopping/web/js/libs/require/require.js', null, array('data-main' => $this->websiteUrl.'plugins/shopping/web/js/clients.js'));

	echo $this->noLayout ? $this->headScript() : '';
?>
<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/css/reset-widgets.css') ?>
<div id="clients" class="ui-helper-clearfix">
    <table id="clients-table" class="widget" style="width: 100%">
        <thead>
            <tr class="search-line">
				<th colspan="5" class="gray-bg">
					<label><?php echo $this->translate('Search');?></label>
					<input type="text" id="clients-search" name="clients-search" placeholder="<?php echo $this->translate('by name or email');?>"/>
                </th>
            </tr>
            <tr class="title-table">
	            <th width="30px"><?php echo $this->formCheckbox('clients-check-all', null, array('title' => 'Check/Uncheck All'));?></th>
	            <th class="sortable" data-sortkey="full_name"><?php echo $this->translate('Full Name');?></th>
	            <th class="sortable" data-sortkey="email"><?php echo $this->translate('Email');?></th>
	            <th class="sortable" data-sortkey="reg_date"><?php echo $this->translate('Registered');?></th>
	            <th class="sortable" data-sortkey="total_amount"><?php echo $this->translate('Total Spend (orders)');?></th>
            </tr>
        </thead>
        <tbody id="customer-list">
            <tr>
	            <td colspan="5" class=" textcentered"><img src="<?php echo $this->websiteUrl;?>/system/images/loading.gif"/></td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
	            <td colspan="3" class="ui-resizable text-left">
		            <?php echo $this->translate('with selected do');?>
					<!-- @todo add some actions -->
		            <select id="mass-action">
			            <option value="0"><?php echo $this->translate('nothing');?></option>
			            <option value="deleteSelected"><?php echo $this->translate('delete');?></option>
		            </select>
	            </td>
	            <td class="textcentered">
		            <form id="export-users-form" action="<?php echo $this->websiteUrl;?>backend/backend_user/export/" method="post"><a href="javascript:;" id="export-users">[&nbsp;<?php echo $this->translate('export as csv file');?>&nbsp;]</a></form>
	            </td>
	            <td class="textcentered">
		            <a href="#" id="clients-previous" class="table-nav mr15px">&#8656;&nbsp;<?php echo $this->translate('previous');?></a>
		            <a href="#" id="clients-next" class="table-nav"><?php echo $this->translate('next');?>&nbsp;&#8658;</a>
	            </td>
            </tr>
        </tfoot>
    </table>

	<div id="customer-details">
		<div class="toolbar">
			<a href="javascript:;" class="link btn-text">[ &#8678; back to clients list ]</a>
		</div>
		<div id="profile">

		</div>
	</div>
</div>
