<?php
$this->headTitle($this->translate('Manage config'));

$this->jQuery()->addJavascriptFile($this->websiteUrl.'plugins/shopping/web/js/libs/jquery/jquery.select-chain.js');
?>

<script>
<?php $this->jQuery()->onLoadCaptureStart();?>
	$('div.seotoaster > div.ui-widget-header:first').remove();

	var shopping = {};
	shopping.saveconfig = function(){
		var url = '<?php echo $this->form->getAction(); ?>';
		var data = $('form[user-changed="true"]').serialize();
		if (!data) {
			window.console && console.log('nothing to save');
			return false;
		} else {
			window.console && console.log(data);
		}

		$.ajax({
			url: url,
			data: data,
			type: 'POST',
			dataType: 'html',
			success: function(response){
				$('form[user-changed="true"]').removeAttr('user-changed');
				$('#config > ul > li > a.user-changed').removeClass('user-changed');
                showMessage('<?php echo $this->translate('Saved'); ?>');
			}
		});
	}

	$('#save-btn').on('click', shopping.saveconfig);

	$('#config').tabs({
		select: function(event, ui){
			$form = $(ui.panel).children('form');
			if ($form.attr('user-changed') === true && $form.find(':submit').size() == 0) {
				$form.append('<input type=submit />');
			}
		}
	});
	$('select[name$="country"]').each(function(){
		var $stateField = $(this).closest('form').find('select[name$="state"]');
		$(this).selectChain({
			data: {
                country: $(this).val(),
                pairs: true
            },
			target: $stateField,
			url: '<?php echo $this->websiteUrl; ?>plugin/shopping/run/getdata/type/states'
		})
	});

	$('form :input').on('change', function(){
		var $form = $(this).closest('form');
		if (!$form.attr('user-changed')){
			$form.attr('user-changed', true);
			var currentTab = $('#config').tabs('option', 'selected');
			$('#config > ul > li:eq('+currentTab+') > a').addClass('user-changed');
		}
	});

    $('.no-save-btn').on('click', function() {
        $('#save-btn').hide();
    })
    $('a').not('.no-save-btn').on('click', function() {
        $('#save-btn').show();
    })
<?php $this->jQuery()->onLoadCaptureEnd();?>
</script>

<style>
	a.user-changed::after {
		content: '*'
	}
    .ui-tabs#config .ui-tabs-panel {
        padding: 10px 10px 10px 15px;
        background: #DAE8ED;
    }
    #config .ui-tabs-nav li.ui-tabs-selected {
        background: #DAE8ED;
    }
    button#save-btn {
        float: right;
        margin: 0 20px 10px;
    }
	.email-trigger label {
		display: inline-block;
	}
	.email-trigger select {
		width: 300px;
	}
</style>

<div id="config" class="h540">
    <div class="closebutton"><span class="close"><?php echo $this->translate('Close'); ?></span></div>
    <ul>
        <?php foreach ($this->form->getSubForms() as $subform): ?>
            <li><a href="#<?php echo $subform->getId(); ?>-tab"><?php echo $subform->getLegend(); ?></a></li>
        <?php endforeach; ?>
        <?php if(isset($this->configTabs) && is_array($this->configTabs) && !empty($this->configTabs)): ?>
            <?php foreach($this->configTabs as $configTab): ?>
                <li><a class="no-save-btn" href="<?php echo $configTab['contentUrl']; ?>"><?php echo $configTab['title']; ?></a></li>
            <?php endforeach; ?>
        <?php endif; ?>
	</ul>
	<?php echo $this->form; ?>
    <button id="save-btn" class="mt10px"><?php echo $this->translate('Save');?></button>
</div>
