<?php $countryList = Tools_Geo::getCountries(true); ?>
<div class="clearfix profile-header">
	<div class="profile-picture">
		<?php echo $this->gravatar($this->customer->getEmail(), array('secure'=>true), array('class' => 'avatar') ); ?>
	</div>
	<div class="profile-main-info vcard">
		<h1 class="fn"><?php echo $this->customer->getFullName();?></h1>
		<h3><a href="mailto:<?php echo $this->customer->getEmail();?>" class="email"><?php echo $this->customer->getEmail();?></a></h3>
		<p><?php echo $this->customer->getRoleId();?> since <?php echo $this->customer->getRegDate();?></p>
		<?php if ($billingAddressDefault = $this->customer->getDefaultAddress('billing')) : ?>
			<div class="adr">
				<span class="street-address"><?php echo $billingAddressDefault['address1'].' '. $billingAddressDefault['address2'];?></span>
				<br/>
				<span class="locality"><?php echo $billingAddressDefault['city'];?></span>
				<span class="region"><?php $state = Tools_Geo::getStateById($billingAddressDefault['state']); echo $state['state']; ?></span>
				<span class="postal-code"><?php echo $billingAddressDefault['zip'];?></span>
			</div>
		<?php endif;?>
		<?php if ($shippingAddressDefault = $this->customer->getDefaultAddress('shipping')) : ?>
			<div class="adr">
				<span class="street-address"><?php echo $shippingAddressDefault['address1'].' '. $shippingAddressDefault['address2'];?></span>
				<br/>
				<span class="locality"><?php echo $shippingAddressDefault['city'];?></span>
				<span class="region"><?php $state = Tools_Geo::getStateById($shippingAddressDefault['state']); echo $state['state']; ?></span>
				<span class="postal-code"><?php echo $shippingAddressDefault['zip'];?></span>
			</div>
		<?php endif;?>
	</div>
	<div class="profile-actions">
		<input type="button" class="blue-btn" value="<?php echo $this->translate('Edit profile');?>" />
		<ul class="stats">
			<li><a href="">15 orders</a></li>
			<li>10 payed orders</li>
			<li>5 pending orders</li>
			<li>17 products in whishlist</li>
		</ul>
	</div>
</div>
<div class="profile-dashboard">
	<ul class="profile-nav">
		<li><a href="#profile-address-list">Addresses</a></li>
		<li><a href="#profile-orders-list">Orders</a></li>
	</ul>
</div>
<div class="profile-content">
	<div id="profile-address-list">
	<?php $addressList = $this->customer->getAddresses(); ?>
	<?php if (!empty($addressList)): ?>
	<?php foreach ($addressList as $billingAddress): ?>
		<div class="adr">
			<?php echo $this->formHidden('id', $billingAddress['id'], array('id'=>'id_'.$billingAddress['id']));?>
			<?php echo $this->formHidden('type', $billingAddress['address_type'], array('id'=>'type_'.$billingAddress['id']));?>
			<span class="street-address"><?php echo $billingAddress['address1'].' '. $billingAddress['address2'];?></span>
			<br/>
			<span class="locality"><?php
				echo $billingAddress['city'].
					($billingAddress['city']&&($billingAddress['state'] || $billingAddress['zip'])?',':'');
				?></span>
			<span class="region"><?php $state = Tools_Geo::getStateById($billingAddress['state']); echo $state['state']; ?></span>
			<span class="postal-code"><?php echo $billingAddress['zip'];?></span>
			<br />
			<span><?php echo $countryList[$billingAddress['country']];?></span>
<!--			<a class="delete-lnk" href="javascript:;" title="--><?php //echo $this->translate('Delete this address');?><!--"><img src="/system/images/delete.png" alt="[x]"></a>-->
		</div>
	<?php endforeach; ?>
	<?php else : ?>
	<p>no addresses</p>
	<?php endif;?>
	</div>
	<div id="profile-orders-list">
		<p>Orders list:</p>
		<table border="1" width="100%">
			<thead>
				<tr>
					<th>Order #</th>
					<th>Purchased On</th>
					<th>Status</th>
					<th>Products in cart</th>
					<th>Total Price</th>
					<th>Shipping price</th>
					<th>Shipping via</th>
					<th>Details</th>
				</tr>
			</thead>
			<tbody>
			<?php if ($this->orders): ?>
			<?php foreach ($this->orders as $order):?>
				<tr data-role="cart" data-id="<?php echo $order->getId();?>">
					<td><?php echo $order->getId();?></td>
					<td><?php echo Zend_Date::now();?></td>
					<td><?php echo $order->getStatus();?></td>
					<td><?php echo sizeof($order->getCartContent());?></td>
					<td><?php echo $this->currency($order->getTotal());?></td>
					<td><?php echo $this->currency($order->getShippingPrice()) ;?></td>
					<td class="shipping-data">
						<p><?php echo $order->getShippingService().' - '.$order->getShippingType() ;?></p>
						<?php if (Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_ADMINPANEL)):?>
						<p>
							<u>Tracking ID</u>: <span class="tracking-id"><?php echo $order->getShippingTrackingId(); ?></span>
							<a href="javascript:;" class="tracking-dialog" data-shipping-tracking-id="<?php echo $order->getShippingTrackingId();?>">[&nbsp;edit&nbsp;]</a>
						</p>
						<?php endif;?>
						<p class="textcentered">
							<a target="_blank" class="tracking-link" href="<?php echo $this->websiteUrl;?>plugin/shopping/run/track/id/<?php echo $order->getId();?>"><?php echo $this->translate('Where is my order?');?></a>
						</p>
					</td>
					<td><a href="javascript:;" class="tpopup" data-url="<?php echo $this->websiteUrl;?>plugin/shopping/run/order/id/<?php echo $order->getId();?>">view</a></td>
				</tr>
			<?php endforeach; ?>
			<?php else: ?>
			<tr><td colspan="8" class="padding5px textcentered"><?php echo $this->translate("You don't have any orders yet");?></td></tr>
			<?php endif; ?>
			</tbody>
		</table>
		<?php //var_dump($this->orders); ?>
	</div>
</div>
<script>
	//	simple tab script for navigation
	$('div.profile-content > div:first').siblings().hide().end().show();
	$('ul.profile-nav').find('a:first').addClass('active').end().on('click', 'a', function(e){
		e.preventDefault();
		$(this).closest('ul').find('li > a').removeClass('active');
		$(this).addClass('active');
		var containerId = $(this).attr('href');
		$(containerId).siblings('div').hide().removeClass('active').end().show().addClass('active');
	});
	$('a.tracking-dialog').on('click', function(e){
		e.preventDefault();
		var self = this,
			id = parseInt($(this).closest('tr').data('id'));
		smoke.prompt('<?php echo $this->translate('Insert tracking code for this order');?>', function(value){
			value = $.trim(value);
			if (value !== false && $(self).data('shippingTrackingId') !== value) {
				$.ajax({
					url: $('#website_url').val()+'plugin/shopping/run/order?id='+id,
					data: {shippingTrackingId: value},
					type: 'POST',
					dataType: 'json',
					success: function(response) {
						showMessage('<?php echo $this->translate('Saved');?>', response.hasOwnProperty('error') && response.error);
						if (response.hasOwnProperty('responseText')){
							$(self).data('shippingTrackingId', response.responseText.shippingTrackingId);
							$(self).closest('p').find('span.tracking-id').text(response.responseText.shippingTrackingId);
						}
					}
				});
			}
		});
	});
</script>
<style>
	#profile .profile-header > div {
		float: left;
	}
	#profile .profile-header .profile-picture {
		width: 10%;
		min-width: 80px;
		margin: 0 1%;
	}
	#profile .profile-header .profile-main-info {
		width: 50%
	}
	#profile .profile-header .profile-actions {
		width: 30%
	}
	#profile ul {
		margin: 0;
		padding: 0;
	}
	#profile ul li {
		list-style: none;
		margin: 0;
		padding: 0;
	}
	#profile .profile-dashboard {
		width: 19%;
		float: left;
	}
	#profile .profile-content {
		width: 79%;
		float: left;
		padding: 4px 2px;
		border: 1px solid #e6e6fa;
		border-radius: 0 8px 8px 0;
	}
	#profile ul.profile-nav li {
		background-color: #e6e6fa;
		margin-bottom: 2px;
	}
	#profile ul.profile-nav li:first-child { border-radius:  4px 0 0 0; }
	#profile ul.profile-nav li:last-child { border-radius: 0 0 0 4px; }

	#profile ul.profile-nav li:hover {
		background-color: #f5f5f5;
	}
	#profile ul.profile-nav li a {
		display: block;
		margin: 0 auto;
		padding: 5px;
	}
	#profile ul.profile-nav li a.active {
		text-decoration: underline;
	}

	#profile #profile-address-list div.adr {
		padding: 5px;
		margin: 4px 1%;
		position: relative;
		border: 1px solid #e6e6fa;
		border-radius: 8px 0 8px 8px;
		width: 46%;
		float: left;
	}
	#profile div.adr a.delete-lnk {
		position: absolute;
		top: 2px;
		right: 2px;
	}
	#profile td.shipping-data p {
		margin: 5px 0;
	}
</style>