<div id="customer-groups-config-block" class="seotoaster container">
    <div id="customer-groups-config-block-part"></div>
    <input type="hidden" id="customer-groups-tab-config-token" name="secureToken"
           value="<?php echo Tools_System_Tools::initSecureToken(Shopping::SHOPPING_SECURE_TOKEN); ?>"/>
</div>
<input id="system-language-customer-groups-config" type="hidden" name="system-language" value="<?php echo Tools_Misc::getJsTranslationLanguage();?>"/>
<script>
    $(function () {
        $.getScript('<?php echo $this->websiteUrl . "plugins/shopping/web/js/vue-modules/customergroupsmodules/customergroupsconfig.js"?>', function(result){});
    });
</script>
