<?php echo $this->doctype(); ?>
<html>
    <head>
	    <?php
            $this->headMeta()->setCharset('UTF-8');
            $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')->appendHttpEquiv('Content-Language', $this->translate()->getLocale());

            echo $this->headMeta();

            echo $this->headTitle();

            $this->headLink()
                ->prependStylesheet($this->websiteUrl . 'plugins/shopping/web/css/store.css')
                ->prependStylesheet($this->websiteUrl . 'system/css/seotoaster-plugins.css', 'screen', 'IE')
                ->prependStylesheet($this->websiteUrl . 'system/css/seotoaster-lite.css', 'screen', 'IE')
                ->prependStylesheet($this->websiteUrl . 'system/css/seotoaster-ui.css', 'screen', 'IE')
                ->prependStylesheet($this->websiteUrl . 'system/css/seotoaster.css')
                ->prependStylesheet($this->websiteUrl . 'system/css/reset.css');
            echo $this->headLink();

            echo $this->headStyle();

            $this->jQuery()->enable();
            $this->jQuery()->uiEnable();

            $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/external/jquery/plugins/tmpl/jquery.tmpl.min.js')->addJavascriptFile($this->websiteUrl . 'system/js/external/smoke/smoke.min.js')->addJavascriptFile($this->websiteUrl . 'system/js/external/jquery/plugins/cookie/jquery.cookie.js')->addJavascriptFile($this->websiteUrl . 'system/js/internal/system.js');

            echo $this->jQuery();

            $this->headScript()->setAllowArbitraryAttributes(true);
            echo $this->headScript();
        ?>

    </head>

    <body>
        <noscript style="width: 100%; height: 100%; position: fixed; display: block; background: white; font-size: 150%; text-align: center; padding-top: 30%;">
        JavaScript must be enabled at this point.<br/>
        <a href="http://www.seotoaster.com/">seotoaster.com</a>
        </noscript>
        <?php echo $this->formHidden('website_url', $this->websiteUrl); ?>
        <div class="seotoaster container">
        <?php $headerContent = $this->placeholder('headerContent')->toString(); ?>
            <?php if (!empty($headerContent)): ?>
            <div class="header">
        <?php endif; ?>
                <div class="closebutton">
                    <?php echo $this->toasterHelp($this->layout()->sectionId, Tools_Misc::$_helpHashMap) ?>
                    <a class="close icon-close btn link icon inverse-error" href="javascript:;" title="<?php echo $this->translate('Close'); ?>"></a>
                </div>
                <?php echo $headerContent; ?>
                <?php if (!empty($headerContent)): ?>
            </div>
        <?php endif; ?>
            <?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>