<?php
$this->headTitle($this->translate('Merchandising'));
$this->placeholder('headerContent')->set('Merchandising');

$this->headLink()->appendStylesheet($this->websiteUrl.'system/css/reset-widgets.css');
$this->jQuery()->addJavascriptFile($this->websiteUrl.'plugins/shopping/web/js/libs/jquery/jquery.select-chain.js');
?>


<div id="merchandising" class="grid_12 mb10px h500">
    <ul>
        <li><a href="#coupons"><?php echo $this->translate('Coupons');?></a></li>
	</ul>
	<div id="coupons">
		<p><?php echo $this->translate('Set parameters for promotional coupons applicable to the entire cart from this screen.');?></p>
		<p><?php echo $this->translate('Product specific coupons can be found under the "add/edit product" screen. Set cart level coupons from this screen');?></p>
		<br>
		<?php echo $this->partial('merchandising/coupon.phtml'); ?>
	</div>
</div>

<script>
$(function(){
	$('#merchandising').tabs();
});
</script>

<script src="<?php echo $this->websiteUrl;?>plugins/shopping/web/js/libs/require.min.js"
        data-main="<?php echo $this->websiteUrl;?>plugins/shopping/web/js/modules/merchandising/config"></script>

<?php echo $this->partial('merchandising/_actionTemplate.phtml', array('currency' => $this->currency)); ?>