<?php
$this->headScript()
    ->appendFile($this->websiteUrl.'plugins/shopping/web/js/libs/jquery/jquery.select-chain.js')
    ->appendFile($this->websiteUrl . 'plugins/shopping/web/js/libs/require.min.js',
        null,
        array('data-main' => $this->websiteUrl . 'plugins/shopping/web/js/modules/merchandising/config')
    );

$this->headLink()
    ->appendStylesheet($this->websiteUrl . 'plugins/shopping/web/css/store.css');
?>


<?php echo $this->partial('merchandising/_actionTemplate.phtml', array('currency' => $this->currency)); ?>
<div id="merchandising" class="seotoaster container">
<?php
    echo $this->partial(
        'admin' . DIRECTORY_SEPARATOR . '_header.phtml',
        array(
            'helpSection' => $this->helpSection,
            'hashMap'     => Tools_Misc::$_helpHashMap
        )
    );
?>
    <div class="with-content-footer">
        <div class="tabs-nav-wrap">
            <span class="arrow left ticon-arrow-left3"></span>
            <span class="arrow right ticon-arrow-right3"></span>
            <ul class="header">
                <?php foreach ($this->configTabs as $configTab) :?>
                    <?php if ($configTab['type'] === 'internal') :?>
                        <li><a href="#<?php echo $configTab['tabId'];?>"><?php echo $this->translate($configTab['tabName']);?></a></li>
                    <?php else :?>
                        <li><a href="<?php echo $this->websiteUrl; ?>plugin/<?php echo $configTab['tabId'];?>/run/merchandising/""><?php echo $this->translate($configTab['tabName']);?></a></li>
                    <?php endif;?>
                <?php endforeach;?>
            </ul>
        </div>
        <div id="coupons">
            <?php echo $this->partial('merchandising/coupon.phtml'); ?>
        </div>
        <div id="group-pricing">
            <?php echo $this->partial('merchandising/grouping.phtml', array('defaultGroupId'=> $this->defaultGroupId)); ?>
        </div>
        <div id="recurring-payments">
            <?php echo $this->partial('merchandising/recurring.phtml'); ?>
        </div>
        <div id="user-attributes-assignment-rules">
            <?php echo $this->partial('merchandising/assign-user-group-rules-config.phtml', array('websiteUrl' => $this->websiteUrl)); ?>
        </div>
        <div class="message info grid_12">
            <ul class="list-count-sign column_2 full-width">
                <li class="m0px text-overflow"><?php echo $this->translate('Set parameters for cart wide promotions from this screen.'); ?></li>
                <li class="m0px text-overflow"><?php echo $this->translate('Set item specific promotions in the "add/edit product" screen.'); ?></li>
            </ul>
        </div>
    </div>
</div>

<script>
    $(function () {
        $('#merchandising').tabs({
            beforeLoad: function(event, ui){
                showSpinner('#merchandising');
            }
        });
    });
</script>