<?php
$this->jQuery()->addJavascriptFile($this->websiteUrl.'system/js/external/plupload/plupload.js');
$this->jQuery()->addJavascriptFile($this->websiteUrl.'system/js/external/plupload/plupload.html5.js');
$this->jQuery()->addJavascriptFile($this->websiteUrl.'system/js/external/plupload/plupload.html4.js');
$this->jQuery()->addJavascriptFile($this->websiteUrl.'system/js/external/plupload/plupload.flash.js');
$title = $this->translate('Import orders');
$this->headTitle($title);
$this->placeholder('headerContent')->set($title);
?>

<div id="uplodContainer" class="content-auto text-center pt10px pb10px">
    <button id="pickOrders"><?php echo $this->translator->translate('Upload orders csv');?></button>
</div>

<script type="text/javascript" charset="utf-8">
    $(function() {
        var uploader = new plupload.Uploader({
            runtimes : 'html5,flash,html4',
            browse_button : 'pickOrders',
            container : 'uplodContainer',
            max_file_size : '100mb',
            url : '<?php echo $this->websiteUrl?>plugin/shopping/run/importOrders/',
            filters : [
                {title : "Zip files", extensions : "csv"}
            ],
            init : {
                FilesAdded: function(up, files) {
                    showSpinner();
                    up.start();
                }
            }
        });
        uploader.init();
        uploader.bind('FileUploaded', function(up, file, info) {
            hideSpinner();
            if(info.response.error == '0'){
                showMessage(info.response.reason, false, '5000');
            }else{
                showMessage(info.response.reason, true, '5000');
            }
        });
    });
</script>




			