<?php $countryList = Tools_Geo::getCountries(true); ?>
<div class="seotoaster container">
    <?php echo $this->partial(
        'admin' . DIRECTORY_SEPARATOR . '_header.phtml',
        array(
            'headerText' => $this->translate('Order #').' '. $this->order->getId()
        )
    ); ?>
    <div class="content scroll">
        <div id="order-view" class="toaster-widget clearfix">
            <div class="grid_12 mb20px">
                <div class="title"><?php echo $this->translate('Summary');?></div>
                <div><?php echo $this->translate("Placed on").' '.date('d M, Y', strtotime($this->order->getCreatedAt()));?></div>
                <div><?php echo $this->translate("Placed from IP").' '. $this->order->getIpAddress();?></div>
            </div>

            <div class="grid_6">
                <div class="title"><?php echo $this->translate('Billing Address');?> <!--span>[edit]</span--></div>
                <div class="adr">
                    <?php if (null !== ($billingAddressId = $this->order->getBillingAddressId())): ?>
                        <?php $billingAddress = Tools_ShoppingCart::getAddressById($billingAddressId); ?>
                        <?php if(isset($billingAddress['company']) && $billingAddress['company'] != ''):?>
                            <span><?php echo $billingAddress['company'];?></span><br />
                        <?php endif;?>
                        <span class="first-name"><?php echo $billingAddress['firstname'];?></span>
                        <span class="last-name"><?php echo $billingAddress['lastname'];?></span><br />
                        <?php echo $this->formHidden('id', $billingAddress['id'], array('id' => 'id_' . $billingAddress['id'])); ?>
                        <?php echo $this->formHidden('type', $billingAddress['address_type'], array('id' => 'type_' . $billingAddress['id'])); ?>
                        <span class="street-address"><?php echo $billingAddress['address1'] . ' ' . $billingAddress['address2'];?></span>
                        <br/>
                        <span class="locality"><?php
                            echo $billingAddress['city'] .
                                    ($billingAddress['city'] && ($billingAddress['state'] || $billingAddress['zip']) ? ',' : '');
                            ?></span>
                        <span class="region"><?php $state = Tools_Geo::getStateById($billingAddress['state']); echo $state['state']; ?></span>
                        <span class="postal-code"><?php echo $billingAddress['zip'];?></span>
                        <br/>
                        <span><?php echo $countryList[$billingAddress['country']];?></span>
                        <span class="phone"><?php echo $billingAddress['phone'];?></span>
                        <?php if ($this->order->getGateway()) : ?>
                            <br/>
                            <span><?php echo $this->translate('Payment Method');?>
                                : <?php echo $this->order->getGateway() ;?></span>
                        <?php endif; ?>
                    <?php else: ?>
                        <p><?php echo $this->translate('not provided');?></p>
                    <?php endif;?>
                </div>
            </div>

            <div class="grid_6">
                <div class="title"><?php echo $this->translate('Shipping Address');?> <!--span>[edit]</span--></div>
                <div class="adr">
                    <?php if (null !== ($shippingAddressId = $this->order->getShippingAddressId())): ?>
                        <?php $shippingAddress = Tools_ShoppingCart::getAddressById($shippingAddressId); ?>
                        <?php if(isset($shippingAddress['company']) && $shippingAddress['company'] != ''):?>
                            <span class="company"><?php echo $shippingAddress['company'];?></span><br />
                        <?php endif;?>
                        <span class="first-name"><?php echo $shippingAddress['firstname'];?></span>
                        <span class="last-name"><?php echo $shippingAddress['lastname'];?></span>
                        <br/>
                        <?php if ($this->order->getShippingService() === Shopping::SHIPPING_PICKUP && !$this->defaultPickup): ?>
                            <span class="phone"><?php echo $shippingAddress['phone'];?></span>
                            <br/>
                            <span class="phone"><?php echo $shippingAddress['mobile'];?></span>
                        <?php else:?>
                            <span class="street-address"><?php echo $shippingAddress['address1'] . ' ' . $shippingAddress['address2'];?></span>
                            <br/>
                            <span class="locality"><?php
                                echo $shippingAddress['city'] .
                                        ($shippingAddress['city'] && ($shippingAddress['state'] || $shippingAddress['zip']) ? ',' : '');
                                ?></span>
                            <span class="region"><?php $state = Tools_Geo::getStateById($shippingAddress['state']); echo $state['state']; ?></span>
                            <span class="postal-code"><?php echo $shippingAddress['zip'];?></span>
                            <br/>
                            <span><?php echo $countryList[$shippingAddress['country']];?></span>
                            <span class="phone"><?php echo $shippingAddress['phone'];?></span>
                        <?php endif;?>
                    <?php else: ?>
                        <p><?php echo $this->translate('not provided');?></p>
                    <?php endif;?>
                </div>
            </div>
            <div class="grid_12 mt10px">
                <?php if ($this->order->getShippingService() === Shopping::SHIPPING_PICKUP && !$this->defaultPickup): ?>
                    <div class="pickup-location-info">
                        <div class="title"><?php echo $this->translate('Location info'); ?>:</div>
                        <span
                            class="location-name"><?php echo $this->pickupLocationData['name']; ?></span><br/>
                        <span
                            class="street-address"><?php echo $shippingAddress['address1'] . ' ' . $shippingAddress['address2']; ?></span>
                        <br/>
                            <span class="locality"><?php
                                echo $shippingAddress['city'] .
                                    ($shippingAddress['city'] && ($shippingAddress['state'] || $shippingAddress['zip']) ? ',' : '');
                                ?></span>
                        <span class="region"><?php $state = Tools_Geo::getStateById($shippingAddress['state']);
                            echo $state['state']; ?></span>
                        <span class="postal-code"><?php echo $shippingAddress['zip']; ?></span>
                        <br/>
                        <span><?php echo $countryList[$shippingAddress['country']]; ?></span>
                        <span
                            class="location-phone"><?php echo $this->pickupLocationData['phone']; ?></span><br/>
                        <?php $pickupWorkingHours = unserialize($this->pickupLocationData['working_hours']); ?>
                        <div class="location-working-hours">
                            <?php echo $this->translate('Sunday'); ?>:
                            <span><?php echo ($pickupWorkingHours['sunday'] === '') ? $this->translate(
                                    'not provided'
                                ) : $pickupWorkingHours['sunday']; ?></span>
                            <?php echo $this->translate('Monday'); ?>:
                            <span><?php echo ($pickupWorkingHours['monday'] === '') ? $this->translate(
                                    'not provided'
                                ) : $pickupWorkingHours['monday']; ?></span>
                            <?php echo $this->translate('Tuesday'); ?>:
                            <span><?php echo ($pickupWorkingHours['tuesday'] === '') ? $this->translate(
                                    'not provided'
                                ) : $pickupWorkingHours['tuesday']; ?></span>
                            <?php echo $this->translate('Wednesday'); ?>:
                            <span><?php echo ($pickupWorkingHours['wednesday'] === '') ? $this->translate(
                                    'not provided'
                                ) : $pickupWorkingHours['wednesday']; ?></span>
                            <?php echo $this->translate('Thursday'); ?>:
                            <span><?php echo ($pickupWorkingHours['thursday'] === '') ? $this->translate(
                                    'not provided'
                                ) : $pickupWorkingHours['thursday']; ?></span>
                            <?php echo $this->translate('Friday'); ?>:
                            <span><?php echo ($pickupWorkingHours['friday'] === '') ? $this->translate(
                                    'not provided'
                                ) : $pickupWorkingHours['friday']; ?></span>
                            <?php echo $this->translate('Saturday'); ?>:
                            <span><?php echo ($pickupWorkingHours['saturday'] === '') ? $this->translate(
                                    'not provided'
                                ) : $pickupWorkingHours['saturday']; ?></span>
                        </div>
                    </div>
                <?php endif; ?>
            </div>

            <div class="grid_12 mt20px mb20px">
                <div class="title"><?php echo $this->translate("Order #%1\$s content", $this->order->getId());?></div>
                <table style="width: 100%">
                    <thead>
                    <tr>
                        <th><?php echo $this->translate('Product');?></th>
                        <th class="text-center"><?php echo $this->translate('Mpn');?></th>
                        <?php
                        $colSpan = 0;
                        if (Tools_Security_Acl::isAllowed(Shopping::RESOURCE_STORE_MANAGEMENT)):?>
                            <?php $colSpan = 1; ?>
                            <th class="text-center"><?php echo $this->translate('Original Price'); ?></th>
                        <?php endif;?>
                        <th class="text-center"><?php echo $this->translate('Price'); ?></th>
                        <th class="text-center"><?php echo $this->translate('Qty'); ?></th>
                        <th class="text-center"><?php echo $this->translate('Subtotal'); ?></th>
                        <th class="text-center"><?php echo $this->translate('Tax'); ?></th>
                        <th class="text-center"><?php echo $this->translate('Total'); ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $cartContent = $this->order->getCartContent(); ?>
                    <?php $productMapper = Models_Mapper_ProductMapper::getInstance();?>
                    <?php if (!empty($cartContent)): ?>
                        <?php foreach ($cartContent as $item) : ?>
                            <?php $product = $productMapper->find($item['product_id']); ?>
                            <tr>
                                <td><b><?php echo $item['name'];?></b>
                                    <br/>
                                    <?php $photo = $product->getPhoto();?>
                                    <?php if (isset($photo) && $photo != ''): ?>
                                        <?php $productPageUrl = $this->websiteUrl;?>
                                        <?php if($product->getPage() instanceof Application_Model_Models_Page):?>
                                           <?php $productPageUrl .=  $product->getPage()->getUrl();?>
                                        <?php endif;?>
                                        <a class="page-teaser-image"
                                           href="<?php echo $productPageUrl; ?>"
                                           title="<?php echo $product->getName(); ?>" target="_blank">
                                            <img style="width:80px; vertical-align:middle"
                                                 src="<?php echo Tools_Misc::prepareProductImage($product->getPhoto()); ?>"
                                                 alt="<?php echo $product->getName(); ?>"/>
                                        </a>
                                    <?php else: ?>
                                        <img style="width:80px;"
                                             src="<?php echo $this->websiteUrl; ?>system/images/noimage.png"
                                             alt="<?php echo $product->getName(); ?>"/>
                                    <?php endif;?>
                                    <br/><?php echo $this->translate('SKU');?>: <?php echo $item['sku'];?>
                                    <?php if (!empty($item['options'])): ?>
                                        <?php $item['taxRate'] = Tools_Tax_Tax::calculateProductTax($product, null, true);?>
                                        <?php foreach ($item['options'] as $optionTitle => $optData): ?>
                                            <?php
                                            if (is_array($optData)) {
                                                $optionStr = '<span>'.$optionTitle. ':</span> <span>'.$optData['title'].'</span> ';
                                                if (!empty($optData['priceValue']) && intval($optData['priceValue'])) {
                                                    if ((bool)$item['taxRate'] && $this->showPriceIncTax == 1){
                                                        $optPriceMod = $optData['priceValue'] * (100 + $item['taxRate'])/100;
                                                    } else {
                                                        $optPriceMod = $optData['priceValue'];
                                                    }
                                                    if ($optData['priceType'] === 'percent') {
                                                        $optionStr .= '<span>(' . $optData['priceSign'] . '%'. number_format($optPriceMod, 2) .')</span>';
                                                    } else {
                                                        $optionStr .= '<span>(' . $optData['priceSign'] . $this->currency($optPriceMod) .')</span>';
                                                    }
                                                }
                                                if (!empty($optData['weightValue']) && intval($optData['weightValue'])) {
                                                    $optionStr .= '<span>(' . $optData['weightSign'] .' '. $optData['weightValue'] .' '. $this->weightSign . ')</span>' ;
                                                }
                                            } else {
                                                $optionStr = $optionTitle . ': ' . $optData;
                                            } ?>
                                            <div class="options"><?php echo $optionStr; ?></div>
                                        <?php endforeach; ?>
                                <?php endif;?>
                                </td>
                                <td class="text-center"><?php echo $product->getMpn();?></td>
                                <?php if (Tools_Security_Acl::isAllowed(Shopping::RESOURCE_STORE_MANAGEMENT)):?>
                                    <td class="text-center"><?php echo $this->currency($item['original_price']);?></td>
                                <?php endif;?>
                                <td class="text-center">
                                <?php if($item['freebies'] == 1):?>
                                    <?php echo $this->translate('free');?>
                                <?php else:?>
                                    <?php echo $this->currency($item['price']);?>
                                <?php endif;?>
                                </td>
                                <td class="text-center"><?php echo $item['qty'];?></td>
                                <?php if($item['freebies'] == 1):?>
                                    <td class="text-center"><?php echo $this->translate('free');?></td>
                                    <td class="text-center"><?php echo $this->translate('free');?></td>
                                    <td class="text-center"><?php echo $this->translate('free');?></td>
                                <?php else:?>
                                    <td class="text-center"><?php echo $this->currency($item['qty'] * $item['price']);?></td>
                                    <td class="text-center"><?php echo $this->currency($item['qty'] * $item['tax']);?></td>
                                    <td class="text-center"><?php echo $this->currency($item['qty'] * $item['tax_price']);?></td>
                                <?php endif;?>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    </tbody>
                    <tfoot>
                    <tr><td colspan="<?php echo $colSpan + 7 ?>"></td></tr>
                    <tr>
                        <td colspan="<?php echo $colSpan + 7 ?>">
                            <?php echo $this->translate('Delivery comments');?>:
                            <p class="order-notes text-normal"><?php echo nl2br($this->order->getNotes());?></p>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="<?php echo $colSpan + 5 ?>" rowspan="7"></td>
                        <td><?php echo $this->translate('Subtotal');?>:</td>
                        <?php if ($this->showPriceIncTax == 1): ?>
                            <td class="text-right"><?php echo $this->currency($this->order->getSubTotal() + $this->order->getSubTotalTax());?></td>
                        <?php else:?>
                            <td class="text-right"><?php echo $this->currency($this->order->getSubTotal());?></td>
                        <?php endif;?>
                    </tr>
                    <?php if ($this->order->getDiscount() > 0): ?>
                        <tr>
                            <td><?php echo $this->translate('Discount');?>:</td>
                            <?php if ($this->showPriceIncTax == 1): ?>
                                <td class="text-right"><?php echo $this->currency($this->order->getDiscount() + $this->order->getDiscountTax());?></td>
                            <?php else: ?>
                                <td class="text-right"><?php echo $this->currency($this->order->getDiscount());?></td>
                            <?php endif;?>
                        </tr>
                    <?php endif; ?>
                    <tr>
                        <td><?php echo $this->translate('Shipping');?>:</td>
                        <?php if ($this->showPriceIncTax == 1): ?>
                            <td class="text-right"><?php echo $this->order->getShippingPrice() === null ? $this->currency(0) : $this->currency($this->order->getShippingPrice() + $this->order->getShippingTax());?></td>
                        <?php else:?>
                            <td class="text-right"><?php echo $this->order->getShippingPrice() === null ? $this->currency(0) : $this->currency($this->order->getShippingPrice());?></td>
                        <?php endif;?>
                    </tr>
                    <?php if ($this->order->getShippingService()) : ?>
                        <tr>
                            <td><?php echo $this->translate('Shipping service');?>:</td>
                            <td class="text-right"><?php echo strtoupper($this->order->getShippingService()) ;?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if ($this->order->getShippingType()) : ?>
                        <tr>
                            <td><?php echo $this->translate('Shipping type');?>:</td>
                            <td class="text-right"><?php echo $this->order->getShippingType();?></td>
                        </tr>
                    <?php endif; ?>
                    <tr>
                        <?php if (Tools_Misc::getTaxName() != ''): ?>
                            <?php $taxName = Tools_Misc::getTaxName(); ?>
                        <?php else: ?>
                            <?php $taxName = 'Tax'; ?>
                        <?php endif;?>
                        <?php if ($this->showPriceIncTax == 1): ?>
                            <td><?php echo $this->translate('Inc. ' . $taxName);?>:</td>
                        <?php else: ?>
                            <td><?php echo $this->translate('Total ' . $taxName);?>:</td>
                        <?php endif;?>
                        <td class="text-right"><?php echo $this->currency($this->order->getTotalTax());?></td>
                    </tr>
                    <?php if ($this->order->getRefundAmount() > 0): ?>
                        <tr>
                            <td><?php echo $this->translate('Refund');?>:</td>
                            <td class="text-right"><?php echo $this->currency($this->order->getRefundAmount());?></td>
                        </tr>
                    <?php endif; ?>
                    <tr>
                        <td><?php echo $this->translate('Grand Total');?>:</td>
                        <td class="text-right"><?php echo $this->currency($this->order->getTotal());?></td>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
<style>
	.title{
        color         : #666;
        font-weight   : bold;
        border-bottom : 1px dashed #ddd;
        margin        : 0 0 10px;
    }

    .adr{
        padding : 0 10px;
    }

    table thead tr{
        background-color : #666666;
        color            : #eee;
    }

    table td, table th{
        padding : 4px 6px;
    }

    table tbody td{
        vertical-align : middle;
        border-bottom  : 1px solid #d3d3d3;
    }

    table tfoot td{
        font-weight : bold;
        color       : #777;
    }

    table tfoot td[rowspan="3"]{
        border-right : 1px solid #d3d3d3;
    }
</style>
