<?php $this->placeholder('headerContent')->set($this->translate('Order #').' '. $this->order->getId()); ?>
<?php $countryList = Tools_Geo::getCountries(true); ?>
<div class="h550" style="overflow-y: auto;">
	<div id="order-view" class="toaster-widget clearfix">
		<div class="grid_12">
			<div class="title padding5px"><?php echo $this->translate('Summary');?></div>
			<div><?php echo $this->translate("Placed on").' '.date('d M, Y', strtotime($this->order->getCreatedAt()));?></div>
			<div><?php echo $this->translate("Placed from IP").' '. $this->order->getIpAddress();?></div>
		</div>

		<div class="mt10px">&nbsp;</div>

		<div class="grid_6">
			<div class="title padding5px"><?php echo $this->translate('Billing Address');?> <!--span>[edit]</span--></div>
			<div class="adr">
				<?php if (null !== ($billingAddressId = $this->order->getBillingAddressId())): ?>
					<?php $billingAddress = Tools_ShoppingCart::getAddressById($billingAddressId); ?>
					<?php echo $this->formHidden('id', $billingAddress['id'], array('id' => 'id_' . $billingAddress['id'])); ?>
					<?php echo $this->formHidden('type', $billingAddress['address_type'], array('id' => 'type_' . $billingAddress['id'])); ?>
					<span class="street-address"><?php echo $billingAddress['address1'] . ' ' . $billingAddress['address2'];?></span>
					<br/>
					<span class="locality"><?php
						echo $billingAddress['city'] .
								($billingAddress['city'] && ($billingAddress['state'] || $billingAddress['zip']) ? ',' : '');
						?></span>
					<span class="region"><?php $state = Tools_Geo::getStateById($billingAddress['state']); echo $state['state']; ?></span>
					<span class="postal-code"><?php echo $billingAddress['zip'];?></span>
					<br/>
					<span><?php echo $countryList[$billingAddress['country']];?></span>
					<span class="phone"><?php echo $billingAddress['phone'];?></span>
				<?php else: ?>
					<p><?php echo $this->translate('not provided');?></p>
				<?php endif;?>
			</div>
		</div>

		<div class="grid_6">
			<div class="title padding5px"><?php echo $this->translate('Shipping Address');?> <!--span>[edit]</span--></div>
			<div class="adr">
				<?php if (null !== ($shippingAddressId = $this->order->getShippingAddressId())): ?>
					<?php $shippingAddress = Tools_ShoppingCart::getAddressById($shippingAddressId); ?>
					<span><?php echo $shippingAddress['firstname'];?></span>
					<span><?php echo $shippingAddress['lastname'];?></span>
					<br/>
					<span class="street-address"><?php echo $shippingAddress['address1'] . ' ' . $shippingAddress['address2'];?></span>
					<br/>
					<span class="locality"><?php
						echo $shippingAddress['city'] .
								($shippingAddress['city'] && ($shippingAddress['state'] || $shippingAddress['zip']) ? ',' : '');
						?></span>
					<span class="region"><?php $state = Tools_Geo::getStateById($shippingAddress['state']); echo $state['state']; ?></span>
					<span class="postal-code"><?php echo $shippingAddress['zip'];?></span>
					<br/>
					<span><?php echo $countryList[$shippingAddress['country']];?></span>
					<span class="phone"><?php echo $shippingAddress['phone'];?></span>
				<?php else: ?>
					<p><?php echo $this->translate('not provided');?></p>
				<?php endif;?>
			</div>
		</div>

		<div class="grid_12 mt20px mb20px">
			<div class="title padding5px"><?php echo $this->translate("Order #%1\$s content", $this->order->getId());?></div>
			<table style="width: 100%">
				<thead>
				<tr>
					<th><?php echo $this->translate('Product');?></th>
					<th><?php echo $this->translate('Mpn');?></th>
                    <?php if (Tools_Security_Acl::isAllowed(Shopping::RESOURCE_STORE_MANAGEMENT)):?>
					    <th><?php echo $this->translate('Original Price'); ?></th>
                    <?php endif;?>
					<th><?php echo $this->translate('Price'); ?></th>
					<th><?php echo $this->translate('Qty'); ?></th>
					<th><?php echo $this->translate('Subtotal'); ?></th>
					<th><?php echo $this->translate('Tax'); ?></th>
					<th><?php echo $this->translate('Total'); ?></th>
				</tr>
				</thead>
				<tbody>
				<?php $cartContent = $this->order->getCartContent(); ?>
				<?php $productMapper = Models_Mapper_ProductMapper::getInstance();?>
				<?php if (!empty($cartContent)): ?>
					<?php foreach ($cartContent as $item) : ?>
						<?php $product = $productMapper->find($item['product_id']); ?>
						<tr>
							<td><b><?php echo $item['name'];?></b>
								<br/>
								<?php $photo = $product->getPhoto();?>
								<?php if (isset($photo) && $photo != ''): ?>
									<a class="page-teaser-image"
									   href="<?php echo $this->websiteUrl . $product->getPage()->getUrl(); ?>"
									   title="<?php echo $product->getName(); ?>" target="_blank">
										<img style="width:80px; vertical-align:middle"
										     src="<?php echo Tools_Misc::prepareProductImage($product->getPhoto()); ?>"
										     alt="<?php echo $product->getName(); ?>"/>
									</a>
								<?php else: ?>
									<img style="width:80px;"
									     src="<?php echo $this->websiteUrl; ?>system/images/noimage.png"
									     alt="<?php echo $product->getName(); ?>"/>
								<?php endif;?>
								<br/><?php echo $this->translate('SKU');?>: <?php echo $item['sku'];?></td>
							<td class="textcentered"><?php echo $product->getMpn();?></td>
                            <?php if (Tools_Security_Acl::isAllowed(Shopping::RESOURCE_STORE_MANAGEMENT)):?>
							    <td class="textcentered"><?php echo $this->currency($item['original_price']);?></td>
                            <?php endif;?>
                            <td class="textcentered">
                            <?php if($item['freebies'] == 1):?>
							    <?php echo $this->translate('free');?>
                            <?php else:?>
                                <?php echo $this->currency($item['price']);?>
                            <?php endif;?>
                            </td>
							<td class="textcentered"><?php echo $item['qty'];?></td>
                            <?php if($item['freebies'] == 1):?>
                                <td class="textcentered"><?php echo $this->translate('free');?></td>
                                <td class="textcentered"><?php echo $this->translate('free');?></td>
                                <td class="textcentered"><?php echo $this->translate('free');?></td>
                            <?php else:?>
                                <td class="textcentered"><?php echo $this->currency($item['qty'] * $item['price']);?></td>
                                <td class="textcentered"><?php echo $this->currency($item['qty'] * $item['tax']);?></td>
                                <td class="textcentered"><?php echo $this->currency($item['qty'] * $item['tax_price']);?></td>
                            <?php endif;?>
						</tr>
					<?php endforeach; ?>
				<?php endif; ?>
				</tbody>
				<tfoot>
				<tr>
					<td class="floatLeft"><?php echo $this->translate('Delivery comments');?>:</td>
					<td class="floatLeft"><span class="order-notes"><?php echo $this->order->getNotes();?></span></td>
					<td colspan="4"></td>
					<td class="text-right"><?php echo $this->translate('Subtotal');?>:</td>
					<td><?php echo $this->currency($this->order->getSubTotal());?></td>
				</tr>
				<tr>
					<td colspan="5"></td>
					<td class="text-right"><?php echo $this->translate('Shipping');?>:</td>
					<td><?php echo $this->order->getShippingPrice() === null ? $this->currency(0) : $this->currency($this->order->getShippingPrice());?></td>
				</tr>
                <tr>
                    <td colspan="5"></td>
                    <?php if (Tools_Misc::getTaxName() != ''): ?>
                        <?php $taxName = Tools_Misc::getTaxName(); ?>
                    <?php else: ?>
                        <?php $taxName = 'Tax'; ?>
                    <?php endif;?>
                    <?php if ($this->showPriceIncTax == 1): ?>
                        <td class="text-right"><?php echo $this->translate('Inc. ' . $taxName);?>:</td>
                    <?php else: ?>
                        <td class="text-right"><?php echo $this->translate('Total ' . $taxName);?>:</td>
                    <?php endif;?>
                    <td><?php echo $this->currency($this->order->getTotalTax());?></td>
                </tr>
				<?php if ($this->order->getDiscount() > 0): ?>
					<tr>
						<td colspan="5"></td>
						<td class="text-right"><?php echo $this->translate('Discount');?>:</td>
						<td><?php echo $this->currency($this->order->getDiscount());?></td>
					</tr>
				<?php endif; ?>
				<tr>
					<td colspan="5"></td>
					<td class="text-right"><?php echo $this->translate('Grand Total');?>:</td>
					<td><?php echo $this->currency($this->order->getTotal());?></td>
				</tr>
				</tfoot>
			</table>
		</div>
	</div>
</div>
<style>
	.seotoaster {
		background-color: #ffffff;
	}

	.title {
		color: #666;
		font-weight: bold;
		border-bottom: 1px dashed #ddd;
		margin: 10px 0;
	}

	#order-view {
		width: 900px;
		margin: 0 auto;
	}

	.adr {
		padding: 0 10px;
	}

	table thead tr {
		background-color: #666666;
		color: #eee;
		text-shadow: 0 0 2px #333;
	}

	table td, table th {
		padding: 4px 6px;
	}

	table tbody td {
		vertical-align: middle;
		border-bottom: 1px solid #d3d3d3;
	}

	table tfoot td {
		font-weight: bold;
		font-size: 14px;
		color: #777;
	}

	table tfoot td.text-right {
		text-align: right;
	}

	table tfoot td.floatLeft {
		float: left;
	}
</style>
<script>
	$(function () {
		$('#order-view').closest('.seotoaster').addClass('h600');
	});
</script>
