<?php $this->headTitle($this->translate('Manage customers')); ?>
<style>
	#people{
	}
	#people table{
	}
	#people table tr{
	}
	#people table tr.search-line th{
	    padding: 5px 20px 10px;
	    text-align: left;
	}
	#people table tr.search-line th input{
		margin-left:10px;
		width:250px;
	}
	#people table tr.title-table{
		background:#666;
		color:#eee;
	}
	#people table tr.title-table th{
	}
	#people table th, #people table td{
		vertical-align:middle;
		text-align:center;
		padding:5px;
	}
	#people table th{
	}
	#people table td{
	}
	#people table td.full-name, #people table td.email{
		text-align:left;
	}
	#people table td.chek-td{
		border-left:none;
	}
	#people table td.total{
		border-right:none;
	}
	#people table tfoot td, #people table tfoot th{
		border:none;
		padding-top:10px;
	}
	#people table tfoot td:first-child{
		text-align:left;
	}
	#people table tfoot #people-previous{
		margin-right:10px;
	}
	#people #customer-details{
	}
	#people #customer-details .toolbar{
		border-bottom: 2px solid #a9a9a9;
		margin-bottom:10px;
		padding:5px 10px;
	}
	#people #customer-details #profile h3{
		border:none;
	}
	#people #customer-details .profile-actions ul.stats{
		text-align:center;
	}
	#people #customer-details .profile-actions ul.stats li{
		display:inline-block;
		vertical-align:bottom;
		padding-left:15px;
		margin-right:15px;
		border-left:1px dashed #ccc;
	}
	#people #customer-details .profile-actions ul.stats li:first-child{
		border:none;
	}
</style>

<script id="tableRowTemplate" type="text/x-jquery-tmpl">
    <td class="chek-td textcentered"><input type="checkbox" name="select[]" value="${id}" title="Click to mark/unmark ${full_name}" {{if checked}}checked="checked"{{/if}} /></td>
    <td class="full-name"><a href="javascript:;" class="details">${full_name}</a></td>
    <td class="email">${email}&nbsp;<a href="mailto:${email}">&#x2709;</a></td>
    <td class="date">${reg_date}</td>
    <td class="total text-center"><span>{{if total_amount}}${total_amount}{{else}}0{{/if}}</span> (${total_orders})</td>
</script>

<script id="customerDetailsTemplate" type="text/x-jquery-tmpl">
	<h2 class="fn">${fullName}</h2>
	<h3><a href="mailto:${email}" class="email">${email}</a></h3>
	<p>${roleId} since ${regDate}</p>

</script>

<script id="addressTemplate" type="text/x-jquery-tmpl">
	<div class="adr">
		<h3><?php echo $this->translate('Default shipping address');?></h3>
		<span class="street-address">address1 + address2</span>
		<br/>
		<span class="locality">city</span>
		<span class="region">state</span>
		<span class="postal-code">zip</span>
	</div>
</script>

<?php
    $this->headScript()->setAllowArbitraryAttributes(true)
		    ->appendFile($this->websiteUrl . 'system/js/external/jquery/plugins/tmpl/jquery.tmpl.min.js')
			->appendFile($this->websiteUrl.'plugins/shopping/web/js/libs/require/require.js', null, array('data-main' => $this->websiteUrl.'plugins/shopping/web/js/people.js'));

	echo $this->noLayout ? $this->headScript() : '';
?>


<div id="people" class="ui-helper-clearfix">
    <table id="people-table" style="width: 100%">
        <thead>
            <tr class="search-line">
	            <th colspan="5">
	            <?php echo $this->translate('Search');?>&nbsp;<input type="text" id="people-search" name="people-search" placeholder="<?php echo $this->translate('by name or email');?>"/>
                </th>
            </tr>
            <tr class="title-table">
	            <th><?php echo $this->formCheckbox('people-check-all', null, array('title' => 'Check/Uncheck All'));?></th>
	            <th class="sortable" data-sortkey="full_name"><?php echo $this->translate('Full Name');?></th>
	            <th class="sortable" data-sortkey="email"><?php echo $this->translate('Email');?></th>
	            <th class="sortable" data-sortkey="reg_date"><?php echo $this->translate('Registered');?></th>
	            <th class="sortable" data-sortkey="total_amount"><?php echo $this->translate('Total Spend (orders)');?></th>
            </tr>
        </thead>
        <tfoot>
            <tr>
	            <td colspan="3" class="ui-resizable">
		            <?php echo $this->translate('with selected do');?>
					<!-- @todo add some actions -->
		            <select id="mass-action" style="width: 250px">
			            <option value="0"><?php echo $this->translate('nothing');?></option>
			            <option value="deleteSelected"><?php echo $this->translate('delete');?></option>
		            </select>
	            </td>
	            <td>
		            <form id="export-users-form" action="<?php echo $this->websiteUrl;?>backend/backend_user/export/" method="post"><a href="javascript:;" id="export-users"><?php echo $this->translate('export as csv file');?></a></form>
	            </td>
	            <th>
		            <a href="#" id="people-previous" class="table-nav">&#8656;&nbsp;<?php echo $this->translate('previous');?></a>
		            <a href="#" id="people-next" class="table-nav"><?php echo $this->translate('next');?>&nbsp;&#8658;</a>
	            </th>
            </tr>
        </tfoot>
        <tbody id="customer-list">
            <tr>
	            <td colspan="5" class="text-center"><img src="<?php echo $this->websiteUrl;?>/system/images/loading.gif"/></td>
            </tr>
        </tbody>
    </table>

	<div id="customer-details" class="grid_12">
		<div class="toolbar">
			<a href="javascript:;" class="link textcentered">&#8678; back to customer list</a>
		</div>
		<div id="profile">

		</div>
	</div>
</div>
