<?php $this->headTitle($this->translate('Manage customers')) ?>
<style>
	table#people-table {
	    background-color: #efefef;
	}
	table#people-table th.sortable {
		cursor: pointer;
	    white-space: nowrap;
	    color: #3C78A7;
	    text-align: left;
		padding: 5px;
    }
    table#people-table th.sortable::after{
	    color: #5f9ea0;
	    content: " \21D5";
	    display: inline;
    }
    table#people-table th.sortUp::after{
	    content: " \21E7";
    }
    table#people-table th.sortDown::after{
        content: " \21E9";
    }
    table#people-table thead tr{
	    border-bottom: 1px dashed #ccc;
    }
    table#people-table tbody tr:hover td {
	    background-color:  #d3d3d3;
	    color: #3C78A7;
    }
    table#people-table td {
	    padding: 6px 2px;
    }
    table#people-table td.text-center{
	    text-align: center;
    }
    table#people-table tbody tr {
	    background-color: white;
	    border-bottom: 1px dashed #cccccc;
    }
    table#people-table a.table-nav {
	    margin: 10px 2px;
    }
    table#people-table a.table-nav:hover {
	    text-decoration: underline;
    }
</style>

<script id="tableRowTemplate" type="text/x-jquery-tmpl">
    <td class="textcentered"><input type="checkbox" name="select[]" value="${id}" title="Click to mark/unmark ${full_name}" {{if checked}}checked="checked"{{/if}} /></td>
    <td><a href="javascript:;" class="details">${full_name}</a></td>
    <td>${email}</td>
    <td>${reg_date}</td>
    <td class="text-center"><span>{{if total_amount}}${total_amount}{{else}}0{{/if}}</span> (${total_orders})</td>
</script>

<script id="customerDetailsTemplate" type="text/x-jquery-tmpl">
	<h2 class="fn">${fullName}</h2>
	<h3><a href="mailto:${email}" class="email">${email}</a></h3>
	<p>${roleId} since ${regDate}</p>

</script>

<script id="addressTemplate" type="text/x-jquery-tmpl">
	<div class="adr">
		<h3><?php echo $this->translate('Default shipping address');?></h3>
		<span class="street-address">address1 + address2</span>
		<br/>
		<span class="locality">city</span>
		<span class="region">state</span>
		<span class="postal-code">zip</span>
	</div>
</script>

<?php
    $this->headScript()->setAllowArbitraryAttributes(true)
		    ->appendFile($this->websiteUrl . 'system/js/external/jquery/plugins/tmpl/jquery.tmpl.min.js')
			->appendFile($this->websiteUrl.'plugins/shopping/web/js/libs/require/require.js', null, array('data-main' => $this->websiteUrl.'plugins/shopping/web/js/people.js'));

	echo $this->noLayout ? $this->headScript() : '';
?>


<div id="people" class="ui-helper-clearfix">
	<div><?php echo $this->translate('Search');?>&nbsp;<input type="text" id="people-search" name="people-search" placeholder="<?php echo $this->translate('by name or email');?>" style="width: 200px"/></div>
    <table id="people-table" style="width: 100%">
        <thead>
            <tr class="mb10px">
	            <th><?php echo $this->formCheckbox('people-check-all', null, array('title' => 'Check/Uncheck All'));?></th>
	            <th class="sortable" data-sortkey="full_name"><?php echo $this->translate('Full Name');?></th>
	            <th class="sortable" data-sortkey="email"><?php echo $this->translate('Email');?></th>
	            <th class="sortable" data-sortkey="reg_date"><?php echo $this->translate('Registered');?></th>
	            <th class="sortable" data-sortkey="total_amount"><?php echo $this->translate('Total Spend (orders)');?></th>
            </tr>
        </thead>
        <tfoot>
            <tr>
	            <td colspan="4">
		            <?php echo $this->translate('with selected do');?>
					<!-- @todo add some actions -->
		            <select id="mass-action" style="width: 250px">
			            <option value="0"><?php echo $this->translate('nothing');?></option>
			            <option value="deleteSelected"><?php echo $this->translate('delete');?></option>
			            <option value="deleteExport"><?php echo $this->translate('export to csv');?></option>
		            </select>
		            <form id="expusrs" action="<?php echo $this->websiteUrl;?>backend/backend_user/export/" method="post"><a href="javascript:;" id="export-users"><?php echo $this->translate('export as csv file');?></a></form>
	            </td>
	            <th>
		            <a href="#" id="people-previous" class="table-nav">&#8656;&nbsp;<?php echo $this->translate('previous');?></a>
		            <a href="#" id="people-next" class="table-nav"><?php echo $this->translate('next');?>&nbsp;&#8658;</a>
	            </th>
            </tr>
        </tfoot>
        <tbody id="customer-list">
            <tr>
	            <td colspan="5" class="text-center"><img src="<?php echo $this->websiteUrl;?>/system/images/loading.gif"/></td>
            </tr>
        </tbody>
    </table>

	<div id="customer-details">
		<div class="toolbar mb10px" style="border-bottom: 2px solid #a9a9a9;">
			<a href="javascript:;" class="link">&#8678; back to customer list</a>
		</div>
		<div id="profile">

		</div>
	</div>
</div>
