<input type="hidden" id="general-config-token" name="secureToken"
       value="<?php echo Tools_System_Tools::initSecureToken(shopping::SHOPPING_SECURE_TOKEN); ?>"/>
<input id="system-language-general-config" type="hidden" name="system-language" value="<?php echo Tools_Misc::getJsTranslationLanguage();?>"/>
<input id="product-id" type="hidden" name="product-id" value="<?php echo $this->productId;?>"/>
<div id="product-location-config-tab"></div>
<script>
    $(function () {
        $.getScript('<?php echo $this->websiteUrl . "plugins/shopping/web/js/vue-modules/productlocationmodules/productlocationconfig.js"?>', function(result){});
    });
</script>