<?php $this->headTitle('Manage product'); ?>
<?php
$this->headScript()
    ->appendFile($this->websiteUrl.'system/js/external/waypoints/waypoints.min.js')
    ->appendFile($this->websiteUrl.'system/js/external/jquery/plugins/lazyload/jquery.lazyload.min.js')
    ->appendFile($this->websiteUrl.'system/js/external/jquery/plugins/tmpl/jquery.tmpl.min.js')
    ->appendFile($this->websiteUrl . 'plugins/shopping/web/js/libs/require.min.js',
        null,
        array('data-main' => $this->websiteUrl . 'plugins/shopping/web/js/modules/product/config')
    );

$this->headLink()
    ->appendStylesheet($this->websiteUrl . 'plugins/shopping/web/css/store.css');
?>

<?php
    $firstPageCaption = $this->translate('First');
    $lastPageCaption = $this->translate('Last');
?>
<input type="hidden" name="system-language" value="<?php echo Tools_Misc::getJsTranslationLanguage();?>"/>
<?php echo $this->partial('merchandising/_actionTemplate.phtml', array('currency' => $this->generalConfig['currency'])); ?>

<script id="paginatorTemplate" type="text/template">
	<div class="paginator <%= cssClass %>" data-collection="<%= collection %>">
	    <% if (_.isUndefined(pages)) { var pages = 5; } %>
		<% if (firstPage != currentPage) { %><a href="#" class="page" data-page="first"><?php echo $firstPageCaption; ?></a><% } else { %><span><?php echo $firstPageCaption; ?></span><% } %>

        <% if (currentPage > firstPage) { %><a href="#" class="page" data-page="prev"><?php echo $this->translate('Previous'); ?></a><% } %>

        <% if (currentPage - pages > firstPage) { %><span>...</span><% } %>

        <% for (var p = currentPage - pages; p <= currentPage + pages; p++) { %>
            <% if (p < firstPage || p > lastPage) continue; %>
            <% if (currentPage == p) { %>
                <span class="page selected"><%= p %></span>
            <% } else { %>
                <a href="#" class="page" data-page="<%= p %>"><%= p %></a>
            <% } %>
        <% } %>

        <% if (currentPage + pages < lastPage) { %><span>...</span><% } %>

        <% if (currentPage < totalPages) { %><a href="#" class="page" data-page="next"><?php echo $this->translate('Next'); ?></a><% } %>

        <% if (lastPage != currentPage) { %><a href="#" class="page" data-page="last"><?php echo $lastPageCaption; ?></a><% } else { %><span><?php echo $lastPageCaption; ?></span> <% } %>
	</div>
</script>

<script id="imgTemplate" type="text/template">
	<% _.each(images, function (img){ %>
        <div class="box">
			<img class="lazy" src="<%= img.src %>" width="100px" data-name="<%= img.name %>" title="<%= img.name %>"/>
		</div>
    <% }) %>
</script>

<script id="tagTemplate" type="text/template">
	<a href="javascript:;" class="fl-right ml1 mr1 ticon-close error" title="<?php echo $this->translate('Delete'); ?>"></a>
	<label class="fl-left mr-grid">
        <input type="checkbox" name="tag[]" value="<%= tag.get('id') %>"/>
    </label>
    <span class="tag-editable" title="Click to edit"><%= tag.get('name') %></span>
</script>

<script id="optionLibraryTemplate" type="text/template">
	<option value="-1" disabled="disabled" selected="selected">select from library</option>
    <% _.each(items, function (item){ %>
        <option value="<%= item.id %>"><%= item.title %></option>
    <% }); %>
</script>

<script id="optionMainTemplate" type="text/x-jquery-tmpl">
	<div class="grid_4 alpha omega">
        <label class="grid_4 alpha omega mt5px"><?php echo $this->translate('Option name'); ?></label>
        <input class="grid_8 alpha omega option-title" type="text" value="${title}"/>
	</div>
	<div class="grid_4">
        <label class="grid_4 alpha omega text-center mt5px"><?php echo $this->translate('Type'); ?></label>
        <select class="option-type-select grid_8 alpha omega">
            <option value="dropdown"><?php echo $this->translate('Dropdown Box');?></option>
            <option value="radio"><?php echo $this->translate('Radio Switch');?></option>
            <option value="text"><?php echo $this->translate('Text Field');?></option>
            <option value="date"><?php echo $this->translate('Datepicker');?></option>
        </select>
	</div>
	<div class="grid_3 alpha omega text-center">
        {{if id}}
        &nbsp;
        {{else}}
        <label class="block mt5px"><?php echo $this->translate('Add to library?'); ?> <input type="checkbox" title="<?php echo $this->translate('Add to library?'); ?>" name="isTemplate" {{if isTemplate}}checked="checked"{{/if}} /></label>
        <input class="hide" type="text" name="templateName" placeholder="<?php echo $this->translate('Enter label'); ?>"/>
        {{/if}}
	</div>
    <a href="javascript:;" class="fl-right remove-option btn icon link error ticon-close" title="<?php echo $this->translate('Delete option'); ?>"></a>
	<div class="option-content grid_12 alpha omega"></div>
</script>

<script id="optionListTemplate" type="text/x-jquery-tmpl">
	<div class="header-inner mt15px">
		<div class="grid_4"><?php echo $this->translate('Title'); ?></div>
		<div class="grid_3 alpha"><?php echo $this->translate('Price modifier'); ?></div>
		<div class="grid_3"><?php echo $this->translate('Weight modifier'); ?></div>
		<div class="grid_1 alpha omega text-center"><?php echo $this->translate('Default'); ?></div>
		<div class="grid_1"></div>
	</div>
	<div class="option-list-holder grid_12 alpha omega"></div>
	<a class="add-selection-btn grid_12 alpha omega mt20px btn success ticon-plus" href="javascript:;"><?php echo $this->translate('Add new selection');?></a>
</script>

<script id="listItemTemplate" type="text/x-jquery-tmpl">
	<input class="grid_4 alpha" type="text" name="title" data-role="title" value="${title}"/>
	<div class="grid_3 alpha omega">
        <select class="option-modifier-select grid_3 alpha" name="priceModifierSign">
            <option value="+"
            {{if priceSign == '+'}}selected{{/if}} >+</option>
            <option value="-"
            {{if priceSign == '-'}}selected{{/if}} >-</option>
        </select>
        <input class="option-modifier-select grid_5 alpha omega" type="text" name="priceModifierValue" value="${priceValue}" placeholder="0"/>
        <select class="option-modifier-select grid_4 omega" name="priceModifierType">
            <option value="percent"
            {{if priceType == 'percent'}}selected{{/if}} >%</option>
            <option value="unit"
            {{if priceType == 'unit'}}selected{{/if}} ><?php echo $this->generalConfig['currency']; ?></option>
        </select>
    </div>
	<div class="grid_3 omega">
		<select class="option-modifier-select grid_3 alpha omega" name="weightModifierSign">
			<option value="+"
			{{if weightSign == '+'}}selected{{/if}} >+</option>
            <option value="-"
			{{if weightSign == '-'}}selected{{/if}} >-</option>
		</select>
		<input class="option-modifier-select grid_7 omega" name="weightModifierValue" type="text" placeholder="0" value="${weightValue}"/>
		<span class="grid_2 alpha omega text-center mt5px"><?php echo $this->generalConfig['weightUnit']; ?></span>
	</div>
	<label class="grid_1 text-center mt5px">
		<input type="radio" name="isDefault[${_parent}]" value="${title}" {{if isDefault == '1'}}checked="checked"{{/if}} />
	</label>
	<div class="grid_1 text-center">
		<button class="item-remove btn icon link error ticon-remove" title="<?php echo $this->translate('Delete'); ?>"</button>
	</div>
</script>

<script id="productListingTemplate" type="text/x-jquery-tmpl">
	<% if (showDelete) { %>
        <a class="delete ticon-close error small" href="javascript:;" title="<?php echo $this->translate('Delete');?>"></a>
    <% } else { %>
    <a href="<?php echo $this->url(array('id' => null)); ?>/id/<%= id %>" data-role="editProduct" data-pid="<%= id %>" title="<?php echo $this->translate('Edit'); ?> <%= name %>">
		<% } %>
        <span class="brand"><%= brand %></span>
		<%
			if (!photo) {
				photo = $('#website_url').val()+'/system/images/noimage.png';
			} else if (! /^https?:\/\//.test(photo) ) {
				photo = websiteUrl + mediaPath + photo.replace('/', '/product/');
			}
		%>
        <span class="image">
		    <img src="<%= photo %>" alt="<%= name %>"/>
		</span>
        <span class="name"><%= name %></span>

		<span class="sku"><%= sku %></span>
        <% if (!showDelete) { %>
	</a>
	<label class="checkbox-del"><input type="checkbox" class="marker" name="marker" value=<%= id %>></label>
<% } %>
</script>

<script id="quickPreviewTemplate" type="text/template">
	<a href="<%= (_.isObject(product.page) ? $('#website_url').val() + product.page.url : '#') %>" target="_blank">
		<span class="name"><%= product.name %></span>
		<span class="image background"><img src="<%= photoUrl %>"/></span>
		<span class="description"><%= product.shortDescription.length > 220 ? product.shortDescription.slice(0, 219) + '...' : product.shortDescription %></span>
		<span class="price">
            <% pricePreview = parseFloat(product.price) %>
            <% pricePreview = isNaN(pricePreview) ? 0.00 : pricePreview %>
			<%= pricePreview.toFixed(2) + '&nbsp;' + currency %>
		</span>
		<span class="info"><?php echo $this->translate('Click preview to get to product landing page');?></span>
	</a>
</script>

<div class="seotoaster container">
    <?php
        echo $this->partial(
            'admin' . DIRECTORY_SEPARATOR . '_header.phtml',
            array(
                'helpSection' => $this->helpSection,
                'hashMap'     => Tools_Misc::$_helpHashMap
            )
        );
    ?>
    <div id="manage-product" class="with-content-footer">
        <span class="spinner"></span>
        <div id="product-list" class="show-right">
            <div class="header shadow">
                <div class="closebutton">
                    <a id="product-list-back-link" class="hide-block ticon-chevron-right" href="javascript:;" onclick="$('#product-image-folder').val('0');" title="<?php echo $this->translate('Back'); ?>"></a>
                </div>
                <div class="grid_5">
                    <label class="grid_3 alpha omega" for="product-list-search"><?php echo $this->translate('Search');?>:</label>
                    <input class="grid_9 mt5px" type="text" name="product-list-search" id="product-list-search" placeholder="by name, sku, mpn or tags"/>
                </div>
            </div>
            <div id="product-list-holder" class="content-footer scroll pl2 pr2 column_8 full-width" data-emptymsg="<?php echo $this->translate('Nothing Found'); ?>"></div>
            <div class="footer text-right grid_12">
                <a id="massaction" class="fl-left" href="javascript:;">run mass action</a>
                <div class="paginator"><!-- placeholder for paginator --></div>
            </div>
        </div>


        <div id="image-select-dialog" class="show-left w100">
            <div class="header text-center">
                <div class="closebutton">
                    <a class="hide-block ticon-chevron-left" href="javascript:;" onclick="$('#product-image-folder').val('0');$('#image-list, .paginator').empty();" title="<?php echo $this->translate('Back'); ?>"></a>
                </div>
                <?php /*echo $this->formSelect('product-image-folder', null, array('title' => 'select folder', 'class' => 'mt5px grid_4 push_4'), $this->imageDirList); */?>
            </div>
            <div id="image-list" class="content-footer grid_12 list-images"><span class="spinner"></span></div>
            <div class="footer grid_12 text-center">
                <div class="paginator"></div>
            </div>
        </div>

    <div class="nav-links header fl-right">
        <a class="show-list info inverse ticon-edit" href="javascript:;" data-listtype="edit" title="<?php echo $this->translate('Edit product'); ?>"></a>
        <span class="text-line"><?php echo $this->translate('Product'); ?></span>
        <a id="new-product" class="success inverse ticon-plus-sign" href="#new" title="<?php echo $this->translate('New product'); ?>"></a>
    </div>
    <div class="tabs-nav-wrap">
            <span class="arrow left ticon-arrow-left3"></span>
            <span class="arrow right ticon-arrow-right3"></span>
            <ul class="header">
                <li><a href="#main-tab"><?php echo $this->translate('Main'); ?></a></li>
                <li><a href="#tag-tab"><?php echo $this->translate('Product tags'); ?></a></li>
                <li><a href="#options-tab"><?php echo $this->translate('Product options'); ?></a></li>
                <li><a href="#related-tab"><?php echo $this->translate('Cross selling'); ?></a></li>
                <li><a href="#coupon-tab"><?php echo $this->translate('Coupons'); ?></a></li>
                <li><a href="#group-pricing-tab"><?php echo $this->translate('Groups'); ?></a></li>
                <?php foreach ($this->plugins as $plugin) : ?>
                    <?php
                    $pluginClass = new Zend_Reflection_Class(ucfirst(strtolower($plugin)));
                    $title = $pluginClass->hasConstant('DISPLAY_NAME') ? $pluginClass->getConstant('DISPLAY_NAME') : ucfirst($plugin);
                    if(!$pluginClass->hasMethod('tabAction')){
                        continue;
                    }
                    ?>
                    <li>
                        <a href="<?php echo $this->websiteUrl; ?>plugin/<?php echo $plugin; ?>/run/tab/"><?php echo $this->translate($title); ?></a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <!--------- MAIN INFO -------------->
        <input type="hidden" name="mediaPath" value="<?php echo $this->websiteConfig['media']; ?>" id="media-path"/>

        <div id="main-tab" class="form">
            <div class="grid_8 alpha">
                <fieldset>
                    <div class="grid_3 alpha text-center">
                        <?php echo $this->formSelect('product-image-folder', null, array('title' => 'select folder', 'class' => 'mb5px small'), $this->imageDirList); ?>
                        <div class="product-preview page-preview">
                            <img id="product-image" src="<?php echo $this->websiteUrl; ?>system/images/noimage.png" alt=""/>
                            <span class="ticon-folder-upload"><?php echo $this->translate('Choose your image');?></span>
                            <input type="hidden" id="things-new-folder" value="products"/>
                            <?php
                                $uploader = $this->toasterUploader(array('id' => 'product-teaser-uploader','caller' => 'media', 'noMultiupload' => true, 'filters' => array("image"), 'caption' => " "));
                                echo $uploader;
                            ?>
                        </div>
                    </div>
                    <div class="grid_9 alpha omega mt0px">
                        <label class="grid_7 alpha" for="product-name"><?php echo $this->translate('Product Name'); ?></label>
                        <label class="grid_5 omega fs12 text-right pointer">
                            <?php echo $this->translate('This product is enabled'); ?>
                            <input type="checkbox" id="product-enabled"/>
                        </label>
                        <input type="text" id="product-name" data-reflection="name" placeholder="<?php echo $this->translate('enter name of product'); ?>" autofocus="autofocus"/>
                    </div>
                    <div class="grid_3 alpha omega labeled mt1-5em">
                        <input class="grid_8 alpha omega fl-right" type="text" id="product-sku" data-reflection="sku" placeholder="<?php echo $this->translate('item id'); ?>"/>
                        <label class="grid_4 alpha omega" for="product-sku">SKU</label>
                    </div>
                    <div class="grid_4 omega labeled mt1-5em">
                        <input class="grid_9 alpha omega fl-right" type="text" id="product-mpn" data-reflection="mpn" placeholder="manufacturer partnumber"/>
                        <label class="grid_3 alpha omega" for="product-mpn">MPN</label>
                    </div>
                    <div class="grid_2 omega labeled mt1-5em">
                        <input class="grid_8 alpha omega" type="text" id="product-weight" data-reflection="weight" placeholder="0.00">
                        <label class="grid_4 alpha omega" for="product-weight"><?php echo $this->translate($this->generalConfig['weightUnit']); ?></label>
                    </div>
                    <p class="labeled grid_6 alpha omega mt1-5em">
                        <input class="grid_4 omega fl-right" type="text" name="" id="new-brand"  placeholder="<?php echo $this->translate('create new'); ?>">
                        <select class="grid_6 alpha omega fl-right" name="product-brand" id="product-brand" data-reflection="brand">
                            <option value="0"><?php echo $this->translate('select brand'); ?></option>
                            <?php foreach ($this->brands as $brand): ?>
                            <option value="<?php echo $brand->getName(); ?>"><?php echo $brand->getName(); ?></option>
                            <?php endforeach; ?>
                        </select>
                        <label class="grid_2 alpha omega" for="product-brand"><?php echo $this->translate('Brand'); ?></label>
                    </p>
                    <label class="grid_3 omega mt1-75em text-right pointer"><input id="free-shipping" type="checkbox"/> <?php echo $this->translate('Free Shipping'); ?></label>
                </fieldset>

                <div class="mt2-25em">
                    <div id="description-box" class="tabs-gray">
                        <?php
                            $lexemShortDescription = $this->translate('Short description');
                            $lexemFullDescription = $this->translate('Full description');
                        ?>
                        <ul>
                            <li><a href="#short-description-tab"><?php echo $lexemShortDescription; ?></a></li>
                            <li><a href="#full-description-tab"><?php echo $lexemFullDescription; ?></a></li>
                        </ul>
                        <div id="short-description-tab">
                            <textarea id="product-shortDescription" data-reflection="shortDescription" placeholder="<?php echo $lexemShortDescription; ?>"></textarea>
                        </div>
                        <div id="full-description-tab">
                            <textarea id="product-fullDescription" data-reflection="fullDescription" placeholder="<?php echo $lexemFullDescription; ?>"></textarea>
                        </div>
                    </div>
                </div>
            </div>
            <!--End grid_8-->

            <div class="grid_4 omega mt0px">
                <fieldset>
                    <div class="grid_12 alpha omega">
                    <?php if(!empty($this->templateList)):?>
                        <label for="product-pageTemplate"><?php echo $this->translate('Select a product page template');?></label>
                        <select name="product-pageTemplate" id="product-pageTemplate" data-reflection="pageTemplate">
                            <option value="-1" disabled="disable"><?php echo $this->translate('Select Template');?></option>
                            <?php foreach ($this->templateList as $tmpl) : ?>
                            <option value="<?php echo $tmpl->getName(); ?>"><?php echo $tmpl->getName(); ?></option>
                            <?php endforeach; ?>
                        </select>
                    <?php else:?>
                        <div id="templatelist">
                            <h4 class="missing-template message warning text-normal mb10px mt10px">
                                <strong><?php echo $this->translate('Warning!');?> </strong><?php echo $this->translate('You don\'t have any product template.');?> [ <a href="<?php echo $this->websiteUrl;?>backend/backend_theme/template/"><?php echo $this->translate('Create one now');?>.</a> ]
                            </h4>
                        </div>
                    <?php endif;?>
                    </div>
                    <div class="grid_6 alpha labeled mt1-5em">
                        <input class="grid_8 alpha omega fl-right" type="text" id="product-price" data-reflection="price" placeholder="0.00"/>
                        <label class="grid_4 alpha omega" for="product-price" id="currency-unit"><?php echo $this->generalConfig['currency']; ?></label>
                    </div>
                    <div class="grid_6 omega labeled mt1-5em">
                        <input class="grid_8 alpha omega fl-right" type="text" id="product-inventory" data-reflection="inventory" placeholder="&infin;">
                        <label class="grid_4 alpha omega" for="product-inventory"><?php echo $this->translate('QTY'); ?></label>
                    </div>
                    <div class="grid_12 alpha omega mt1-5em labeled">
                        <select id="product-taxClass" class="grid_10 alpha omega fl-right" name="taxes" data-reflection="taxClass">
                            <option value="0"><?php echo $this->translate('Non taxable'); ?></option>
                            <option value="1"><?php echo $this->translate('Default'); ?></option>
                            <option value="2"><?php echo $this->translate('Alternative'); ?></option>
                            <option value="3"><?php echo $this->translate('Alternative 2'); ?></option>
                        </select>
                        <label class="grid_2 alpha omega" for="product-taxClass"><?php echo $this->translate('Taxes'); ?></label>
                    </div>
                </fieldset>
            </div>
            <div id="preview-box" class="grid_4 omega tabs-gray mt2-25em">
                <ul>
                    <li><a href="#quick-preview"><?php echo $this->translate('Preview'); ?></a></li>
                    <!--li><a href="#merchandising"><?php echo $this->translate('Merchandising'); ?></a></li-->
                </ul>
                <div id="quick-preview"></div>
                <!--div id="merchandising"></div-->
            </div>
        </div>

        <div id="tag-tab">
            <div class="fl-left mr-grid mt5px">
                <a href="javascript" id="toggle-current-tags">[ <?php echo $this->translate('show only selected');?> ]</a>
            </div>
            <div class="paginator">
                <!-- placeholder for pagination -->
            </div>
            <div class="wrap">
                <input type="text" id="new-tag" placeholder="<?php echo $this->translate('Add a new Tag'); ?>" data-confirmMsg="<?php echo $this->translate('Really, delete Tag &quot;%tag%&quot;? All products will be untagged.'); ?>"/>
            </div>

            <ul id="product-tags-current" class="product-tags list-tags list-inline mb0px mt10px column_5 full-width" style="display:none;"></ul>

            <ul id="product-tags-available" class="product-tags list-tags list-inline mb0px mt10px column_5 full-width"></ul>
        </div>
        <!-- #tag-tab -->

        <div id="options-tab" class="scroll">
            <div class="grid_6 prefix_3 suffix_3">
                <select name="option-library" id="option-library" class="grid_5 alpha omega">
                    <option value="-1" disabled="disabled"><?php echo $this->translate('select from library');?></option>
                </select>
                <span class="grid_2 alpha omega or"><?php echo $this->translate('or');?></span>
                <button id="add-new-option-btn" class="btn grid_5 alpha omega"><?php echo $this->translate('Create new option');?></button>
            </div>
            <div id="options-holder" class="grid_12 alpha omega">
            </div>
        </div>
        <!-- End Tab 3 -->

        <div id="related-tab" class="scroll">
            <div id="related-holder" class="column_8 full-width">
                <a href="javascript:;" data-listtype="related" class="show-list productlisting ticon-plus-sign fs48" title="<?php echo $this->translate('Add related'); ?>"></a>
                <span class="spinner"></span>
            </div>
        </div>

        <div id="coupon-tab">
            <p class="blockquote info fs12 hide"><?php echo $this->translate('Set parameters for promotional coupons from this screen. These coupons are valid only when this specific product is part of an order.'); ?></p>
            <?php echo $this->partial('merchandising/coupon.phtml'); ?>
        </div>

        <div id="group-pricing-tab">
            <p class="blockquote fs12 mb10px hide"><?php echo $this->translate('Set your product price for each customers groups.'); ?></br><strong><?php echo $this->translate('(create groups & defaults from the merchandising menu.)'); ?></strong></p>
            <?php echo $this->partial('product/grouping-price.phtml'); ?>
        </div>

        <div class="footer grid_12">
            <a href="javascript:;" class="delete-selected error" alt="<?php echo $this->translate('Delete this product'); ?>" id="delete" style="display: none;">[ <?php echo $this->translate('Delete this product'); ?> ]</a>
            <button class="btn ticon-save" type="submit" name="submit" id="submit" value="Save"/><?php echo $this->translate('Save product'); ?></button>
        </div>
    </div>
    <input class="secure-token-tax" type="hidden" name="<?php echo Tools_System_Tools::CSRF_SECURE_TOKEN;?>" value="<?php echo $this->secureToken;?>" />
</div>

<script>
	$(function () {
		$('#manage-product,#description-box, #preview-box').tabs({
            beforeLoad: function(event, ui){
                //showSpinner('#merchandising');
            }
        });
		$(".ui-tabs-nav, .ui-tabs-nav > *")
				.removeClass("ui-corner-all")
				.addClass("ui-corner-top");

		$(document).one('loaded.product', function () {
			<?php if ($this->product): ?>
			app.model.set(<?php echo json_encode($this->product->toArray()) ;?>);
			app.model.get('options').reset(app.model.get('defaultOptions'));
			app.render();
			<?php endif; ?>
		});
	});
</script>