<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Manage product</title>
		<link href="<?php echo $this->websiteUrl;?>system/css/reset.css" media="screen" rel="stylesheet" type="text/css" > 
		<link href="<?php echo $this->websiteUrl;?>system/css/grid.css" media="screen" rel="stylesheet" type="text/css" > 
		<link href="<?php echo $this->websiteUrl;?>system/uithemes/seotoasterui/seotoasterui.css" media="screen" rel="stylesheet" type="text/css" > 
		<link href="<?php echo $this->websiteUrl;?>system/css/seotoaster.css" media="screen" rel="stylesheet" type="text/css" > 
		<link href="<?php echo $this->websiteUrl;?>plugins/shopping/web/js/libs/smoke/smoke.css" media="screen" rel="stylesheet" type="text/css" > 
		<link href="<?php echo $this->websiteUrl;?>plugins/shopping/web/js/libs/smoke/100s.css" media="screen" rel="stylesheet" type="text/css" > 
		<style>
			div.box {
				background-color: white;
				margin: 3px 0;
				padding: 3px;
				cursor: pointer;
				border: 1px solid #ccc;
			}
			div.box:hover {
				box-shadow: 0 0 3px #3C78A7;
			}
			#product-categories .category-widget {
				float:left;
				margin: 3px 2px;
			}
			.toolbar span.ui-icon {
				display: inline-block;
				border-radius: 4px;
				cursor:pointer;
			}
			.toolbar span.ui-icon:hover {
				background-color: indianred;
				background-image: url(/system/uithemes/seotoasterui/images/ui-icons_ffffff_256x240.png);
			}
			#options-holder .option-content .option-modifier-select {
				width: 50px;
			}
			a.nav-links {
				color: #f3f3f3;
                border-bottom: 1px #1e90ff dotted;
                font-weight: normal;
                font-size: 14px;
			}
			a.nav-links:hover {
				color: #1e90ff;
			}
			div.productlisting {
                width: 11%;
                height: 150px;
                margin: 5px;
                /*padding: 2px;*/
                float: left;
                border: 2px solid lavender;
                border-radius: 3px 8px;
                overflow: hidden;
                position: relative;
                text-align: center;
                cursor: pointer;
                background: #fff;
                font-size: 11pt;
			}
            div.productlisting img{
                max-height: 80px;
                padding: 4px 0px;
            }
            p.brand {
                padding: 2px 0px;
                background-color: lavender;
                margin-bottom: 1px;
                font-weight:bold;
            }
            p.sku{
                text-align: right;
                font-size: 8pt;
                border-top: 1px dashed #eee;
                padding: 4px 0px;
                margin-top: 4px;
                color: #7C7C7C;
                position: absolute;
                bottom: 0px;
                right: 2px;
                width: 100%;
                height: 8pt;
                overflow: hidden;
                background-color:#fff;
            }

            input.highlight {
                border-color: #cd5c5c !important;
            }
            #manage-product > .ui-tabs-panel {
                height: 400px;
            }
            #manage-product .ui-tabs-panel {
                padding: 10px;
            }
            #options-holder > div.option-wrapper {
                border: 2px #666 solid;
                background: url('/system/images/bg-strip.png');
            }
            #ajax_msg {
                line-height: 50px;
                display: none;
                position: absolute;
                top: 30%;
                left:0;
                width: 100%;
                z-index: 5000;
            }
		</style>
		
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script>
		<script src="<?php echo $this->websiteUrl;?>system/js/external/jquery/plugins/tmpl/jquery.tmpl.min.js"></script>
		<script src="<?php echo $this->websiteUrl;?>plugins/shopping/web/js/libs/jquery/jquery.masonry.min.js"></script>
		
		<script src="<?php echo $this->websiteUrl;?>plugins/shopping/web/js/libs/smoke/smoke.min.js"></script>
		
		<!-- Loading "product/main.js" as a bootstrap of product module -->
		<script data-main="<?php echo $this->websiteUrl;?>plugins/shopping/web/js/modules/product/main.js" src="<?php echo $this->websiteUrl;?>plugins/shopping/web/js/libs/require/require-dev.js"></script>
		
		<script id="categoryTemplate" type="text/x-jquery-tmpl">
			<input type="checkbox" name="category[]" value="${id}"/>
			<span class="category-editable">${name}</span>
			<div class="toolbar" style="display:inline;">
				<span class="ui-icon ui-icon-closethick">Delete</span>
			</div>
		</script>
		
		<script id="imgTemplate" type="text/x-jquery-tmpl">
			{{each imageList}}
			<div class="box">
				<img src="${src}" width="100px" data-name="${name}"/>
			</div>
			{{/each}}
		</script>
		
		<script id="optionMainTemplate" type="text/x-jquery-tmpl">
            <div class="grid_4 ">
                <div class="grid_4"><label>Title</label></div>
                <div class="grid_8"><input type="text" class="option-title" value="${title}"/></div>
            </div>
            <div class="grid_4">
                <div class="grid_3">
                    <label>Type</label>
                </div>
                <div class="grid_9">
                    <select class="option-type-select">
                        <option value="dropdown">Dropdown Box</option>
                        <option value="radio">Radio Switch</option>
                        <option value="text">Text Field</option>
                        <option value="date">Datepicker</option>
<!--							<option value="file">Upload File</option>-->
                    </select>
                </div>
            </div>
            <div class="grid_3">
                {{if id}}
                &nbsp;
                {{else}}
                <label for="isTemplate">
                    <input type="checkbox" title="Add as template?" name="isTemplate" {{if isTemplate}}checked="checked"{{/if}} />
                    Add as template?
                </label>
                <input type="text" name="templateName" placeholder="Template name" />
                {{/if}}
            </div>
            <div class="grid_1">
                <button class="remove-option">x</button>
            </div>
            <div class="grid_12 option-content"></div>
		</script>
		
		<script id="optionListTemplate" type="text/x-jquery-tmpl">
			<div class="ui-widget-header clearfix">
				<div class="grid_3">Title</div>
				<div class="grid_4">Price modifier</div>
				<div class="grid_3">Weight modifier</div>
				<div class="grid_1">Dflt</div>
				<div class="grid_1"></div>
			</div>
			<div class="option-list-holder">
				
			</div>
			<div class="clearfix" style="border-top: 1px #666 solid;">
				<button class="add-selection-btn" style="float:right;">Add new selection</button>
			</div>
		</script>
		
		<script id="listItemTemplate" type="text/x-jquery-tmpl">
			<div class="grid_3">
				<input type="text" name="title" data-role="title" value="${title}" />
			</div>
			<div class="grid_4">
				<select class="option-modifier-select" name="priceModifierSign" >
					<option value="+" {{if priceSign == '+'}}selected{{/if}} >+</option>
					<option value="-" {{if priceSign == '-'}}selected{{/if}} >-</option>
				</select>
				<input type="text" name="priceModifierValue" value="${priceValue}" class="option-modifier-select" placeholder="0" />
				<select name="priceModifierType" class="option-modifier-select" >
					<option value="percent" {{if priceType == 'percent'}}selected{{/if}} >%</option>
					<option value="unit" {{if priceType == 'unit'}}selected{{/if}} ><?php echo $this->generalConfig['currency']; ?></option>
				</select>
			</div>
			<div class="grid_3">
				<select name="weightModifierSign" class="option-modifier-select">
					<option value="+" {{if weightSign == '+'}}selected{{/if}} >+</option>
					<option value="-" {{if weightSign == '-'}}selected{{/if}} >-</option>
				</select>
				<input name="weightModifierValue" type="text" class="option-modifier-select" placeholder="0" value="${weightValue}"/>
				<span><?php echo $this->generalConfig['weightUnit']; ?></span>
			</div>
			<div class="grid_1">
				<input type="radio" name="isDefault[${_parent}]" value="${title}" {{if isDefault == '1'}}checked="checked"{{/if}} />
			</div>
			<div class="grid_1">
				<button class="item-remove">x</button>
			</div>
		</script>
		
		<script id="productListingTemplate" type="text/x-jquery-tmpl">
			{{if showDelete}}
			<div class="toolbar" style="position: absolute;right: 0;top: 0;">
				<span class="ui-icon ui-icon-closethick">Delete</span>
			</div>
			{{/if}}
			<a href="#edit/${id}" title="<?php echo $this->translate('Edit');?> ${name}" style="text-align:center;">
                <p class="brand">${brand}</p>
                <img class="lazy" src="{{if photo}}${'/media/'+photo.replace('/', '/product/')}{{else}}/system/images/noimage.png{{/if}}" alt="${name}" />
                ${name}
                <p class="sku">${sku}</p>
            </a>
		</script>
        <script>
            /**
             * applying main UI elements
             */
            $(function(){
                $('#manage-product,#description-box').tabs();
                $(".ui-tabs-nav, .ui-tabs-nav > *" )
                    .removeClass( "ui-corner-all" )
                    .addClass( "ui-corner-top" );
                $('#ajax_msg').ajaxStart(function(){
                    $(this).show();
                }).ajaxStop(function(){
                    $(this).hide();
                });
            });
        </script>
	</head>
    <body>
		<noscript style="width: 100%; height: 100%; position: fixed; display: block; background: white; font-size: 150%; text-align: center; padding-top: 30%;">
		JavaScript must be enabled at this point.<br/>
		<a href="http://www.seotoaster.com/">seotoaster.com</a>
		</noscript>
		<input type="hidden" id="pluginUrl" name="pluginUrl" value="<?php echo trim($this->websiteUrl, ' /').$this->url(array('run'=>''));?>" />
		<input type="hidden" id="websiteUrl" name="websiteUrl" value="<?php echo $this->websiteUrl;?>" />
		<div id="ajax_msg" class="smoke">
            <img src="<?php echo $this->websiteUrl; ?>/system/images/loading.gif" /> Loading...
		</div>
        <div id="manage-product" class="seotoaster container_12" style="padding: 0;">
            <div id="product-list" class="clearfix" style="display: none; overflow: hidden; position:absolute; top: 0; left: 0; width: 100%; height: 100%; z-index: 9999; background-color: #fff;">
                <div class="clearfix ui-widget-header">
                    <div class="grid_1 prefix_3">
                        <label for="product-list-search">Search</label>
                    </div>
                    <div class="grid_5 suffix_3">
                        <input type="text" name="product-list-search" id="product-list-search" placeholder="by name, sku or mpn" />
                    </div>
                </div>
                <div id="product-list-holder" class="h500" style="overflow-y: auto; background: url('/system/images/bg-strip.png');"></div>
            </div>

            <div id="image-select-dialog" class="ui-helper-reset" style="display:none; padding: 5px 0; position: absolute; top: 0; left: 0; width: 100%; height: 100%; z-index: 9999; background-color: #eee;">
                <div class="clearfix" style="border-bottom: 1px solid #777; margin-bottom: 10px;">
                    <a href="javascript:;" onclick="$('#image-select-dialog').hide('slide');">&lt; back</a>
                    <span style="margin-left: 30%">select image for product</span>
                </div>
                <div id="image-list"></div>
            </div>

            <ul>
                <li><a href="#tab1">Main Info</a></li>
                <li><a href="#category-tab">Categories</a></li>
                <li><a href="#options-tab">Options</a></li>
                <li><a href="#tab4">Related Products</a></li>
                <li><a href="#tab5">Marketing</a></li>
                <a href="#new" class="nav-links">New product</a>
                <a href="#list" class="nav-links">Edit product</a>
            </ul>
            <!--------- MAIN INFO -------------->
            <div id="tab1" class="clearfix">
                <div class="grid_8 alpha">
                    <div class="grid_4">
                        <?php echo $this->formSelect('product-image-folder', null, array('title' => 'select folder'), $this->imageDirList); ?>
                        <div style="height: 130px; background: white; text-align: center; vertical-align: middle;">
                            <img style="height: 100%; max-width: 190px;" id="product-image" src="<?php echo $this->websiteUrl;?>system/images/noimage.png" alt="" />
                        </div>
                    </div>
                    <div class="grid_8">
                        <label for="product-name">Product Name</label>
                    </div>
                    <div class="grid_8">
                        <input type="text" id="product-name" data-reflection="property" placeholder="enter name of product" />
                    </div>
                    <div class="grid_2">
                        <label for="product-sku">SKU</label>
                        <input type="text" id="product-sku" data-reflection="property" placeholder="item id" />
                    </div>
                    <div class="grid_3">
                        <label for="product-mpn">MPN</label>
                        <input type="text" id="product-mpn" data-reflection="property" placeholder="manufacturer partnumber" />
                    </div>
                    <div class="grid_3">
                        <label for="product-weight">Weight (in <?php echo $this->generalConfig['weightUnit']; ?>)</label>
                        <input type="text" id="product-weight" data-reflection="property" placeholder="0.00">
                    </div>
                    <div class="clear"></div>
                    <div class="grid_8">
                        <label for="product-brand">Brand&nbsp;<a href="javascript:;" id="brandlanding-link" target="_blank" data-msg="You don't have page &quot;<%= name.toLowerCase() %>.html&quot; yet." style="font-size: 80%">visit brand landing page</a></label>
                    </div>
                    <div class="grid_4">
                        <select name="product-brand" id="product-brand" data-reflection="property">
                        </select>
                    </div>
                    <div class="grid_4">
                        <input type="text" name="" id="new-brand" placeholder="or create new">
                    </div>
                    <div class="clear"></div>

                    <div class="grid_12 mt5px">
                        <div id="description-box">
                            <ul>
                                <li><a href="#short-description-tab">Short description</a></li>
                                <li><a href="#full-description-tab">Full description</a></li>
                            </ul>
                            <div id="short-description-tab">
                            <textarea id="product-shortDescription" class="h150" data-reflection="property" placeholder="Short description"></textarea>
                            </div>
                            <div id="full-description-tab">
                            <textarea id="product-fullDescription" class="h150" data-reflection="property" placeholder="Full description"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <!--End grid_8-->
                <div class=" grid_4">
                    <label for="product-enabled"><input type="checkbox" id="product-enabled" />This product is enabled</label>
                <hr />
                </div>
                <div class="grid_2">
                    <label for="product-price">Price (in <?php echo $this->generalConfig['currency']; ?>)</label>
                    <input type="text" id="product-price" data-reflection="property" placeholder="0.00"/>
                </div>
                <div class="grid_2">
                    <label for="tax">Taxes</label>
                    <select name="taxes" id="product-taxClass" data-reflection="property" >
                        <option value="0">Non taxable</option>
                        <option value="1">Default</option>
                        <option value="2">Alternative</option>
                        <option value="3">Alternative 2</option>
                    </select>
                </div>
                <div class=" grid_4">
                <hr />
                </div>
                <div class="grid_4">
                    <label for="product-pageTemplate">Select a product page template</label>
                </div>
                <div class="grid_4">
                    <select name="product-pageTemplate" id="product-pageTemplate" data-reflection="property">
                        <option value="-1" disabled="disable">Select Template</option>
                        <?php foreach ($this->templateList as $tmpl) : ?>
                        <option value="<?php echo $tmpl->getName();?>" ><?php echo $tmpl->getName();?></option>
                        <?php endforeach; ?>
                    </select>
                    <hr />
                </div>
                <div class="grid_4">
                    <div id="quick-preview"></div>
                </div>
            </div>

            <div id="category-tab" class="clearfix">
                <div class="grid_4 prefix_4 suffix_4 mb5px" style="text-align:center; box-shadow: 0 10px 15px -10px #999;">
                    <input type="text" id="new-category" placeholder="Create new category" data-confirmMsg="Really, delete category &quot;%cat%&quot;?"/>
                </div>

                <div id="product-categories" class="grid_12">
                </div>

            </div> <!-- #category-tab -->

            <div id="options-tab" class="clearfix">
                <div>
                    <button id="add-new-option-btn">Create new option</button>
                    <span>or</span>
                    <select name="option-library" id="option-library" style="width: 250px;">
                        <option value="-1" disabled="disabled">select from library</option>
                    </select>
                </div>
                <div id="options-holder" class="clearfix h350" style="overflow-y: scroll;">

                </div>
            </div> <!-- End Tab 3 -->

            <div id="tab4" class="clearfix">
                <div class="grid_4 prefix_4 suffix_4 mb5px" style="text-align:center; box-shadow: 0 10px 15px -10px #999;">
                    <input type="text" id="add-related" placeholder="Start typing name, SKU or MPN" />
                </div>
                <div id="related-holder" class="grid_12">

                </div>
            </div>

            <div id="tab5">
                @todo super-mega-merchandising plugins are on thier way
            </div>

            <div class="grid_12">
                <hr />
                <input type="button" value="Delete" id="delete"/>
                <input type="submit" name="submit" id="submit" value="Save"/>
            </div>
        </div>

    </body>
</html>