<?php $countryList = Tools_Geo::getCountries(true); ?>
<script>
	$.fn.dataTable || $('head script:last').after(unescape("%3Cscript async='false' src='/system/js/external/jquery/plugins/DataTables/jquery.dataTables.min.js'%3E%3C/script%3E"));
</script>
<div class="clearfix profile-header">
	<div class="tt">
		<div class="ot profile-picture textcentered">
			<?php echo $this->gravatar($this->customer->getEmail(), array('secure'=>true), array('class' => 'photo') ); ?>
		</div>
		<div class="tt profile-main-info vcard">
			<h1 class="fn"><?php echo $this->customer->getFullName();?></h1>
			<h3><a href="mailto:<?php echo $this->customer->getEmail();?>" class="email"><?php echo $this->customer->getEmail();?></a></h3>
			<p><?php echo $this->translate("%1\$s since %2\$s", $this->customer->getRoleId(), date('jS F, Y', strtotime($this->customer->getRegDate())) );?></p>
			<p><?php
				if ($this->customer->getLastLogin()) {
					$lastSeen = date_diff(date_create($this->customer->getLastLogin()), date_create());
					$lastSeen = intval($lastSeen->format('%a'));
					if ($lastSeen < 7) {
						$lastSeenStamp = date('l', strtotime($lastSeen.' days ago'));
					} else {
						$lastSeenStamp = $lastSeen.' days ago';
					}
				} else {
					$lastSeenStamp = 'never';
				}
				echo $this->translate("Last seen: %1\$s", $lastSeenStamp );
				?></p>
			<?php if ($billingAddressDefault = $this->customer->getDefaultAddress('billing')) : ?>
				<div class="adr">
					<span class="street-address"><?php echo $billingAddressDefault['address1'].' '. $billingAddressDefault['address2'];?></span>
					<br/>
					<span class="locality"><?php echo $billingAddressDefault['city'];?></span>
					<span class="region"><?php $state = Tools_Geo::getStateById($billingAddressDefault['state']); echo $state['state']; ?></span>
					<span class="postal-code"><?php echo $billingAddressDefault['zip'];?></span>
				</div>
			<?php endif;?>
			<?php if ($shippingAddressDefault = $this->customer->getDefaultAddress('shipping')) : ?>
				<div class="adr">
					<span class="street-address"><?php echo $shippingAddressDefault['address1'].' '. $shippingAddressDefault['address2'];?></span>
					<br/>
					<span class="locality"><?php echo $shippingAddressDefault['city'];?></span>
					<span class="region"><?php $state = Tools_Geo::getStateById($shippingAddressDefault['state']); echo $state['state']; ?></span>
					<span class="postal-code"><?php echo $shippingAddressDefault['zip'];?></span>
				</div>
			<?php endif;?>
		</div>
	</div>


	<div class="ot profile-actions">
		<!--		<input type="button" class="blue-btn" value="--><?php //echo $this->translate('Edit profile');?><!--" />-->
		<p class="title textcentered ui-state-default">
			<img style="width: 16px; vertical-align: text-bottom;" src="data:;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAZCAYAAAAv3j5gAAAA/UlEQVR42r2VvQ3CMBBGswEjMIJHyASeIUV6qChSISRKpLR0jEDBABmBkpIRIk8QPks+3ekkfkzOsfSUxIm+p/PFSYUxRTAqAsPPvN6BEUzpWJcSBcolWSnRpJGT3oolK3ooSWMuwtinzCtwNG8qisEpL4CVfMa2R7xkBzlvWpFYskHfny1KG3FUjV+bi1jCInnfqketkhAt8PN6xMt14+DMinSwWv8AtuAuQp+gVx/PJl/EAZoBnNTzHZ1n9+iN5Ah8Lt8q0pLx3332SXRWkgAaU1EMFM11oP4lOLdHG/Ev6YC3QIscvWn6rbKtiPdID3wZEXOJk8VEpVlU9AI9gR1AIgkvUwAAAABJRU5ErkJggg==">
			<?php echo $this->translate('Orders summary');?>
		</p>
		<ul class="stats clearfix">
			<?php foreach ($this->stats as $key => $value) : ?>
				<li class="oh <?php echo $key;?>" data-sort="<?php echo $key;?>"><?php echo $value.' '.$this->translate($key);?></li>
			<?php endforeach; ?>
		</ul>
	</div>
</div>


<div id="profile-content">
	<ul class="profile-nav">
		<li><a href="#profile-orders-list">Orders</a></li>
		<li><a href="#profile-address-list">Addresses</a></li>
	</ul>

	<div id="profile-orders-list" class="clearfix">
		<table id="orders-table" border="1">
			<thead>
				<tr class="title-table">
					<th>#</th>
					<th><?php echo $this->translate('Purchased On');?></th>
					<th><?php echo $this->translate('Status');?></th>
					<th><?php echo $this->translate('Products in cart');?></th>
					<th><?php echo $this->translate('Total Price');?></th>
					<th><?php echo $this->translate('Shipping price');?></th>
					<th><?php echo $this->translate('Shipping via');?></th>
					<th><?php echo $this->translate('Details');?></th>
				</tr>
			</thead>
			<tbody>
			<?php if ($this->orders): ?>
			<?php foreach ($this->orders as $order):?>
				<tr data-role="cart" data-id="<?php echo $order->getId();?>">
					<td><?php echo $order->getId();?></td>
					<td><?php echo date('d M, Y', strtotime($order->getCreatedAt()));?></td>
					<td><?php echo $order->getStatus();?></td>
					<td><?php echo sizeof($order->getCartContent());?></td>
					<td><?php echo $this->currency($order->getTotal());?></td>
					<td><?php echo $this->currency($order->getShippingPrice()) ;?></td>
					<td class="shipping-data">
						<p><?php echo $order->getShippingService().' - '.$order->getShippingType() ;?></p>
						<?php if (Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_ADMINPANEL)):?>
						<p>
							<u>Tracking ID</u>: <span class="tracking-id"><?php echo $order->getShippingTrackingId(); ?></span>
							<a href="javascript:;" class="tracking-dialog" data-shipping-tracking-id="<?php echo $order->getShippingTrackingId();?>">[&nbsp;edit&nbsp;]</a>
						</p>
						<?php endif;?>
						<p class="textcentered">
							<a target="_blank" class="tracking-link" href="<?php echo $this->websiteUrl;?>plugin/shopping/run/track/id/<?php echo $order->getId();?>"><?php echo $this->translate('Where is my order?');?></a>
						</p>
					</td>
					<td><a href="javascript:;" class="tpopup" data-pheight="600" data-url="<?php echo $this->websiteUrl;?>plugin/shopping/run/order/id/<?php echo $order->getId();?>">view</a></td>
				</tr>
			<?php endforeach; ?>
			<?php endif; ?>
			</tbody>
		</table>
		<?php //var_dump($this->orders); ?>
	</div>
	<div id="profile-address-list" class="clearfix">
	<?php $addressList = $this->customer->getAddresses(); ?>
	<?php if (!empty($addressList)): ?>
	<?php foreach ($addressList as $billingAddress): ?>
	<div class="ot">
		<div class="adr">
			<?php echo $this->formHidden('id', $billingAddress['id'], array('id'=>'id_'.$billingAddress['id']));?>
			<?php echo $this->formHidden('type', $billingAddress['address_type'], array('id'=>'type_'.$billingAddress['id']));?>
			<span class="street-address"><?php echo $billingAddress['address1'].' '. $billingAddress['address2'];?></span>
			<br/>
			<span class="locality"><?php
				echo $billingAddress['city'].
					($billingAddress['city']&&($billingAddress['state'] || $billingAddress['zip'])?',':'');
				?></span>
			<span class="region"><?php $state = Tools_Geo::getStateById($billingAddress['state']); echo $state['state']; ?></span>
			<span class="postal-code"><?php echo $billingAddress['zip'];?></span>
			<br />
			<span><?php echo $countryList[$billingAddress['country']];?></span>
<!--			<a class="delete-lnk" href="javascript:;" title="--><?php //echo $this->translate('Delete this address');?><!--"><img src="/system/images/delete.png" alt="[x]"></a>-->
		</div>
	</div>
	<?php endforeach; ?>
	<?php else : ?>
	<p><?php echo $this->translate("You don't have any saved addresses");?></p>
	<?php endif;?>
	</div>
</div>
<script>
	$('#profile-content').tabs();
	$('div#profile-content > *').removeClass('ui-widget-content ui-corner-bottom');
	$('div#profile-content .ui-tabs-nav, div#profile-content .ui-tabs-nav > *').removeClass( "ui-widget-header  ui-corner-all ui-corner-top" );
	$(function(){
		var oTable = $('#orders-table').dataTable({
			bPaginate: false,
			bLengthChange: false,
			sDom: 't',
			aoColumnDefs: [
				{bSortable: false, aTargets: [-1]}
			],
			oLanguage: {
		      sEmptyTable: "<?php echo $this->translate('You do not have any orders'); ?>"
		    }
		});
		$('ul.stats').on('click', 'li', function(e){
			var filter = $(this).data('sort');
			if (filter === 'total') filter = '';
			oTable.fnFilter(filter, 2);
		});
	});
	$('a.tracking-dialog').on('click', function(e){
		e.preventDefault();
		var self = this,
			id = parseInt($(this).closest('tr').data('id'));
		smoke.prompt('<?php echo $this->translate('Insert tracking code for this order');?>', function(value){
			if (value === false) {
				return value;
			}
			value = $.trim(value);
			if ($(self).data('shippingTrackingId') !== value) {
				$.ajax({
					url: $('#website_url').val()+'plugin/shopping/run/order?id='+id,
					data: {shippingTrackingId: value},
					type: 'POST',
					dataType: 'json',
					success: function(response) {
						showMessage('<?php echo $this->translate('Saved');?>', response.hasOwnProperty('error') && response.error);
						if (response.hasOwnProperty('responseText')){
							$(self).data('shippingTrackingId', response.responseText.shippingTrackingId);
							$(self).closest('p').find('span.tracking-id').text(response.responseText.shippingTrackingId);
						}
					}
				});
			}
		});
	});
</script>
<style>
	.oh,.ot,.tt{float:left;margin:1%;width:48%}.ot{width:31%}.tt{width:65%}.cl{clear:both}
	#profile ul {
		margin: 0;
		padding: 0;
	}
	#profile ul li {
		list-style: none;
		margin: 0;
		padding: 0;
	}
	#profile .profile-actions {
		border-left: 1px solid #e6e6fa;
	}
	#profile ul.profile-nav li a {
		font-variant: small-caps;
		font-weight: bold;
	}
    #profile #profile-content.ui-tabs .ui-tabs-nav li.ui-tabs-selected,
    #profile #profile-content.ui-tabs .ui-tabs-panel {
	    background: #ffffff;
    }
	#profile #profile-content.ui-tabs .ui-tabs-panel {
		padding: 5px;
		font-size: 14px;
		border: 1px solid #CACACA;
	}

	#profile #profile-address-list div.adr {
		padding: 5px;
		position: relative;
		border: 1px solid #e6e6fa;
		border-radius: 8px 0 8px 8px;
	}
	#profile div.adr a.delete-lnk {
		position: absolute;
		top: 2px;
		right: 2px;
	}
	#profile td.shipping-data p {
		margin: 5px 0;
	}

	/* sidebar stats  */
	#profile .profile-header p.title {
		line-height: 24px;
		background-color: #cccccc;
		color: #666;
		text-transform: uppercase;
		font-weight: bold;
		/*font-variant: small-caps;*/
		border: none;
	}

	#profile .profile-header ul.stats li {
		text-align: center;
		vertical-align: middle;
		padding: 10px 0;
		margin: 1%;
		border-radius: 4px;
		color: #f5f5f5;
		font-weight: bold;
		font-variant: small-caps;
		cursor: pointer;
	}
	#profile .profile-header ul.stats li.total {
		background-color: #87ceeb;
	}
	#profile .profile-header ul.stats li.new {
		background-color: #32cd32;
	}
	#profile .profile-header ul.stats li.completed {
		background-color: #666666;
	}
	#profile .profile-header ul.stats li.pending {
		background-color: #ff7f50;
	}

	/* orders table */
	#profile table {
		width: 100%
	}
	#profile table thead tr {
		background:#666;
		color:#eee;
		text-shadow: 0 0 2px #333;
	}
	#profile table thead th:not(.sorting_disabled) {
		cursor: pointer;
	}
	#profile table thead th::after {
	    display: inline;
	}
	#profile table thead th.sorting::after {
		content: "\00A0\21D5";
	}
	#profile table thead th.sorting_asc::after {
		content: "\00A0\21E7";
	}
	#profile table thead th.sorting_desc::after {
		content: "\00A0\21E9";
	}
	#profile table th, #profile table td{
		border: 1px solid #e6e6fa;
		vertical-align:middle;
		text-align:center;
		padding:5px;
	}
	#profile table th:first-child,
	#profile table td:first-child {
		border-left: none
	}
	#profile table th:last-child,
	#profile table td:last-child {
		border-right: none;
	}
</style>