<?php
$title = $this->translate('Shipping configuration');
$this->headTitle($title);
$this->placeholder('headerContent')->set($title);

$this->headScript()->appendFile($this->websiteUrl.'plugins/shopping/web/js/libs/require.min.js', null, array('data-main' => $this->websiteUrl.'plugins/shopping/web/js/shipping.js'));

?>
<style>
#shippers ul li {
	clear: both;
	width: 100%;
}
#shippers ul li > a {
	width: 80%;
	overflow: hidden;
	text-overflow: ellipsis;
}
#shippers .ui-tabs-panel {
	padding: 4px;
}
#shippers #pane-container header {
	color: gray;
	padding: 4px 20px;
	border-bottom: 1px solid #b5b5b5;
	font-variant: small-caps;
	font-size: 120%;
}
.textright {
	text-align: right;
}
.relative {
	position: relative;
}
#shippers .relative input {

}
.unit-over {
	color: #999;
	position: absolute;
	top: 5px;
	right: 3px;
}
ul.ui-tabs-nav span.unit-over {
	cursor: pointer;
}
ul.ui-tabs-nav span.unit-over:hover {
	text-decoration: underline;
}
ul.ui-tabs-nav li.enabled a {
	color: #228b22;
}
ul.ui-tabs-nav li.disabled a {
	color: #cd5c5c;
}
#ajax_msg {
	position: absolute;
	top: 3px;
	left: 0;
	width: 100%;
	z-index: 5000;
	text-align: center;
	display: none;
}
#ajax_msg img {
	vertical-align: middle;
}
</style>

<div id="ajax_msg"><img src="<?php echo $this->websiteUrl; ?>/system/images/loading.gif" /></div>
<div id="shipping-config" class="container_12">
	<div id="shippers" class="mt10px mb10px clearfix">
		<ul class="grid_4 omega">
			<li><a href="#pickup" data-plugin="pickup"><?php echo $this->translate('Pickup');?></a></li>
			<li><a href="#freeshipping" data-plugin="freeshipping"><?php echo $this->translate('Free shipping');?></a></li>
		<?php foreach($this->shippingPlugins as $plugin):?>
			<li><a data-plugin="<?php echo $plugin->getName();?>" href="<?php echo $this->url(array('run' => 'config', 'name' => strtolower($plugin->getName())), 'pluginroute');?>"><?php echo $plugin->getName();?></a></li>
		<?php endforeach; ?>
		</ul>
		<div id="pane-container" class="grid_8 relative">

			<div id="pickup">
				<label style="display: block;margin: 10px; text-align: justify">When this option is checked user will not be able to fill the shipping address on checkout stage.</label>
			</div>
			<div id="freeshipping">
				<header>Free shipping</header>
				<?php $this->freeForm->setAction($this->url(array('run' => 'bundledshipper')));?>
				<form class="clearfix" action="<?php echo $this->freeForm->getAction();?>" method="post" enctype="application/x-www-form-urlencoded">
					<?php echo $this->freeForm->getElement('shipper')->renderViewHelper(); ?>
					<label class="grid_3 mt5px textright" for="cartamount"><?php echo $this->freeForm->getElement('cartamount')->getLabel();?></label>
					<div class="grid_3 relative">
						<?php echo $this->freeForm->getElement('cartamount')->renderViewHelper();?>
						<label class="unit-over"><?php echo $this->config['currency'];?></label>
					</div>
					<label class="grid_2 mt5px textcentered"><?php echo $this->freeForm->getElement('destination')->getLabel();?></label>
					<div class="grid_3">
						<?php echo $this->freeForm->getElement('destination')->renderViewHelper();?>
					</div>
				</form>
			</div>
		</div>
		<div class="grid_12 mt10px">
			<?php echo $this->formSubmit('submit', 'Save');?>
		</div>
	</div>
</div>

<script>
$(function(){
	$('#shippers').tabs({
		idPrefix: 'shipper-tab',
		panelTemplate: '<div class="clearfix"></div>',
		create: function(event, ui){
			$(this).find('ul.ui-tabs-nav, ul.ui-tabs-nav > li').removeClass('ui-corner-top ui-widget-header')
				.end().find('.ui-tabs-panel').removeClass('ui-corner-bottom');
		}
	});
	$('#ajax_msg').ajaxStart(function(){
		$(this).fadeIn();
	}).ajaxStop(function(){
		$(this).fadeOut();
	});
});
</script>