<?php echo $this->headLink()->appendStylesheet($this->websiteUrl . 'system/js/external/chosen/chosen.css'); ?>
<div class="container_12">
	<!-- Product listing selector -->
	<div id="template-selector" class="grid_12 mt10px mb5px">
		<?php if(isset($this->productTemplates) && !empty($this->productTemplates)): ?>
			<select id="templates" class="templates" style="width:260px;margin: 3px;float:left;" data-placeholder="Select a product listing template...">
				<option value="0"><?php echo $this->translate('Select a product listing template'); ?></option>
				<?php foreach($this->productTemplates as $template): ?>
					<option value="<?php echo $template->getName(); ?>"><?php echo $template->getName(); ?></option>
				<?php endforeach; ?>
			</select>
		<?php else: ?>
			<h3 class="grid_12"><?php echo $this->translate('Warning! You don\'t have any product listing template. You should create one.'); ?></h3>
		<?php endif; ?>
	</div>

	<!-- Filtering -->
	<div id="filters" class="grid_4">
		<select style="width: 205px;float:left;" name="product-categories" id="categories" multiple class="pselect ui-corner-all" data-placeholder="<?php echo $this->translate('Filter by tags');?>..."></select>
	</div>
	<div class="grid_4">
		<select style="width: 205px;float:left;" name="product-brands" id="brands" multiple class="pselect ui-corner-all" data-placeholder="<?php echo $this->translate('Filter by brands');?>..."></select>
	</div>

	<!-- Ordering -->
	<div id="order" class="grid_4">
		<select style="width: 205px;float:left;" name="ordering" id="ordering" multiple class="pselect ui-corner-all" data-placeholder="<?php echo $this->translate('Sort by');?>...">
			<option value="name"><?php echo $this->translate('Name'); ?></option>
			<option value="price"><?php echo $this->translate('Price'); ?></option>
			<option value="brand"><?php echo $this->translate('Brand'); ?></option>
		</select>
	</div>
	<div style="clear: both;"></div>
	<div id="product-products" class="mt10px"></div>
	<a href="javascript:;" id="btn-create" class="grid_12 mt5px"><?php echo $this->translate('Create an automated product listing'); ?></a>
</div>

<style type="text/css">
	#prod-perpage {
		width: 120px;
	}
	.chzn-container-multi {
		margin: 5px 3px;
	}
	#product-products {
		overflow-y: auto;
		height: 310px;
	}
	div.productlisting {
        width: 15%;
        height: 140px;
        margin: 4px 0.6%;
        /*padding: 2px;*/
        float: left;
        border: 1px solid #fff;
        box-shadow: 0 0 4px #BBBBBB;
        -moz-box-shadow: 0 0 4px #BBBBBB;
        -webkit-box-shadow: 0 0 4px #BBBBBB;
        border-radius: 3px;
        -moz-border-radius: 3px;
        -webkit-border-radius: 3px;
        overflow: hidden;
        position: relative;
        text-align: center;
        cursor: pointer;
        background: #fff;
        font-size: 9pt;
    }
	div.productlisting img {
		max-height: 80px;
		display: block;
		margin: 1px auto;
	}
    p.brand {
        padding: 2px 0px;
        background-color: lavender;
        margin-bottom: 1px;
    }
    p.sku{
        text-align: right;
        font-size: 8pt;
        border-top: 1px dotted #ccc;
        padding: 4px 0px;
        margin-top: 4px;
        color: #7C7C7C;
        position: absolute;
        bottom: 0px;
        right: 2px;
        width: 100%;
        height: 8pt;
        overflow: hidden;
        background-color:#fff;
    }
</style>
<?php $this->headScript()->appendFile($this->websiteUrl . 'system/js/external/chosen/chosen.jquery.min.js'); ?>
<?php $this->headScript()->appendFile($this->websiteUrl . 'system/js/external/jquery/plugins/lazyload/jquery.lazyload.min.js'); ?>
<?php $this->headScript()->appendFile($this->websiteUrl . 'system/js/external/waypoints/waypoints.min.js'); ?>
<?php echo $this->headScript(); ?>
<script type="text/javascript" charset="utf-8">
    $(function() {
	    // uiTab object
	    var uiTab = {
		    offset: 0,
		    init: function() {
				//init chosen plugin
			    $('.pselect').chosen();
			    //init jqueryui button
			    $('#btn-create').button();
			    $('.ui-tabs-nav-item a').click(this.launch);
			    $(document).on('click', '.currproduct', this.insertSingleProduct)
			        .on('click', '#btn-create', this.insertList);
			    $('.pselect').chosen().change(function() {
					if(!$('#categories').val() && !$('#brands').val()) {
						uiTab.offset = 0;
					}
				    uiTab.loadStoreData('product', true)
			    });
		    },
		    launch: function() {
			    $('#product-products').html('');
			    $('ul.chzn-choices').removeClass('ui-corner-top').addClass('ui-corner-all');
			    var children = $(this).find('span#products');
			    if(!children.length) {
                    $('.above-editor-links').switchClass('grid_5', 'grid_8');
                    $('#tabs').switchClass('grid_7', 'grid_4');
                    $('tr.mceFirst').show();
                } else {
				    $('.above-editor-links').switchClass('grid_8', 'grid_3');
                    $('#tabs').switchClass('grid_4', 'grid_9');
                    //hiding mce controls
                    $('tr.mceFirst').hide();
                    $('#tabs-frag-3').addClass('h450');
                    $('table#content_tbl').width('230px');
                    $('table#content_tbl').height('475px');
                    //loading store data
				    uiTab.loadStoreData('categories');
				    uiTab.loadStoreData('brands');
				    uiTab.loadStoreData('product')
			    }
		    },
		    insertSingleProduct: function() {
			    var template = $('#templates').val();
                if(template == 0) {
                    showMessage('Product template is missing. Please select a product listing template', true);
                    return false;
                }
                $('textarea.tinymce').tinymce().execCommand('mceInsertContent',false, '{$product:' + $(this).attr('id') + ((template) ? ':' + template : '') + '}');
		    },
		    insertList: function() {
			    var shortCode = '{$productlist:';
                if($('#templates').val() == 0) {
                    showMessage('Product template is missing. Please select a product listing template', true);
                    return false;
                }
                //listing template
                shortCode += $('#templates').val();
                //categories filter
                shortCode += (($('#categories').val() != null) ? ':categories-' + $('#categories').val() : '');
                //brands filter
                shortCode += (($('#brands').val() != null) ? ':brands-' + $('#brands').val() : '');
                //ordering
                shortCode += (($('#ordering').val() != null) ? ':order-' + $('#ordering').val() : '') + '}';
                $('textarea.tinymce').tinymce().execCommand('mceInsertContent', false, shortCode);
		    },
		    loadStoreData : function(dataType, filter) {
                showSpinner();
                //if data type already loaded - return
                if($('#' + dataType + ' option').length) {
                    return false;
                }
                var utab = this;
			    $.getJSON('<?php echo $this->websiteUrl; ?>plugin/shopping/run/getdata/type/' + dataType,
				    this.getParams(filter),
				function(response) {
                    if(response.length) {
                        switch(dataType) {
                            case 'categories':
                            case 'brands':
	                        	uiTab.parseCategoriesAndBrands(response, dataType);
                            break;
                            case 'product':
	                            //console.log(!$('#categories').val(), !$('#brands').val());
	                            uiTab.parseProducts(response, filter);
								if(!$('#categories').val() && !$('#brands').val()) {
		                            $('.productlisting:last-child').waypoint(function() {
										$(this).waypoint('remove');
										utab.offset += 30;
										uiTab.loadStoreData('product')
									},
									{
										context: '#product-products',
										offset : '95%'
									});
								}
                            break;
                        }
                        $('.pselect').trigger("liszt:updated");
                    } else if(typeof filter != 'undefined' && filter) {
	                    $('#product-products').empty();
                    }
					hideSpinner();
                });

            },
		    getParams: function(filter) {
			    var data = {};
			    if(typeof this.offset != 'undefined') {
				    data.offset = this.offset;
			    }
			    if(typeof this.limit != 'undefined') {
                    data.limit = this.limit;
                }
                if(typeof filter != 'undefined' && filter) {
                    data.fcat = $('#categories').val();
                    data.fbrand = $('#brands').val();
                }
			    return data;
		    },
		    parseCategoriesAndBrands: function(catBrandResponse, dataType) {
               $.each(catBrandResponse, function() {
                   $('#' + dataType).append(
                       $('<option></option>').val((dataType == 'categories') ? this.id : this.name).text(this.name)
                   );
               });
		    },
		    parseProducts: function(productsResponse, filter) {
			    var productsContainer = $('#product-products');
			    if((typeof filter != 'undefined' && filter) || !productsResponse.length) {
				    $(productsContainer).empty();
			    }
			    //media servers
			    var mediaServers = <?php echo Tools_Content_Tools::getMediaServers(true); ?>;
			    var srcPart      = '<?php echo $this->websiteUrl;?>';
			    $.each(productsResponse, function() {
				    var srcPart = '<?php echo $this->websiteUrl;?>';
			        <?php if($this->mediaServersAllowed): ?>
	                    srcPart = srcPart.replace('<?php echo $this->websiteData['url']; ?>', mediaServers[Math.floor(Math.random()*mediaServers.length)]  + '.<?php echo $this->domain; ?>');
	                <?php endif; ?>
                    productItem = '<div class="productlisting"><a href="javascript:;" class="currproduct" id="' + this.id + '"  title="' + this.name + '">' +
                                '<p class="brand">' + this.brand + '</p>' +
                                '<img class="lazy" src="" data-original="' + srcPart + 'media/' + this.photo.replace('/', '/product/') + '" alt="' + this.name + '"><p>' + this.name + '</p></a><p class="sku">' + this.sku + '</p></div>';
	                $(productsContainer).append(productItem);
	                hideSpinner();
                });
                $('img.lazy').lazyload({
                    container: $(productsContainer),
                    effect: 'fadeIn'
                });
		    }
	    };
	    // end uiTab
	    uiTab.init();
    });
</script>
