<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title><?php echo $this->translate('Manage taxes'); ?></title>
        <?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/css/reset.css')
                ->appendStylesheet($this->websiteUrl . 'system/css/grid.css')
                ->appendStylesheet($this->websiteUrl . 'system/uithemes/seotoasterui/seotoasterui.css')
                ->appendStylesheet($this->websiteUrl . 'system/css/seotoaster.css')
                ->appendStylesheet($this->websiteUrl . 'system/js/external/smoke/smoke.css')
                ->appendStylesheet($this->websiteUrl . 'system/js/external/smoke/themes/toaster.css'); ?>
        <?php echo $this->headLink(); ?>

        <?php
            $this->headScript()->setAllowArbitraryAttributes(true)
                    ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js')
                    ->appendFile('https://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js')
                    ->appendFile($this->websiteUrl.'system/js/external/jquery/plugins/tmpl/jquery.tmpl.min.js')
                    ->appendFile($this->websiteUrl . 'system/js/internal/system.js')
                    ->appendFile($this->websiteUrl.'system/js/external/smoke/smoke.min.js')
                    ->appendFile($this->websiteUrl.'plugins/shopping/web/js/libs/require/require.js', null, array('data-main' => $this->websiteUrl.'plugins/shopping/web/js/zones.js'));
            echo $this->headScript();
        ?>

		<script id="zoneTemplate" type="text/x-jquery-tmpl">
			<div class="grid_6 suffix_6 mb10px">
				<div>
					<label for="">Zone Name:</label>
					<input type="text" class="zone-name" value="${name}" placeholder="enter name for zone"/>
				</div>
			</div>
			<div class="countries grid_6">
				<div class="ui-widget-header ui-corner-top padding5px">
                    <span class="padding5px">Countries</span>
                    <a href="javascript:;" class="clearprop" data-property="countries">[ clear ]</a>
                </div>
				<ul class="ui-widget-content zone-countries" style="height: 140px; overflow-y: auto; background:#fff; margin:0;">
                </ul>
				<div class="ui-widget-header ui-corner-bottom" style="text-align: center">
					<button class="open-dialog" data-name="add-country">Add Country</button>
<!--					<button>Add Region</button>-->
				</div>
			</div>
			<div class="states grid_6">
				<div class="ui-widget-header ui-corner-top padding5px">
                    <span class="padding5px">States</span>
                    <a href="javascript:;" class="clearprop" data-property="states">[ clear ]</a>
                </div>
				<ul class="ui-widget-content zone-states" style="height: 140px; overflow-y: auto; background:#fff; margin:0;">
				</ul>
				<div class="ui-widget-header ui-corner-bottom" style="text-align: center">
					<button class="open-dialog" data-name="add-state">Add State</button>
<!--					<button>Add Region</button>-->
				</div>
			</div>
			<div class="grid_12 mt10px">
                <div class="ui-widget-header ui-corner-top padding5px">
                    <span class="padding5px">Postal codes</span>
                    <a href="javascript:;" class="clearprop" data-property="zip">[ clear ]</a>
                    <span style="font-weight:normal; margin-left:160px;">Insert list of zip/postal codes: one per line</span>
                </div>
                    <div class="ui-widget-content" style="height: 180px; overflow-y: auto; text-align: center">
                    <textarea style="width: 99%; height: 160px; resize: none;" class="zone-zip">${zip.join('\n')}</textarea>
				</div>
			</div>
		</script>

        <style>
        #zones.ui-tabs .ui-tabs-panel {
            padding: 10px 5px;
            overflow: hidden;
            background: #DAE8ED;
        }
        #zones .ui-tabs-nav li.ui-tabs-selected {
            background: #DAE8ED;
        }
        #add-country-dialog {
            padding: 0;
        }
        li.entry-row .ui-icon {
            float:right;
            cursor: pointer;
        }
        li.entry-row .ui-icon:hover {
            background-image: url("/system/uithemes/seotoasterui/images/ui-icons_cd0a0a_256x240.png");
        }
        #ajax_msg {
            line-height: 50px;
            position: absolute;
            top: 30%;
            left:0;
            width: 100%;
            z-index: 5000;
        }
        </style>
	</head>
    <body>
        <noscript style="width: 100%; height: 100%; position: fixed; display: block; background: white; font-size: 150%; text-align: center; padding-top: 30%;">
        JavaScript must be enabled at this point.<br/>
        <a href="http://www.seotoaster.com/">seotoaster.com</a>
        </noscript>
        <input type="hidden" id="pluginUrl" name="pluginUrl" value="<?php echo trim($this->websiteUrl, ' /').$this->url(array('run'=>''));?>" />
        <input type="hidden" id="websiteUrl" name="websiteUrl" value="<?php echo $this->websiteUrl;?>" />
        <div id="ajax_msg" class="smoke">
            <img src="<?php echo $this->websiteUrl; ?>/system/images/loading.gif" /><?php echo $this->translate('Loading');?>...
        </div>
        <div class="seotoaster container_12 rounded3px" id="manage-zones">
            <div id="zones" class="ui-helper-clearfix h530">
                <div class="closebutton"><span class="close"><?php echo $this->translate('Close'); ?></span></div>
                <ul><button id="new-zone-btn" title="Hotkey: Ctrl+N" ><?php echo $this->translate('Add new');?></button></ul>
			</div>

            <a id="delete-zone" href="javascript:;" style="margin-left:20px; color: #8b0000; font-weight: bold;">[ <?php echo $this->translate('Delete this zone'); ?> ]</a>
            <button id="save-btn" title="Hotkey: Ctrl+S" style="margin: 0 10px 10px 0;"><?php echo $this->translate('Save');?></button>
		</div>

        <div class="ui-helper-hidden">
            <div id="add-country-dialog" title="Add country">
                <ul tabindex="0" id="country-list" class="ui-helper-clearfix" style="height: 200px; overflow-x:hidden;overflow-y: auto; background: lavender;">
                </ul>
                <div class="ui-widget-header padding5px" style="text-align:center;">
                    <span class="ui-icon ui-icon-search" style="display: inline-block"></span>
                    <input id="country-filter" type="text" placeholder="<?php echo $this->translate('Start typing country name here');?>" size="30" />
                </div>
            </div>

            <div id="add-state-dialog" style="margin-top: -5px; padding: 0;">
                <div class="ui-widget-header padding5px">
                    <?php echo $this->translate('Select country');?>:
                    <select id="state-filter">
                        <option value="0" selected="selected"><?php echo $this->translate('all');?></option>
                    </select>
                </div>
                <ul id="state-list" class="ui-helper-clearfix" style="height: 300px; overflow-x:hidden;overflow-y: auto; background: lavender;">
                </ul>
            </div>
        </div>
    <script>
        $(function(){
            $('#zones').tabs();
        });
    </script>
    </body>
</html>
