<?php
$this->headScript()
    ->appendFile($this->websiteUrl.'system/js/external/jquery/plugins/tmpl/jquery.tmpl.min.js')
    ->appendFile($this->websiteUrl . 'plugins/shopping/web/js/libs/require.min.js',
        null,
        array('data-main' => $this->websiteUrl . 'plugins/shopping/web/js/zones.js')
    );

$this->headLink()
    ->appendStylesheet($this->websiteUrl . 'plugins/shopping/web/css/store.css');
?>

<script id="zoneTemplate" type="text/x-jquery-tmpl">
	<div class="grid_6 alpha suffix_6 mb10px">
		<label class="grid_3 alpha omega mt5px"><?php echo $this->translate( 'Zone Name' ); ?>:</label>
		<input type="text" class="zone-name grid_9 omega" value="<%= name %>" placeholder="enter name for zone"/>
	</div>
	<div class="countries grid_6 alpha">
		<div class="header-inner pl2 pr2">
            <?php echo $this->translate( 'Countries' ); ?>
        </div>
		<ul class="zone-countries list-bordered h150px"></ul>
        <div class="footer grid_12">
            <a href="javascript:;" class="clearprop error" data-property="countries">[ <?php echo $this->translate( 'clear' ); ?> ]</a>
            <button class="btn ticon-plus open-dialog fl-right" data-name="add-country"><?php echo $this->translate( 'Add Country' ); ?></button>
        </div>
	</div>
	<div class="states grid_6 omega">
		<div class="header-inner pl2 pr2">
            <?php echo $this->translate( 'States' ); ?>
        </div>
		<ul class="zone-states list-bordered h150px"></ul>
        <div class="footer grid_12">
            <a href="javascript:;" class="clearprop error" data-property="states">[ <?php echo $this->translate( 'clear' ); ?> ]</a>
            <button class="btn ticon-plus open-dialog fl-right" data-name="add-state"><?php echo $this->translate( 'Add State' ); ?></button>
        </div>
	</div>
	<div class="grid_12 alpha omega mt15px">
        <div class="header-inner pl2 pr2 text-center">
            <span class="fl-left"><?php echo $this->translate( 'Postal codes' ); ?></span>
            <a href="javascript:;" class="clearprop fl-right error" data-property="zip">
                [ <?php echo $this->translate( 'clear' ); ?> ]
            </a>
            <em><?php echo $this->translate( 'Insert list of zip/postal codes: one per line' ); ?></em>
        </div>
        <textarea class="zone-zip"><%= zip . join( '\n' ) %></textarea>
	</div>
</script>

<div id="manage-zones" class="seotoaster container">
    <?php
    echo $this->partial(
        'admin' . DIRECTORY_SEPARATOR . '_header.phtml',
        array(
//            'headerText'  => $this->translate('Shipping configuration'),
            'helpSection' => $this->helpSection,
            'hashMap'     => Tools_Misc::$_helpHashMap
        )
    );
    ?>
    <div id="zone">
        <div class="tabs-nav-wrap">
        <span class="arrow left ticon-arrow-left3"></span>
        <span class="arrow right ticon-arrow-right3"></span>
        <ul class="header">
            <li class="add-new-zone">
                <a id="new-zone-btn" class="ui-tabs-anchor ticon-plus icon16" title="Hotkey: Ctrl+N"></a>
            </li>
        </ul>
        </div>
    </div>
    <div class="footer grid_12">
        <a id="delete-zone" class="delete-selected error" href="javascript:;">[ <?php echo $this->translate( 'Delete this zone' ); ?> ]</a>
        <button id="save-btn" class="btn ticon-save" title="Hotkey: Ctrl+S"><?php echo $this->translate( 'Save' ); ?></button>
    </div>

    <div class="ui-helper-hidden">
        <div id="add-country-dialog" title="<?php echo $this->translate( 'Add country' ); ?>">
            <ul id="country-list" class="list-bordered mt10px h200px" tabindex="0"></ul>
            <div class="footer labeled icon right">
                <input id="country-filter" type="text" placeholder="<?php echo $this->translate( 'Start typing country name here' ); ?>" size="30"/>
                <span class="ticon-search"></span>
            </div>
        </div>

        <div id="add-state-dialog" class="form" title="<?php echo $this->translate( 'Add state' ); ?>">
            <label class="grid_3 alpha mt15px"><?php echo $this->translate( 'Filter by country' ); ?>:</label>
            <select id="state-filter" class="grid_9 alpha omega mt10px">
                <option value="0" selected="selected"><?php echo $this->translate( 'all' ); ?></option>
            </select>
            <ul id="state-list" class="list-bordered mt10px grid_12 alpha omega"></ul>
        </div>
    </div>
    <input type="hidden" name="system-language" value="<?php echo Tools_Misc::getJsTranslationLanguage();?>"/>

</div>
<script>
<?php $this->jQuery()->onLoadCaptureStart();?>
$('#zone').tabs();
$(document).one('zones:loaded', function () {
    app.states.reset(<?php echo Zend_Json::encode($this->states); ?>);
    app.countries.reset(<?php echo Zend_Json::encode($this->countries); ?>);
    app.view.zonesCollection.reset(<?php echo Zend_Json::encode($this->zones); ?>);
    $('#add-country-dialog').dialog({
        modal     : true,
        autoOpen  : false,
        resizable : false,
        height    : 310,
        width     : 500,
        create    : function () {
            app.views.countryList.collection = _(app.countries.toJSON()).sortBy(function (c) {
                return c.name.toLowerCase()
            });
            app.views.countryList.render();
        },
        close     : function (event, ui) {
            $('#country-filter').val('');
            $('#country-list > li').show();
        }
    });
    $('#add-state-dialog').dialog({
        modal     : true,
        autoOpen  : false,
        resizable : false,
        height    : 310,
        width     : 500,
        create    : function () {
            app.views.statesList.collection = app.states.toJSON();
            app.views.statesList.render();
        }
    });
    hideSpinner();
});
<?php $this->jQuery()->onLoadCaptureEnd();?>
</script>