define({
     "root": {
        'cs_new'          : 'Abandoned carts',
        'cs_completed'    : 'Payment Received',
        'cs_shipped'      : 'Items Shipped',
        'cs_refunded'     : 'Refunded purchase',
        'cs_pending'  	  : 'Merchant action required -  Customer charged',
	    'cs_processing'	  : 'Technical processing  - Customer not charged',
	    'cs_delivered'	  : 'Items delivered',
	    'cs_canceled'	  : 'canceled',
        'cs_error'        : 'error',
        'Mark order paid' : 'Mark order paid',
	    'Refund payment'  : 'Refund payment',
	    'Cancel order'	  : 'Cancel order',
	    'Delivered'	      : 'Delivered',
        'Last'            : 'Last',
        'Next'            : 'Next',
        'orders found'    : 'orders found',
        'Total'           : 'Total',
        'Previous'        : 'Previous',
        'First'           : 'First',
        'add'             : 'add',
        'edit'            : 'edit',
        'view'            : 'view',
        'Tracking ID'     : 'Tracking ID',
        'View invoice'    : 'View invoice',
        'Download invoice': 'Download invoice',
        'Insert tracking code for this order' : 'Insert tracking code for this order',
        'OK'              : 'OK',
        'Cancel'          : 'Cancel',
        'Saved'           : 'Saved',
        'products found'  : 'products found',
        'yes'             : 'yes',
        'no'              : 'no',
        'Apply to all'    : 'Apply to all',
        'products'        : 'products',
        'select brand'    : 'select brand',
        'Assign brand'    : 'Assign brand',
        'or create new'   : 'or create new',
        'Assign product page template' : 'Assign product page template',
        'Apply'           : 'Apply',
        'Assign tax'      : 'Assign tax',
        'Select tax category' : 'Select tax category',
        'Non taxable'     : 'Non taxable',
        'Default'         : 'Default',
        'Alternative'     : 'Alternative',
        'Assign free shipping' : 'Assign free shipping',
        'select'          : 'select',
        'no free shipping': 'no free shipping',
        'free shipping'   : 'free shipping',
        'Manage tags'     : 'Manage tags',
        'Delete products' : 'Delete products',
        'Are you sure'    : 'Are you sure',
        'This operation cannot be undone' : 'This operation cannot be undone',
        'Enable'          : 'Enable',
        'Disable'         : 'Disable',
        'Enable/Disable products' : 'Enable/Disable products',
        'No product page templates found' : 'No product page templates found',
        'Changed'         : 'Changed',
        'Group saved'     : 'Group saved',
        'Change password for clients?' : 'Change password for clients?',
        'Unable to remove following users' : 'Unable to remove following users',
        'Users deleted'   : 'Users deleted',
        'Assign group'    : 'Assign group',
        'select group'    : 'select group',
        'Apply to all customers' : 'Apply to all customers',
        'New quote' : 'New quote',
        'Quote Sent' :'Quote Sent',
        'Lost opportunity' : 'Lost opportunity',
        'Please save product information first' : 'Please save product information first',
        'Tag name should contain only letters, digits and spaces' : 'Tag name should contain only letters, digits and spaces',
        'Product saved.' : 'Product saved.',
        'Go to your search engine optimized product landing page here.' : 'Go to your search engine optimized product landing page here.',
        'Missing some required fields' : 'Missing some required fields',
        'Please, select product page template before saving' : 'Please, select product page template before saving',
        'Product is not saved yet' : 'Product is not saved yet',
        'Product deleted' : 'Product deleted',
        'Forbidden action' : 'Forbidden action',
        'Can\'t remove products' : 'Can\'t remove products',
        'Products removed' : 'Products removed',
        'Input new value' : 'Input new value',
        'View packing slip' : 'View packing slip',
        'Download packing slip' : 'Download packing slip',
        'Wait a minute! this country is already part of another zone... Add anyway?':'Wait a minute! this country is already part of another zone... Add anyway?'
    }
});
