define({
    "root": {
        'Original total': 'Precio original',
        'Export orders' : 'Exportar pedidos',
        'cs_new'          : 'Carros abandonados',
        'cs_completed'    : 'Pago recibido',
        'cs_shipped'      : 'Productos enviados',
        'cs_refunded'     : 'Pago rechazado',
        'Merchant action required -  Customer charged'     : 'Acción del comerciante requerida - cliente cobrado',
        'Technical processing  - Customer not charged'     : 'Procesamiento técnico - cliente no cobrado',
        'cs_pending'  	  : 'acción del comerciante requerida - cliente cobrado',
        'cs_processing'	  : 'procesamiento técnico - cliente no cobrado',
        'cs_delivered'	  : 'Productos entregados',
        'cs_canceled'	  : 'Cancelado',
        'cs_error'        : 'Error',
        'New quote'       : 'Nuevo presupuesto',
        'Quote Sent'      : 'Presupuesto enviado',
        'Mark order paid' : 'Marcar presupuesto como pagado',
        'Refund payment'  : 'Devolver pago',
        'Cancel order'	  : 'Cancelar pedido',
        'Delivered'	      : 'Entregado',
        'Last'            : 'Fin',
        'Next'            : 'Siguiente',
        'orders found'    : 'pedidos encontrados',
        'Total'           : 'Total',
        'Previous'        : 'Anterior',
        'First'           : 'Inicio',
        'add'             : 'añadir',
        'edit'            : 'editar',
        'view'            : 'ver',
        'Tracking ID'     : 'ID Envío',
        'View invoice'    : 'Ver factura',
        'Download invoice': 'Descargar factura',
        'Insert tracking code for this order' : 'Establecer identificador de envío',
        'OK'              : 'OK',
        'Cancel'          : 'Cancelar',
        'Saved'           : 'Guardado',
        'Save'            : 'Guardar',
        'products found'  : 'productos encontrados',
        'yes'             : 'sí',
        'Yes'             : 'Sí',
        'no'              : 'no',
        'No'              : 'No',
        'Apply to all'    : 'Aplicar a todos',
        'products'        : 'productos',
        'select brand'    : 'seleccionar marca',
        'Assign brand'    : 'Asignar marca',
        'or create new'   : 'crear una nueva',
        'Assign product page template' : 'Asignar producto a plantilla de página',
        'Apply'           : 'Aplicar',
        'Assign tax'      : 'Establecer impuestos',
        'Select tax category' : 'Seleccionar impuestos',
        'Non taxable'     : 'Sin impuestos',
        'Default'         : 'Por defecto',
        'Alternative'     : 'Alternativo',
        'Assign free shipping' : 'Asignar envío gratis',
        'select'          : 'seleccionar',
        'no free shipping': 'sin envío gratis',
        'free shipping'   : 'con envío gratis',
        'Manage tags'     : 'Gestionar tags',
        'Delete products' : 'Eliminar productos',
        'Are you sure'    : '¿Estas seguro?',
        'This operation cannot be undone' : 'Esta operación no se puede deshacer',
        'Enable'          : 'Activar',
        'Disable'         : 'Desactivar',
        'Enable/Disable products' : 'Activar/desactivar productos',
        'No product page templates found' : 'No se han encontrado plantillas de productos',
        'Changed'         : 'Modificado',
        'Group saved'     : 'Grupo guardado',
        'Change password for clients?' : '¿Cambiar contraseña de clientes?',
        'Unable to remove following users' : 'No se pueden eliminar los siguientes usuarios',
        'Users deleted'   : 'Usuarios eliminados',
        'Assign group'    : 'Asignar grupo',
        'select group'    : 'seleccionar grupo',
        'Apply to all customers' : 'Aplicar a todos los clientes',
        'Lost opportunity' : 'Oportunidad perdida',
        'Please save product information first' : 'Por favor, guarde la información de producto',
        'Tag name should contain only letters, digits and spaces' : 'El nombre del tag sólo puede contener letras, números o espacios en blanco',
        'Product saved.' : 'Producto guardado',
        'Go to your search engine optimized product landing page here.' : 'Producto Guardado. Ver la a página de producto aquí',
        'Missing some required fields' : 'Existen campos obligatorios pendientes de rellenar',
        'Please, select product page template before saving' : 'Por favor, seleccione una plantilla de producto antes de guardar',
        'Product is not saved yet' : 'Producto no guardado',
        'Product deleted' : 'Producto borrado',
        'Forbidden action' : 'Acción desconocida',
        'Can\'t remove products' : 'No es posible eliminar estos productos',
        'Products removed' : 'Productos eliminados',
        'Input new value' : 'Escribir',
        'View packing slip' : 'Ver etiqueta de envío',
        'Export all orders matching filter' : 'Exportar la selección de pedidos',
        'Download packing slip' : 'Descargar etiqueta de envío',
        'Wait a minute! this country is already part of another zone... Add anyway?':'Atención, este país ya forma parte de otra zona. ¿Añadir de todas formas?',
        'There are no users for export' : 'No hay usuarios que exportar',
        'Imported' : 'Importado',
        'Recurring' : 'Recurrente',
        'Regular' : 'Estándar',
        'Add as related' : 'Añadir como relacionado',
        'Delete selected' : 'Borrar seleccionado',
        'add to set' : 'establecer',
        'Enter amount to refund below' : 'Introduzca abajo la cantidad a devolver',
        'How much do you want to refund?' : '¿Qué cantidad quiere devolver?',
        'Tax rate' : 'Impuesto %',
        'Process refund now through payment processor' : 'Devolver a tarjeta de cliente',
        'Add a refund message (will show on client\'s credit card receipt)' : 'Añadir un mensaje a la devolución (se mostrará en el detalle de la devolución de la tarjeta del cliente)',
        'Refund order' : 'Devolver pedido',
        'Refund' : 'Realizar devolución',
        'Missing required fields' : 'Faltan campos oblogatorios por rellenar',
        'Please enter location' : 'Por favor, introduzca una dirección',
        'Missing required field' : 'Faltan campos oblogatori por rellenar',
        'Send invoice to user via email' : 'Enviar factura por email',
        'No data available in table' : 'No existen datos en esta tabla',
        'First page' : 'Inicio',
        'Last page' : 'Fin',
        'Next page' : 'Siguiente',
        'Previous page' : 'Anterior',
        'Generate shipping label' : 'Generar etiqueta de envio',
        'Do you want to specify shipment date?' : '¿Quiere especificar la fecha de envío?',
        'Do you want to create a label?' : '¿Quiere crear una etiqueta?',
        'Do you want to use this date for the shipping label?' : '¿Desea utilizar esta fecha de recogida en la etiqueta de envío?',
        'Create label' : 'Crear etiqueta',
        'Please specify shipment date' : 'Por favor especificar la fecha de envío',
        'Please specify shipment time' : 'Por favor especificar la hora de envío',
        'Export' : 'Exportar',
        'Are you sure you want to change status for this order?' : '¿Desea cambiar de estado este pedido?',
        'Invoice has been sent' : 'Factura enviada',
        'Shipment availability dates' : 'Fechas de recogida disponibles',
        'for order' : 'para pedido',
        'Summary of delivery' : 'Resumen de dias',
        'Date' : 'Fecha',
        'Order' : 'Pedido',
        'Time' : 'Hora',
        'Shipment price' : 'Precio de envío',
        'Include Tax' : 'Inpuestos incluidos',
        'Shipping service does not support shipment label creation' : 'El Servicio de entregas no permite la creación de etiquetas de envío',
        'Are you sure you want to refund this payment?' : '¿Estas seguro que quieres el rembolso de este pago?',
        'Are you sure?' : '¿Está seguro?',
        'No available services' : 'Servicio no disponible',
        'Refund shipment order' : 'Solicitar anulación de etiqueta.',
        'Do you want to delete it?' : '¿Desea eliminarlo?',
        'Select a brand' : 'Selecciona marca',
        'Do you want delete file?' : '¿Desea eliminar el fichero?',
        'Are you sure want to delete?' : '¿Desea eliminarlo?',
        'Oh man... Really?' : '¿Estas seguro?',
        'Do you really want to delete this column? (Data will be deleted!)' : '¿Desea eliminar la columna? ( Datos serán borrados)',
        'This product was sold. Do you really want to delete this file?' : '¿Producto vendido. Desea eliminar el fichero?',
        'Digital products found' : 'Productos digitales encontrados',
        'discount' : 'descuento'
    }
});