define({
    "root": {
        'cs_new'          : 'Panier abandonné',
        'cs_completed'    : 'Paiement reçu',
        'cs_shipped'      : 'Livraison en cours',
        'cs_refunded'     : 'Achat remboursé',
        'cs_pending'  	  : 'Action requise par vendeur',
	    'cs_processing'	  : 'Processus en cours',
	    'cs_delivered'	  : 'Livraison effectuée',
	    'cs_canceled'	  : 'Commande annulée',
        'cs_error'        : 'erreur',
        'Customer charged': 'Client chargé',
        'Customer not charged' : 'Client non chargé',
	    'Mark order paid' : 'Recevoir paiement',
	    'Refund payment'  : 'Rembourser client',
	    'Cancel order'	  : 'Annuler commande',
	    'Delivered'	      : 'Commande livré',
        'Last'            : 'Dernier',
        'Next'            : 'Suivant',
        'orders found'    : 'commandes trouvées',
        'Total'           : 'Total',
        'Previous'        : 'Précédent',
        'First'           : 'Première',
        'add'             : 'ajouter',
        'edit'            : 'editer',
        'view'            : 'voir',
        'Tracking ID'     : 'Numéro de suivi',
        'View invoice'    : 'Voir facture',
        'Download invoice': 'Télécharger facture',
        'Insert tracking code for this order' : 'Insérez le code de suivi de cette commande',
        'OK'              : 'OK',
        'Cancel'          : 'Annuler',
        'Saved'           : 'Sauvegardé',
        'products found'  : 'produits trouvés',
        'yes'             : 'Oui',
        'no'              : 'Non',
        'Apply to all'    : 'Appliquer a tous',
        'products'        : 'produits',
        'select brand'    : 'Sélectionnez une marque',
        'Assign brand'    : 'Attribuer marque',
        'or create new'   : 'ou ajouter',
        'Assign product page template' : 'Assigner le modèle de page produit',
        'Apply'           : 'Appliquer',
        'Assign tax'      : 'Attribuer TVA',
        'Select tax category' : 'Sélectionner le taux de taxe',
        'Non taxable'     : 'Non imposable',
        'Default'         : 'Par défaut',
        'Alternative'     : 'Alternative',
        'Assign free shipping' : 'Attribuer la livraison gratuite',
        'select'          : 'sélectionner',
        'no free shipping': 'pas d‘envoi gratuit',
        'free shipping'   : 'livraison gratuite',
        'Manage tags'     : 'Gérer les tags',
        'Delete products' : 'Effacer les produits',
        'Are you sure'    : 'Etes-vous sûr',
        'This operation cannot be undone' : 'This operation cannot be undone',
        'Enable'          : 'Activer',
        'Disable'         : 'Désactiver',
        'Enable/Disable products' : 'Activer / Désactiver produits',
        'No product page templates found' : 'Aucun modèle de page produit',
        'Changed'         : 'Modifié',
        'Group saved'     : 'Groupe sauvegardé',
        'Change password for clients?' : 'Change password for clients?',
        'Unable to remove following users' : 'Incapable d’effacer les utilisateurs suivants',
        'Users deleted'   : 'Utilisateurs effacés',
        'Assign group'    : 'Assigner un groupe',
        'select group'    : 'Sélectionner un groupe',
        'Apply to all customers' : 'Appliquer a tous les clients',
        'Lost opportunity' : 'Opportunité perdu',
        'Please save product information first' : 'Please save product information first',
        'Tag name should contain only letters, digits and spaces' : 'Tag name should contain only letters, digits and spaces',
        'Product saved.' : 'Product saved.',
        'Go to your search engine optimized product landing page here.' : 'Go to your search engine optimized product landing page here.',
        'Missing some required fields' : 'Missing some required fields',
        'Please, select product page template before saving' : 'Please, select product page template before saving',
        'Product is not saved yet' : 'Product is not saved yet',
        'Product deleted' : 'Product deleted',
        'Forbidden action' : 'Forbidden action',
        'Can\'t remove products' : 'Can\'t remove products',
        'Products removed' : 'Products removed'


    }
});
