define({
    "root": {
        'cs_new'          : 'Panier abandonné',
        'cs_completed'    : 'Paiement reçu',
        'cs_shipped'      : 'Livraison en cours',
        'cs_refunded'     : 'Achat remboursé',
        'cs_pending'  	  : 'Action requise par vendeur - Carte débitée',
	    'cs_processing'	  : 'Processus en cours - Carte non débitée',
	    'cs_delivered'	  : 'Livraison effectuée',
	    'cs_canceled'	  : 'Commande annulée',
        'cs_error'        : 'erreur',
        'cs_partial'      : 'Partial Order',
        'New quote'       : 'Nouveau devis',
        'Quote Sent'      : 'Devis envoyé',
	    'Mark order paid' : 'Recevoir paiement',
	    'Refund payment'  : 'Rembourser client',
	    'Cancel order'	  : 'Annuler commande',
	    'Delivered'	      : 'Commande livré',
        'Last'            : 'Dernier',
        'Next'            : 'Suivant',
        'orders found'    : 'commandes trouvées',
        'Total'           : 'Total',
        'Previous'        : 'Précédent',
        'First'           : 'Première',
        'add'             : 'ajouter',
        'edit'            : 'editer',
        'view'            : 'voir',
        'Tracking ID'     : 'Numéro de suivi',
        'View invoice'    : 'Voir facture',
        'Download invoice': 'Télécharger facture',
        'Insert tracking code for this order' : 'Insérez le code de suivi de cette commande',
        'OK'              : 'OK',
        'Cancel'          : 'Annuler',
        'Saved'           : 'Sauvegardé',
        'products found'  : 'produits trouvés',
        'yes'             : 'Oui',
        'no'              : 'Non',
        'Apply to all'    : 'Appliquer a tous',
        'products'        : 'produits',
        'select brand'    : 'Sélectionnez une marque',
        'Assign brand'    : 'Attribuer marque',
        'or create new'   : 'ou ajouter',
        'Assign product page template' : 'Assigner le modèle de page produit',
        'Apply'           : 'Appliquer',
        'Assign tax'      : 'Attribuer TVA',
        'Select tax category' : 'Sélectionner le taux de taxe',
        'Non taxable'     : 'Non imposable',
        'Default'         : 'Par défaut',
        'Alternative'     : 'Alternative',
        'Assign free shipping' : 'Attribuer la livraison gratuite',
        'select'          : 'sélectionner',
        'no free shipping': 'pas d‘envoi gratuit',
        'free shipping'   : 'livraison gratuite',
        'Manage tags'     : 'Gérer les tags',
        'Delete products' : 'Effacer les produits',
        'Are you sure'    : 'Etes-vous sûr',
        'This operation cannot be undone' : 'This operation cannot be undone',
        'Enable'          : 'Activer',
        'Disable'         : 'Désactiver',
        'Enable/Disable products' : 'Activer / Désactiver produits',
        'No product page templates found' : 'Aucun modèle de page produit',
        'Changed'         : 'Modifié',
        'Group saved'     : 'Groupe sauvegardé',
        'Change password for clients?' : 'Change password for clients?',
        'Unable to remove following users' : 'Incapable d’effacer les utilisateurs suivants',
        'Users deleted'   : 'Utilisateurs effacés',
        'Assign group'    : 'Assigner un groupe',
        'select group'    : 'Sélectionner un groupe',
        'Apply to all customers' : 'Appliquer a tous les clients',
        'Lost opportunity' : 'Opportunité perdu',
        'Please save product information first' : 'Sauvegarder d’abord la fiche produit',
        'Tag name should contain only letters, digits and spaces' : 'Les tags doivent contenir uniquement des lettres, nombres ou espaces.',
        'Product saved.' : 'Produit sauvegardé.',
        'Go to your search engine optimized product landing page here.' : 'Accéder a la page produit ici.',
        'Missing some required fields' : 'Tous les champs obligatoires doivent être renseignés',
        'Please, select product page template before saving' : 'Sélectionner un modèle de page produit avant de sauvegarder SVP',
        'Product is not saved yet' : 'Le produit n’est pas encore sauvegardé',
        'Product deleted' : 'Produit effacé',
        'Forbidden action' : 'Action interdite',
        'Can\'t remove products' : 'Incapable d’effacer les produits',
        'Products removed' : 'Produits effacés',
        'Input new value' : 'Entrée nouvelle valeur',
        'View packing slip' : 'Voir bon de livraison',
        'Export all orders matching filter' : 'Exporter toutes les commandes correspondant au filtre',
        'Download packing slip' : 'Télécharger bon de livraison',
        'There are no users for export' : 'Il n\'y a pas d\'utilisateurs pour l\'exportation',
        'Export orders' : 'Exporter les commandes',
        'Your session has timed out. Please log again' : 'Votre session a expiré. Veuillez vous connecter à nouveau',
        'here' : 'ici',
        'Can\'t delete coupon!' : 'Impossible de supprimer le coupon',
        'Are you sure to delete?' : 'Êtes-vous sûr de vouloir supprimer?',
        'A coupon name can\'t contain gaps' : 'Le nom du coupon ne peut pas contenir des espaces',
        'Are you sure?' : 'Etes-vous d\'accord?',
        'Are you sure want to add all not in use countries?' : 'Etes-vous d\'accord d\'ajouter tous les pays non utilisés?',
        'Done. Don\'t forget to save zone' : 'C\'est fait. N\'oubliez pas de sauvegarder la zone',
        'Nothing to process. All countries are already added' : 'Rien à ajouter. Tous les pays ont été ajoutés avant',
        'Can\'t process countries' : 'Impossible d\'ajouter les pays',
        'Zone Name' : 'Nom de la zone',
        'enter name for zone' : 'introduire le nom de la zone',
        'Countries' : 'Pays',
        'clear' : 'supprimer',
        'Add all not in use' : 'Pays non utilisés',
        'Add Country' : 'Ajouer un pays',
        'States' : 'Etats',
        'Add State' : 'Ajouter un état',
        'Postal codes' : 'Code Postal',
        'Insert list of zip/postal codes: one per line' : 'Introduire la liste des codes postaux: un par ligne',
        'Wait a minute! this country is already part of another zone... Add anyway?' : 'Attendez une minute! Сe pays fait déjà partie d\'une autre zone... Ajouter tout de même?',
        'Line break' : 'Saut de ligne',
        'Line break <br>' : 'Saut de ligne <br>',
        'Paragraph' : 'Paragraphe',
        'Paragraph <p></p>' : 'Paragraphe <p></p>',
        'Wait a minute! this state is already part of another zone... Add anyway?' : 'Attendez une minute! Сe état fait déjà partie d\'une autre zone... Ajouter tout de même?',
        'Quote Signed (Signature only quote)':'Quote Signed (Signature only quote)',
        'Do you want to delete option from the library?' : 'Voulez-vous supprimer cette option de bibliothèque?',
        'Deleted' : 'Supprimé'
    }
});
