<p class="filter-header"><?php echo !empty($this->label) ? $this->label : $this->translate(ucfirst($this->name)); ?></p>
<ul>
    <?php
        $values = empty($this->nocount) ? $this->values : array_flip($this->values);
    ?>
    <?php foreach ($values as $value => $count) : ?>
        <li>
            <label>
                <input type="checkbox"
                       name="<?php echo $this->name; ?>"
                       value="<?php echo $value; ?>"
                    <?php if (in_array($value, $this->checked)) { ?>
                        checked
                    <?php } ?>
                    />
                <a href="<?php echo $this->url() . '?' . $this->name . '=' . urlencode($value); ?>">
                    <?php echo $value; ?><?php if(empty($this->nocount)) { echo '&nbsp[' . $count . ']'; } ?>
                </a>
            </label>
        </li>
    <?php endforeach; ?>
</ul>