<?php
$min = floor(floatval($this->min));
$max = ceil(floatval($this->max));

if(isset($this->priceTax) && !empty($this->priceTax)){
    $percentMin = ($this->min / 100) * $this->priceTax;
    $percentMax = ($this->max / 100) * $this->priceTax;
    $min = floor($this->min + $percentMin);
    $max = round($this->max + $percentMax);

    if(!empty($this->group)) {
        $min = floor($this->group['min']);
        $max = ceil($this->group['max']);
    }
}
$sliderType = $this->name;
?>
<p>
    <?php echo $this->translate('From'); ?>
    <?php
        $from =  !empty($this->from) ? $this->from : $min;
        $to =  !empty($this->to) ? $this->to : $max;
    ?>
    <span class="filter-from-<?php echo $sliderType; ?>"><?php echo $this->useCurrency ? $this->currency($from) : $from; ?></span>
    <?php echo $this->translate('to'); ?>
    <span class="filter-to-<?php echo $sliderType; ?>"><?php echo $this->useCurrency ? $this->currency($to) : $to; ?></span>
</p>
<div class="filter-slider"
     data-min="<?php echo $min; ?>"
     data-max="<?php echo $max; ?>"
    <?php if (!empty($this->from)) { ?> data-from="<?php echo $this->from; ?>" <?php } ?>
    <?php if (!empty($this->to)) { ?> data-to="<?php echo $this->to; ?>" <?php } ?>
    ></div>
<?php
if (isset($this->from) && isset($this->to)) {
    $filterRange = $this->from . '-' . $this->to;
} else {
    $filterRange = '';
}
?>
<input type="hidden" class="filter-value-<?php echo $sliderType; ?>" name="<?php echo $this->name; ?>" value="<?php echo $filterRange; ?>"/>
