<form class="plugin-filtering-widget plugin-filtering-wrap" action="<?php echo $this->url(); ?>" method="post">
    <input type="hidden" name="filterId" value="<?php echo $this->filterId; ?>"/>
    <h4><?php echo $this->translate('Filter Widget Builder'); ?></h4>
    <ul>
        <?php if (!empty($this->tags)) : ?>
            <li>
                <label class="filter-label">
                    <input type="hidden" name="show[tags]" value="none" />
                    <input type="checkbox" class="mass-change"
                           title="<?php echo $this->translate('toggle all'); ?>"
                        <?php if (empty($this->settings['tags']) || (is_array($this->settings['tags']) && sizeof($this->tags) === sizeof($this->settings['tags']) ) ) { ?>
                            checked
                        <?php } ?>
                        />
                    <?php echo $this->translate('Category'); ?>
                </label>
                <ul>
                    <?php foreach ($this->tags as $tag) : ?>
                        <li>
                            <label>
                                <input type="checkbox" name="show[tags][<?php echo $tag; ?>]" value="1"
                                    <?php if (empty($this->settings['tags']) || (is_array($this->settings['tags']) && isset($this->settings['tags'][$tag]))) { ?>
                                        checked
                                    <?php } ?>
                                    />
                                <?php echo $tag; ?>
                            </label></li>
                    <?php endforeach; ?>
                </ul>
            </li>
        <?php endif; ?>
        <?php if (!empty($this->brands)) : ?>
            <li>
                <label class="filter-label">
                    <input type="hidden" name="show[brands]" value="none" />
                    <input type="checkbox" class="mass-change" title="<?php echo $this->translate('toggle all'); ?>"
                        <?php if (empty($this->settings['brands']) || (is_array($this->settings['brands']) && sizeof($this->brands) === sizeof($this->settings['brands']) ) ) : ?>
                            checked
                        <?php endif; ?>
                        />
                    <?php echo $this->translate('Brands'); ?>
                </label>
                <ul>
                    <?php
                    $brands = array_keys($this->brands);
                    foreach ($brands as $brand) : ?>
                        <li>
                            <label>
                                <input type="checkbox" name="show[brands][<?php echo $brand; ?>]" value="1"
                                    <?php if (empty($this->settings['brands'])  || (is_array($this->settings['brands']) && isset($this->settings['brands'][$brand]))) : ?>
                                        checked
                                    <?php endif; ?>
                                    />
                                <?php echo $brand; ?>
                            </label></li>
                    <?php endforeach; ?>
                </ul>
            </li>
        <?php endif; ?>
        <li class="filter-price">
            <label class="filter-label">
                <input type="hidden" name="show[price]" value="0" />
                <input type="checkbox" name="show[price]" value="1"
                    <?php if (!isset($this->settings['price']) || $this->settings['price']): ?>
                        checked
                    <?php endif; ?>
                    />
                <?php echo $this->translate('Price'); ?>
            </label>
        </li>
        <?php foreach ($this->filters as $filterId => $filter) : ?>
            <?php $show = !isset($this->settings[$filter['name']]) || !empty($this->settings[$filter['name']]); ?>
            <li data-attributeId="<?php echo $filterId; ?>">
                <label class="filter-label">
                    <input type="hidden" name="show[<?php echo $filter['name']; ?>]" value="none" />
                    <?php if (!isset($filter['values'])) : ?>
                        <input type="checkbox" name="show[<?php echo $filter['name']; ?>]" value="1"
                            <?php if (!isset($this->settings[$filter['name']]) || !empty($this->settings[$filter['name']])): ?>
                                checked
                            <?php endif; ?>
                            />
                    <?php else : ?>
                        <input type="checkbox" class="mass-change" title="<?php echo $this->translate('toggle all'); ?>"
                            <?php if (!isset($this->settings[$filter['name']]) || (is_array($this->settings[$filter['name']])
                                && sizeof($this->settings[$filter['name']]) === sizeof($filter['values']))) { ?>
                                checked
                            <?php } ?>
                            />

                    <?php endif; ?>
                    <?php echo $filter['label']; ?>
                </label>
                <?php if (!empty($filter['values'])) : ?>
                    <?php if (sizeof($filter['values']) > 10) { ?>
                        <span title="<?php echo $this->translate('show/hide nested elements'); ?>"
                              class="toggle-nested">&#177;</span>
                    <?php } ?>
                    <ul <?php if (!$show) { ?>style="display: none"<?php } ?> >
                        <?php foreach ($filter['values'] as $value => $count) : ?>
                            <li>
                                <label>
                                    <input type="checkbox"
                                           name="show[<?php echo $filter['name']; ?>][<?php echo $value; ?>]"
                                           value="1"
                                           title="<?php echo $this->translate('Check to hide from users'); ?>"
                                        <?php if (!isset($this->settings[$filter['name']]) ||
                                            (is_array($this->settings[$filter['name']]) && isset($this->settings[$filter['name']][$value])) ) { ?>
                                            checked
                                        <?php } ?>
                                        />
                                    <?php
                                    echo $value;
                                    ?></label>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
    <div class="footer">
        <p class="msg"><?php echo $this->translate('Log out from your admin account in order to view final navigation layer.'); ?></p>
        <button class="btn" type="submit"><?php echo $this->translate('Save '); ?></button>
    </div>
</form>

<style type="text/css">
    .plugin-filtering-widget ul {
        margin: 0 0 0 10px;
        padding: 5px;
    }

    .plugin-filtering-widget ul li {
        list-style: none;
        padding: 0;
        margin: 0;
        position: relative;
    }

    .plugin-filtering-widget > ul > li:nth-child(odd) {
        background-color: #eee;
    }

    .plugin-filtering-widget ul label.filter-label {
        font-weight: bold;
        cursor: pointer;
    }

    .plugin-filtering-widget ul span.toggle-nested {
        position: absolute;
        top: 0;
        right: 0;
        cursor: pointer;
    }

    .plugin-filtering-wrap {
        width: auto;
        overflow: hidden;
        position: relative;
        border: 3px dashed #eee;
    }

    .plugin-filtering-wrap > h4 {
        border-bottom: 3px dashed #eee;
        padding: 3px;
        text-transform: uppercase;
    }

    .plugin-filtering-wrap > h4 > span {
        font-size: 80%;
    }

    .plugin-filtering-wrap > .footer {
        border-top: 3px dashed #eee;
    }

    .plugin-filtering-wrap label > input[type=checkbox] {
        cursor: pointer;
    }

    .msg {
        border-bottom: 3px dashed #eee;
        font-size: 85%;
    }
</style>